### PR TITLE
Estimation of river turbidity using sentinel-2 satellite data

### PR DESCRIPTION
**Pull request by shivanip32**
This notebook shows how river turbidity can be estimated using satellite data without any field measurement.

-----

# Checklist

Please go through each entry in the below checklist and mark an 'X' if that condition has been met. Every entry should be marked with an 'X' to be get the Pull Request approved.

- [x] All `import`s are in the first cell? First block of imports are standard libraries, second block are 3rd party libraries, third block are all `arcgis` imports? Note that in some cases, for samples, it is a good idea to keep the imports next to where they are used, particularly for uncommonly used features that we want to highlight.
- [x] All `GIS` object instantiations are one of the following?
    - `gis = GIS()`
    - `gis = GIS('https://www.arcgis.com', 'arcgis_python', 'P@ssword123')`
    - `gis = GIS(profile="your_online_profile")`
    - `gis = GIS('https://pythonapi.playground.esri.com/portal', 'arcgis_python', 'amazing_arcgis_123')`
    - `gis = GIS(profile="your_enterprise_portal")`
- [ ] If this notebook requires setup or teardown, did you add the appropriate code to `./misc/setup.py` and/or `./misc/teardown.py`?
- [x] If this notebook references any portal items that need to be staged on AGOL/Python API playground, did you coordinate with a Python API team member to stage the item the correct way with the api\_data\_owner user?
- [x] Code refactored & split out across multiple cells, useful comments?
- [x] Consistent voice/tense/narrative style? Thoroughly checked for typos?
- [x] All images used like `` instead of ``? All map widgets contain a static image preview? (Call `mapview_inst.take_screenshot()` to do so)
- [ ] All file paths are constructed in an OS-agnostic fashion with `os.path.join()`? (Instead of `r"\foo\bar"`, `os.path.join(os.path.sep, "foo", "bar")`, etc.)
- [x] **IF YOU WANT THIS SAMPLE TO BE DISPLAYED ON THE DEVELOPERS.ARCGIS.COM WEBSITE**, ping @ DavidJVitale so he can add it to the list for the next deploy

### CODE REVIEW

**Comment by shivanip32** [comment]
ArcGIS/geosaurus/issues/4245

**Comment by AtmaMani** [comment]
@moonlanderr thanks for the review
@mohi9282 can you do the second round of reviews?

**Comment by mohi9282** [comment]
@shivanip32 this is a very informative sample and I loved going through the details. I have recommended some minor changes for the language for your review.

cc: @AtmaMani

**Comment by shivanip32** [comment]
@mohi9282 & @moonlanderr thank you for reviewing the sample. I have updated the notebook with suggested changes.

cc. @AtmaMani & @priyankatuteja

**Comment by AtmaMani** [comment]
@mohi9282 could you verify the revision and approve the PR?

**Comment by mohi9282** [comment]
@shivanip32 - thanks for the updates. Requesting minor changes to date format at 1 place and some conclusion verbiage.

**Review by moonlanderr — APPROVED** [review]

**Comment by shivanip32** [comment]
@mohi9282, thank you for reviewing my notebook, I have updated the changes.

cc. @AtmaMani & @priyankatuteja

**Review by mohi9282 — APPROVED** [review]
Looks good

**Review by priyankatuteja — CHANGES_REQUESTED** [review]
@shivanip32 I have suggested minor changes, in addition to those if you can rename file from river_turbidity_estimation_using_sentinel2_data_for_allahabad to river_turbidity_estimation_using_sentinel2. Thanks!

**Comment by priyankatuteja** [comment]
@shivanip32 
As discussed, the image needs to be replaced too.

**Comment by shivanip32** [comment]
@priyankatuteja, I have updated the image in sample.

**Comment by shivanip32** [comment]
@priyankatuteja, I have updated the image in sample.

**Review by AtmaMani — APPROVED** [review]

**Comment by AtmaMani** [comment]
@shivanip32 thanks for the sample. @moonlanderr @mohi9282 @priyankatuteja thank you for the detailed reviews

**Pull request merged**
