### PR TITLE
Parameters changed for replicas.create(...)

### PR DESCRIPTION
**Pull request by CMPeng**
https://github.com/ArcGIS/geosaurus/issues/1812

1. geometry_filter is required
2. creating replica in 'filegdb' data format will not list the generated replica in the /repplicas rest endpoint; however, with data_format="sqlite" solves the problems.

```
replica1 = ports_flc.replicas.create(replica_name = 'arcgis_python_api_2',
                                    layers='0',
                                    data_format='filegdb',
                                    out_path = 'E:\\demo')
replica1
```
changed to 
```
geometry_filter1 = {
                        'geometry':'8608022.3,1006191.2,8937015.9,1498443.1',
                        'geometryType':'esriGeometryEnvelope'
                    }

replica1 = precip_flc.replicas.create(replica_name = 'arcgis_python_api_precip',
                                      layers='0',
                                      geometry_filter=geometry_filter1,
                                      sync_model="perLayer",
                                      target_type="server",
                                      data_format="sqlite",
                                      out_path=r'/arcgis/home')
replica1
```

### CODE REVIEW

**Comment by AtmaMani** [comment]
@CMPeng can you specify geometry filter using `arcgis.geometry.Geometry` objects instead of as a dictionary? One idea is to geocode a place, get its extent and use that as an envelope. We should minimize using raw dicts and promote reuse of our Objects.

Also, did the sqlite db download to the specified location after you called create?

**Comment by CMPeng** [comment]
@AtmaMani 
The extents used here is extracted from the service's full extents; so the modifications here used show the steps to automate the extraction of extents to be geometry filter. Please check if OK.
```
geometry_filter1 = {
                        'geometry':'8608022.3,1006191.2,8937015.9,1498443.1',
                        'geometryType':'esriGeometryEnvelope'
                    }
```
vs
```
extents =ports_flc.properties['fullExtent']
extents_str = ",".join(format(x, "10.3f") for x in [extents['xmin'],extents['ymin'],extents['xmax'], extents['ymax']])
extents_str
```
```
geom_filter = {'geometryType':'esriGeometryEnvelope'}
geom_filter.update({'geometry':extents_str})
geom_filter
```
BTW. I tried creating a Geometry object and used it directly as the input value for `geometry_filter` but it does not work out. Seems to be `dict` type required.

**Comment by AtmaMani** [comment]
@CMPeng I prefer the latter pattern of getting the geometry and like your changes. It shows where you got those numbers from. Can you make an explicit statement that the sqlite db is download in the location? Just a line will do. All other changes look good!

As part of ArcGIS/geosaurus#1812, we can evaluate if the API can support [envelope](https://esri.github.io/arcgis-python-api/apidoc/html/arcgis.geometry.html#envelope) objects and if we can provide a default extent (using your logic of getting from feature layer's ext) and keep that parameter optional.

**Comment by AtmaMani** [comment]
@CMPeng could you update this notebook to use the PYthon API playground credentials?

**Comment by CMPeng** [comment]
@AtmaMani Can you please review again?
1. use pythonapi profile
2. add markdown cell to note that the replica is created inside \arcgis\home

**Comment by AtmaMani** [comment]
looks good, thanks @CMPeng

**Pull request merged**
