### PR TITLE
detecting settlements notebook added

### PR DESCRIPTION
**Pull request by guneetmutreja**
This fixes the issue no: 2868 

In this notebook, we detect settlements using the traditional supervised classification (SVM) approach and DL (Unet) approach. We compare their results against each other.

### CODE REVIEW

**Comment by guneetmutreja** [comment]
ArcGIS/geosaurus#2868

**Comment by guneetmutreja** [comment]
<p>@moonlander All changes suggested are now been resolved. Please have a look.</p>

**Comment by moonlanderr** [comment]
changes approved

**Comment by AtmaMani** [comment]
@guneetmutreja this is a great sample. I like the text narratives, charts, maps, everything is well done and refined. The approach of using SVM output to Unet model is well brought out. Explanations for nuances like how you initialize weights for remaining bands, why you unfreeze, are important and is brought out quite well. @moonlanderr @priyankatuteja thanks for the detailed reviews.

**Pull request merged**
