### PR TITLE
chennai floods set time extents

### PR DESCRIPTION
**Pull request by CMPeng**
Note:
This is not the final draft, still need to use take_screenshot() to handle all map widgets outputs...

Change - 
As in cell [50]
```
import pandas as pd
from arcgis import geometry
from IPython.display import Image

img_items = []

def filter_images(my_map, where_clause, suffix):
    global df

    selected = ls_water_lyr.filter_by(where=where_clause, geometry=geometry.filters.intersects(ls_water_lyr.extent))
    # Option 1
    # my_map.add_layer(selected.mean())
    
    # Option 2
    # blend_lyr = selected._mosaic_operation('blend')
    # blend_lyr.properties.spatialReference = blend_lyr.properties.extent.spatialReference    
    # lyr = blend_lyr.save('blend_lyr' + suffix, for_viz=True)
    # my_map.add_layer(lyr)
    
    # Option 3
    mean_lyr = selected.mean()
    savedimg = mean_lyr.export_image(bbox=area['extent'], size=[1200,450], f='image', save_folder='.', save_file='mean_lyr'+suffix+'.jpg')
    img_items.append(open('mean_lyr'+suffix+'.jpg','rb').read())
    
    fs = selected.query(out_fields="AcquisitionDate, GroupName, Month, JulianDay, WRS_Row, WRS_Path, Name", 
                  return_geometry=True,
                  return_distinct_values=False)
    tdf = fs.sdf
    df = tdf
    tdf['Time'] = pd.to_datetime(tdf['AcquisitionDate'], unit='ms') 
    print(df.shape)
    
    return tdf
```

There are three ways of implementing this - but options 1 and 2 both displayed unexpectedly due to "add_layer" while option 3 shows the expected result.

Added on Mar 1st,
```
search_rainfall = gis.content.search("Chennai_precipitation", 
                              item_type="feature service", 
                              outside_org=True)
if len(search_rainfall) >= 1:
    rainfall = search_rainfall[0]
else:
    # if the "Chennai_precipitation" web layer does not exist
    # import any pandas data frame, with an address field, as a layer in our GIS
    import pandas as pd
    df = pd.read_csv('data/Chennai_precipitation.csv')
    # Create an arcgis.features.FeatureCollection object by importing the pandas dataframe with an address field
    rainfall = gis.content.import_data(df, {"Address" : "LOCATION"})
```

### CODE REVIEW

**Comment by achapkowski** [comment]
@CMPeng you do not need: `global df` in your first line of your method. Unless totally needed, always avoid `global`.

**Comment by rohitgeo** [comment]
@CMPeng good to know you have 3 workarounds! Can you go with #3 that shows the expected results? Thanks!

**Comment by CMPeng** [comment]
Thanks @achapkowski  - the global var is removed;
@rohitgeo The other two options are removed from the sample, but I really think there might be something strange with add_layer() since it is not displaying the image service as expected :(
@Yongyao since the chennai_precipitation layer is somewhat not existent any more, I added something to have it publish if search_results are empty list.

**Comment by rohitgeo** [comment]
@cmpeng we are able to get a similar thing working for pre-fire and mid-fire imagery in https://github.com/Esri/arcgis-python-api/blob/master/samples/04_gis_analysts_data_scientists/california_wildfires_2017_thomas_fire_analysis.ipynb

Can you please look into what's different here? 

cc @rhea-j

**Comment by CMPeng** [comment]
Hi @rohitgeo  The reason that in the sample, imageries for pre-fire and mid-fire show as different maps is that one is loading just basemap and the other draws from imagery layer. If pre-fire and mid-fire both come from filtered results of the same imagery layer, but with different temporal extents (in this case, using diff objectid), they will look the same in the maps e.g. If we insert an extra cell after cell [9]:
Cell [9]
```
prefire = landsat.filter_by('OBJECTID=668630') # 2017-11-23 
midfire = landsat.filter_by('OBJECTID=681950') # 2017-12-09
``` 
Add extra cell [10]
```
address = 'Montclair Dr, Ventura, CA'
location = geocode(address)[0]

fire_map1 = gis.map(location)
fire_map1.add_layer(prefire)

fire_map2 = gis.map(location)
fire_map2.add_layer(midfire)

fire_map1.layout=Layout(flex='1 1', padding='6px', height='450px')
fire_map2.layout=Layout(flex='1 1', padding='6px', height='450px')

box = HBox([fire_map1, fire_map2])
box
```

**Comment by rohitgeo** [comment]
@DavidJVitale this may need a fix in the map widget. Can you look into this?

**Comment by DavidJVitale** [comment]
@rohitgeo I have looked into this with @CMPeng and will hopefully make a fix soon. It's on my radar.

**Comment by CMPeng** [comment]
@rohitgeo 
Thanks to @DavidJVitale 's fixing the add_layer(...) issue, the map widget display now also takes in the MosaicRule, and the HBox display of the sample is looking good.
image

Please approve the change in the temporal filtering part of this sample -
```
def filter_images(my_map, start_year, end_year):
    selected = ls_water_lyr.filter_by(where="(Year = " + str(start_year) + ")", 
                                      time=[dt.datetime(start_year, 1, 1), dt.datetime(end_year, 1, 1)],
                                      geometry=arcgis.geometry.filters.intersects(ls_water_lyr.extent))
    print("Applicable lockRasterIds=", selected._mosaic_rule.get("lockRasterIds"))
    my_map.add_layer(selected.mean())
    
    fs = selected.query(out_fields="AcquisitionDate, GroupName, Month, JulianDay, WRS_Row, WRS_Path")
    tdf = fs.sdf  
    print(tdf.shape)
    return tdf
```

Though the sample ran alright, I think there might be something strange with the filter_by(time=[...]).
If removing the where clause in the method definition, the filtered results will list other results that fall outside of the time span.

**Comment by rohitgeo** [comment]
@CMPeng it's great to have this working. Thanks for the fix. Please open an issue regarding the issue with removing the where clause in the geosaurus repo and @rhea-j can look into this.

**Comment by rohitgeo** [comment]
There are embedded maps with black background like these in the notebook:
image

Also, we need to embed the screenshots of the side-by-side HBox maps.

**Comment by CMPeng** [comment]
> There are embedded maps with black background like these in the notebook:
> image
> 
> Also, we need to embed the screenshots of the side-by-side HBox maps.

@DavidJVitale 
Do you know if this is a limitation of the take_screenshot() method? I got the background as all black when the original map has transparency set.

@rohitgeo 
For the HBox screenshot, it is a known issue (https://github.com/ArcGIS/geosaurus/issues/1789 logged to David). Do you want it to be just a static image embedded as a workaround for now?
And will log a bug for @rhea-j with the temporal filtering issue.

**Comment by rohitgeo** [comment]
@CMPeng yes, let's just use a static image embedded for the HBox screenshot. For the other maps too, lets use static screenshots till we are able to fix the take_screenshot() method.

**Comment by CMPeng** [comment]
@rohitgeo 
Please see the latest commit for (a) embedding the static image for HBox, and (b) opacity removed from add_layer(), and hence screenshot's background color comes back to transparent.
Also, I am not entitled to assign the issue https://github.com/Esri/arcgis-python-api/issues/388 to @rhea-j; Can you please help? Thanks!

**Comment by DavidJVitale** [comment]
@rohitgeo @CMPeng The default implementation of `take_screenshot()` does a `.jpg`, which doesn't allow for transparency. I just fixed this here: https://github.com/ArcGIS/geosaurus/pull/1803

Let me know if this isn't the solution you were looking for. See the PR for more info.

**Comment by CMPeng** [comment]
Thanks David for fixing the `"rasterFunction" failed to add to map widget` bug, and the latest commit includes these changes -
1. Use the "chennai population" layer instead of the "soil management" item since the latter not able to add to map view (generateToken failure)
2. Use the new band combination to display land/water boundaries in place of the deprecated imagery service (as Rhea suggested)
3. "distrcit_name" column no longer exists in the dataframe, instead, using "NAME" in the sample.

@rohitgeo @AtmaMani Can either of you please review it again? Thanks a lot!

**Comment by rohitgeo** [comment]
@CMPeng 

1. I noticed we replaced
`gis = GIS("https://www.arcgis.com", "arcgis_python", "P@ssword123")` with 
gis = GIS(profile = "your_online_profile")

This will cause the sample to not run out of the box for those who havent set the profile and dont know about the demo account... will this profile be set in the Try it Live environment?


2. Can we replace all occurrences of 'feature service' with 'feature layer' when doing gis.content.search()? In the Web GIS UX and the Python API, we reference them as layers - they are backed by services eventually but to users theyre just layers that be be added to a map.

3. We could remove the stray `ls_water_lyr.properties.extent.spatialReference`. This looks like a debug message/query

4. We could comment out the print statements in `filter_images()`, especially the one using the hidden _mosaic_rule

5. Excellent work on this sample - thank you.

**Comment by CMPeng** [comment]
Thanks @rohitgeo for the suggestions, and they are addressed in the latest commit.

For (1), I have added the u/p way of making GIS connection in the comments so if user wants to try a different way other than profile, they can use the alternative. 

And yes, we are going to replacing u/p with profile in more and more samples. If I understand correctly per discussions with @AtmaMani and @DavidJVitale this profile is created by David within the CICD infrastructure, and hence "your_enterprise_profile" and "your_online_profile" will just work for the nightly test runs, though not sure about the "Try it Live" scenario.

@AtmaMani or @DavidJVitale, can you please help answer the question? Thanks!!

**Comment by DavidJVitale** [comment]
@rohitgeo we made the decision to have all our samples use `GIS(profile = "your_online_profile")` or `GIS(profile = "your_ent_profile")`. It's the cleanest way to have our samples run nightly as a QA measure (we have 1 level of misdirection), and it promotes a good security standard for our end users.

It will __not__ work out of the box at the moment in the "Try it Live" environment. We decided that using the samples as QA took a higher priority over the "Try it Live" environment working perfectly, since the "Try it Live" will probably be changing in the future to be an AGOL ArcGIS Notebooks environment. We can potentially look into making this work in the "Try it Live" environment if you think it's a high enough priority, or maybe we add a comment about the demo account?

@AtmaMani feel free to add in any other info.

**Comment by CMPeng** [comment]
@rohitgeo Please check out the latest changes with the embedded image re-added. thanks!

**Comment by AtmaMani** [comment]
Notes: this PR is tracked at https://github.com/ArcGIS/geosaurus/issues/1857

**Pull request merged**
