### PR TITLE
updated workflow in `Calculating cost surfaces using weighted overlay analysis` sample notebook

### PR DESCRIPTION
**Pull request by jyaistMap**
- updating the workflows for a sample notebook: _GIS analysts and data scientists > Calculating cost surfaces using weighted overlay analysis_

### CODE REVIEW

**Comment by jyaistMap** [comment]
- map widget images for maps at end of notebook (last 3 steps) in #186

**Comment by AtmaMani** [comment]
@jyaistMap the sample is well improved thanks. Can you update the notebook so it has the raster algebra gif. Another change is to decorate the code in "Invoking Raster Analysis on Portal for ArcGIS" paragraph.

**Comment by jyaistMap** [comment]
@AtmaMani I've decorated the code with backticks. Can you tell me where the raster algebra gif is? Where do you see it fitting in the notebook?

**Comment by jyaistMap** [comment]
Thanks @rohitgeo 
* modified import statement to `from arcgis.raster.functions import *` and simplified subsequent code
* edited _Invoking...on Portal for ArcGIS_ to _Invoking...ArcGIS Enterprise_
* expanded _Intro_ to provide context for why we do these types of analyses 
* removed `try...except` from connect to `GIS` step
* used map algebra in `colormap` function and changed output name to `result_weighted_overlay`

**Comment by rohitgeo** [comment]
Thanks for making the changes @jyaistMap

**Pull request merged**
