### PR TITLE
Shipwrecks detection notebook

### PR DESCRIPTION
**Pull request by guneetmutreja**
Contains sample notebook to detect shipwrecks from bathymetry data using MaskRCNN

### CODE REVIEW

**Comment by AtmaMani** [comment]
@guneetmutreja this is a nice sample, I have requested for a couple of changes. @priyankatuteja thanks for the first round of reviews.

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/639/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Hey, I couldn't get this one. Can you please elaborate a bit.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/639/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
currently it looks like:

image

**Comment by AtmaMani** [comment]
<p style="user-select: auto;">Sure, below is an example of what I am looking for:</p><pre class="ql-syntax" spellcheck="false" style="user-select: auto;">arcpy.ia.ExportTrainingDataForDeepLearning(in_raster="shaded_Relief",
out_folder=r"\\Training_data_MaskRCNN", in_class_data="training_data_wrecks", 
image_chip_format="TIFF",
tile_size_x=256, 
tile_size_y=256, 
stride_x=0, 
stride_y=0, 
output_nofeature_tiles="ONLY_TILES_WITH_FEATURES", metadata_format="RCNN_Masks",
start_index=0, 
class_value_field="ecode"....) 
</pre><p style="user-select: auto;">so on.</p><p style="user-select: auto;">This pattern of <code>arg_name=value</code>  makes the snippet very readable. I'd encourage this pattern not just for ArcPy but for every cell in future.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/639/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/639/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
