### PR TITLE
updated column name and map images in `which_college_district_has_the_fewest_low_income_families.ipynb`

### PR DESCRIPTION
**Pull request by ManushiM**
* Resolves [source repo #9686](https://github.com/ArcGIS/geosaurus/issues/9686)
 - changed column name
 - added map images
 - refer to [issue](https://github.com/ArcGIS/geosaurus/issues/9686).

-----

# Checklist

Please go through each entry in the below checklist and mark an 'X' if that condition has been met. Every entry should be marked with an 'X' to be get the Pull Request approved.

- [ ] All `import`s are in the first cell? 
    - [ ] First block of imports are standard libraries
    - [ ] Second block are 3rd party libraries
    - [ ] Third block are all `arcgis` imports? Note that in some cases, for samples, it is a good idea to keep the imports next to where they are used, particularly for uncommonly used features that we want to highlight.
- [ ] All `GIS` object instantiations are one of the following?
    - `gis = GIS()`
    - `gis = GIS('home')` or `gis = GIS('pro')`
    - `gis = GIS(profile="your_online_portal")`
    - `gis = GIS(profile="your_enterprise_portal")`
- [ ] If this notebook requires setup or teardown, did you add the appropriate code to `./misc/setup.py` and/or `./misc/teardown.py`?
- [ ] If this notebook references any portal items that need to be staged on AGOL/Python API playground, did you coordinate with a Python API team member to stage the item the correct way with the `api_data_owner` user?
- [ ] If the notebook requires working with local data (such as CSV, FGDB, SHP, Raster files), upload the files as items to the [Geosaurus Online Org](geosaurus.maps.arcgis.com/) using `api_data_owner` account and change the notebook to first download and unpack the files.
- [ ] Code simplified & split out across multiple cells, useful comments?
- [ ] Consistent voice/tense/narrative style? Thoroughly checked for typos?
- [ ] All images used like `` instead of ``? All map widgets contain a static image preview? (Call `mapview_inst.take_screenshot()` to do so)
- [ ] All file paths are constructed in an OS-agnostic fashion with `os.path.join()`? (Instead of `r"\foo\bar"`, `os.path.join(os.path.sep, "foo", "bar")`, etc.)
- [ ] Is your code formatted using [Jupyter Black](https://www.freecodecamp.org/news/auto-format-your-python-code-with-black/)? You can use Jupyter Black to format your code in the  notebook.
- [ ] **IF YOU WANT THIS SAMPLE TO BE DISPLAYED ON THE DEVELOPERS.ARCGIS.COM WEBSITE**, ping @ mohi9282 so he can add it to the list for the next deploy

### CODE REVIEW

**Comment by ManushiM** [comment]
Thanks @CMPeng ! Oh this is odd. On my end I do not see the empty map. This is what I see.
image

But probably, github isn't rendering the mapview. So maybe leaving an empty mapview with the screenshot might make the notebook readable at least?

**Review by CMPeng — APPROVED** [review]
Got u!

**Review by cariashuang0417 — COMMENTED** [review]
image
@ManushiM , looks like the "summary_fields" parameter in `summarize_with` function also needs modification. I've checked the census_track data and found the column name is actually "income_lt_30k". Could you double check it?

**Review by jyaistMap — CHANGES_REQUESTED** [review]
Hi Manushi -
* I just submitted a PR to your fork to update this branch with the `take_screenshot()` method for embedding map content

**Comment by ManushiM** [comment]
Thanks, @jyaistMap ! This looks good. I can't approve my own PR sadly, and we may need someone else to approve it.

**Comment by jyaistMap** [comment]
Hi @ManushiM - Can you merge the PR I submitted to the `college_district-low-icome-families` branch on your fork?  Once you do that, you need to push the changes that were just merged into your fork back up to this repo so they appear in this PR. Does that make sense?

**Comment by ManushiM** [comment]
@jyaistMap I merged your PR to this branch. Doesn't that already add your changes, or do I need to perform another step?

**Comment by jyaistMap** [comment]
Tested on local build. looks great!

**Comment by jyaistMap** [comment]
> @jyaistMap I merged your PR to this branch. Doesn't that already add your changes, or do I need to perform another step?

Nope. Your good. My mistake...you don't need to push anything up it does it automatically.

**Pull request merged**
