### PR TITLE
adding a new sample for ogc services

### PR DESCRIPTION
**Pull request by CMPeng**
Adding a new sample for ogc services (per requests from Jim Mason and Jun)
 - WMTS
 - WMS
 - WFS

@jyaistMap Can you please shed lights onto this sample? many thanks! (I closed a similarly named pr since it was not rooted from next branch to start with and I fear that might cause conflicts)

### CODE REVIEW

**Comment by CMPeng** [comment]
Hi @jyaistMap,
Please see your comments addressed in the latest notebook; I have separated service and layers as two different concepts; simplify adding them to web maps (if possible); and modify how WFS is rendered in the notebook (use a WFS that is in 3857, and also use `print` to replace the original drawing happening within map widget [the current approach involves print utility from enterprise or online, and does not require map widget to reproject the wfs]). Thanks,
Chunming

**Comment by CMPeng** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/Esri/arcgis-python-api/pull/1395/discussion/) on ReviewNB
> 
> _jyaistMap commented on 2022-12-19T22:01:15Z_ ----------------------------------------------------------------
> 
> Why is the _upload_size _argument used when adding this type of item but not in any of other _add _methods in the notebook? Would an explanation of this argument be helpful?

Added a one-line statement in the new commit. This is an optional parameter, the other notebooks never mentioned that one can set the upload_size in situations of multi-part uploading (this parameter sets the limit per batch).

**Comment by CMPeng** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/Esri/arcgis-python-api/pull/1395/discussion/) on ReviewNB
> 
> _jyaistMap commented on 2022-12-19T22:01:16Z_ ----------------------------------------------------------------
> 
> It looks like this dictionary was created by hand so it could then be assigned to the _wfs_txt _variable. How would a user know how to build this dictionary? Again, if you think that a user with experience with these layers and services, ignore this. I would not myself understand how to jump from knowing a WFS url to building a dictionary with all the keys and values of the layer and also its fields. If you're able to go from the url to getting some kind of layer that then would have these properties, that would be easy to follow. Can the _wfs_url _be used to create an _OGCFeatureService _layer and then the properties from there can be used to build this dictionary? Again - I'm super inexperienced with this kind of data, but these are the questions that come up in my mind when I look at this.

Good question, John (but also a complicated question). First thing first, I have added some explanations on how to get information from `GetCapabilities` and `DescribeFeatureType` calls with `WFS` in the new commit, and shortened the `wfs_txt` needed for input in the notebook, hope now that it is clearer for readers.

Then, how would a user know the right procedures needed to create a `wfs`? currently, Python API does not provide straight-forward solutions for user to do a simple `WFSLayer()` initialization. So a user has to write the WFS from scratch, or follow the sample cell I wrote here (guess that's why Jim Mason and Jun found our API difficult to use for OGC services in the first place). (Good news is, we support WMS and WMTS Layer construction now)

Last, "Can the _wfs_url _be used to create an _OGCFeatureService _layer and then the properties from there can be used to build this dictionary?" Unfortunately it can't. I tried but failed~ The code underneath was trying to fetch an endpoint that ends with `HostedFeatureService` - I think this endpoint is for hosted services instead of services published on the server side (e.g. WFS). The procedures to publish a WFS service item used in the notebook is what we can do with Python API for now. Hopefully that in the future there will be improvements (esp. to how it being rendered in the map widget).

**Comment by jyaistMap** [comment]
Hi @CMPeng 
 * Thank you for adding the explanatory text - to me this reads much better in that it guides me on where the information is coming from that was used to construct that `wfs_txt` dictionary. 
 * I think providing the link in the guide suffices to provide users who might be new with an outlet for investigating the background if they so choose. Given it's a sample, I think it's fair to target more advanced users and provide newer users this link.

I'm inclined to merge this sample and then we can update it in the future if we think that's necessary.

**Review by jyaistMap — APPROVED** [review]
LGTM. Thanks, @CMPeng!

**Pull request merged**
