### PR TITLE
resolves issue#9773, fixed `using_and_updating_GIS_content.ipynb`

### PR DESCRIPTION
**Pull request by tarunkukreja003**
resolves [#9773](https://github.com/ArcGIS/geosaurus/issues/9773) , fixed `using_and_updating_GIS_content.ipynb`, 
-> data is now available
-> fixed the error **_there is no attribute called baseMap for WebMap['baseMap']_** with **_WebMap.basemap_**

environment used:
-> arcgis version - 2.2.0.1
-> arcgis pro - 3.2.1
-> python - 3.9.18

### CODE REVIEW

**Comment by tarunkukreja003** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1738/discussion/#comment-1918327380'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tarunkukreja003** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1738/discussion/#comment-1918327393'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jyaistMap** [comment]
@tarunkukreja003 

* the cells where maps are supposed to appear are blank when previewing the site with a local build. We should correct these before merging this PR:

image

image

image

**Review by jyaistMap — CHANGES_REQUESTED** [review]
We need to review this guide on how to draw the map widgets.

**Comment by tarunkukreja003** [comment]
maps now being displayed

**Review by ManushiM — APPROVED** [review]
LGTM

**Review by jyaistMap — APPROVED** [review]
Build site locally and all looks good.

**Pull request merged**
