### PR TITLE
change geonet to Esri Community and add links

### PR DESCRIPTION
**Pull request by jyaistMap**
@mohi9282 @CMPeng
  * not sure why the files changed section in this PR seems to change the whole notebook. I only edited the last cell, entitled _How this website is organized_
  * in response to feedback email from `ResourceCtr-feedback@esri.com`:
    *  change the word `geonet` to `Esri Community` and add a link to the Esri Community homepage
    * add links to the `guides`, `samples`, `api-ref`, and specific `ArcGIS API for Python Community` home page

### CODE REVIEW

**Comment by CMPeng** [comment]
Hi @jyaistMap all looks good to me, except for the `samples notebooks` link, it is pointing to a page that not exists (as opened from ReviewNB).

**Comment by jyaistMap** [comment]
Thanks @CMPeng  - oops! Fixed it.

**Comment by CMPeng** [comment]
@jyaistMap The new commit still opened in a 404 page for me. Will using `../../samples/` and `../../api-reference` work?

**Comment by jyaistMap** [comment]
Hi @CMPeng - based on discussions with the Developer Website team, we've learned when writing Guides, links to other guide pages work through relative paths (`../`), but links to the `samples` and `api-reference` must begin with (`/python/`). When I hover over `sample-notebooks` and `api reference` text and look at the url that shows up in the lower left hand corner, the syntax looks correct based on what @mohi9282 and I have learned about how the new website builds pages.

Any additional thoughts, @mohi9282?

**Review by CMPeng — APPROVED** [review]
Thanks @jyaistMap for the clarifications! LGTM.

**Pull request merged**
