### PR TITLE
Added MMSegmentation guide

### PR DESCRIPTION
**Pull request by guneetmutreja**
PR containing MMSegmentation guide.

### CODE REVIEW

**Comment by priyankatuteja** [comment]
@vikashranjan26 Could you please have a look at the technical doc. @guneetmutreja  Please get it reviewed from Vikash.

**Review by vikashranjan26 — APPROVED** [review]
LGTM

**Comment by guneetmutreja** [comment]
@kapil-varshney Can you please help review the guide?

**Comment by guneetmutreja** [comment]
@kapil-varshney Please review the changes.

**Review by kapil-varshney — APPROVED** [review]
LGTM

**Pull request merged**
