### PR TITLE
updated Accessing and creating content guide

### PR DESCRIPTION
**Pull request by jyaistMap**
* updated GIS to use profile
* fixed json featureCollection
* edited and reordered text

\<insert pull request description here\>

-----

# Checklist

Please go through each entry in the below checklist and mark an 'X' if that condition has been met. Every entry should be marked with an 'X' to be get the Pull Request approved.

- [ ] All `import`s are in the first cell? First block of imports are standard libraries, second block are 3rd party libraries, third block are all `arcgis` imports?
- [ ] All `GIS` object instantiations are one of the following?
    - `gis = GIS('https://www.arcgis.com', 'arcgis_python', 'P@ssword123')`
    - `gis = GIS(profile="your_online_profile")`
    - `gis = GIS('https://pythonapi.playground.esri.com/portal', 'arcgis_python', 'amazing_arcgis_123')`
    - `gis = GIS(profile="your_enterprise_portal")`
- [ ] If this notebook requires setup or teardown, did you add the appropriate code to `./misc/setup.py` and/or `./misc/teardown.py`?
- [ ] If this notebook references any portal items that need to be staged on AGOL/Python API playground, did you coordinate with a Python API team member to stage the item the correct way with the api\_data\_owner user?
- [ ] Code refactored & split out across multiple cells, useful comments?
- [ ] Consistent voice/tense/narrative style? Thoroughly checked for typos?
- [ ] All images used like `` instead of ``? All map widgets contain a static image preview? (Call `mapview_inst.take_screenshot()` to do so)
- [ ] All file paths are constructed in an OS-agnostic fashion with `os.path.join()`? (Instead of `r"\foo\bar"`, `os.path.join(os.path.sep, "foo", "bar")`, etc.)

### CODE REVIEW

**Comment by AtmaMani** [comment]
@DavidJVitale could you do the first round of reviews on this PR

**Comment by jyaistMap** [comment]
@AtmaMani 
* added `data` directory in `the-gis` containing the csv files
* updated the code to use the data in that directory
* added code to copy source earthquakes file and paste with a unique name to avoid file name conflicts on the portal with `add()`
* added unique string to the end of the `item` title to avoid service name conflicts on `publish()`

**Comment by AtmaMani** [comment]
@jyaistMap thanks, looks good.
For future, at 
```python
csv_file = os.path.basename(csv_path)
csv_root, csv_ext = csv_file.split('.')
```
when extracting filename and extension from a file, I find `pathlib.Path` class robust. This is because you can have filenames with one or more periods which are not part of the extension. For instance,

```python
from pathlib import Path
p = Path('../some_folder/filename.secondword.csv')
print(p.stem)   # 'filename.secondword'
print(p.suffix)  # '.csv'
```

**Comment by jyaistMap** [comment]
Thanks for the tip @AtmaMani Funny you mention it...just walked through some exercises using `pathlib` yesterday.

**Pull request merged**
