### PR TITLE
Cloning complex apps master

### PR DESCRIPTION
**Pull request by nparavicini7**
master version of #1674

### CODE REVIEW

**Comment by CMPeng** [comment]
Thanks @nparavicini7 for the great write-up. I am just having some trivial questions while running the notebook on my side. Great job!

**Comment by nparavicini7** [comment]
<p>In what way were you trying to add random id's? To the cloning call, or the item mapping dictionary?</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1695/discussion/#comment-1767326193'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nparavicini7** [comment]
<p>No, this was an example I was using for debugging issues at the time when Playground Enterprise was experiencing issues. It's expected to work now. This guide was adapted from the UC talk John and I gave, where this was included as well. I figured I'd keep it in there as an example</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1695/discussion/#comment-1767326210'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nparavicini7** [comment]
<p>Are you trying to run this through your own Jupyter setup or online notebooks? Sometimes preview() has auth issues</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1695/discussion/#comment-1767326101'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nparavicini7** [comment]
<p>Yes will make that clear</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1695/discussion/#comment-1767326241'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by CMPeng** [comment]
<blockquote>Are you trying to run this through your own Jupyter setup or online notebooks? Sometimes preview() has auth issues</blockquote><p>In my local jupyter notebook, I am using a devext org as my destination to clone stuff...</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1695/discussion/#comment-1767326101'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by CMPeng** [comment]
<blockquote>In what way were you trying to add random id's? To the cloning call, or the item mapping dictionary?</blockquote><p>I cloned a FS from AGOL to devext, then try to feed that FS's item id to the value of the mapping dict (key being the story map's id on devext), then clone_items() would just fail. What's the item #502...? is it some layers included in the storymap (I cannot access your this item and hence not know what type of item it is)?</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1695/discussion/#comment-1767326193'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nparavicini7** [comment]
<p>Ah okay gotcha. So the key for the item mapping should be the FS that it's meant to replace, not the storymap.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1695/discussion/#comment-1767326193'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nparavicini7** [comment]
<p>Okay gotcha. Are popups enabled in the browser in which you interact with your notebooks? Sometimes popups being disabled will mess up authentication</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1695/discussion/#comment-1767326101'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by CMPeng — APPROVED** [review]
Thank you for addressing all bullet points I suggested. LGTM! @nparavicini7

**Pull request merged**
