### PR TITLE
New admin sample to find top 'n' items in an org

### PR DESCRIPTION
**Pull request by AtmaMani**
Sample notebook for GIS admins demonstrates how to construct search queries to find the top 100 / 200 / n items that match a particular criteria.

-----

# Checklist

Please go through each entry in the below checklist and mark an 'X' if that condition has been met. Every entry should be marked with an 'X' to be get the Pull Request approved.

- [x] All `import`s are in the first cell? First block of imports are standard libraries, second block are 3rd party libraries, third block are all `arcgis` imports? Note that in some cases, for samples, it is a good idea to keep the imports next to where they are used, particularly for uncommonly used features that we want to highlight.
- [x] All `GIS` object instantiations are one of the following?
    - `gis = GIS()`
    - `gis = GIS('https://www.arcgis.com', 'arcgis_python', 'P@ssword123')`
    - `gis = GIS(profile="your_online_profile")`
    - `gis = GIS('https://pythonapi.playground.esri.com/portal', 'arcgis_python', 'amazing_arcgis_123')`
    - `gis = GIS(profile="your_enterprise_portal")`
- [x] Code refactored & split out across multiple cells, useful comments?
- [x] Consistent voice/tense/narrative style? Thoroughly checked for typos?
- [x] All file paths are constructed in an OS-agnostic fashion with `os.path.join()`? (Instead of `r"\foo\bar"`, `os.path.join(os.path.sep, "foo", "bar")`, etc.)
- [ ] **IF YOU WANT THIS SAMPLE TO BE DISPLAYED ON THE DEVELOPERS.ARCGIS.COM WEBSITE**, ping @ DavidJVitale so he can add it to the list for the next deploy

### CODE REVIEW

**Comment by AtmaMani** [comment]
Closes https://github.com/ArcGIS/geosaurus/issues/4862

**Comment by AtmaMani** [comment]
@jyaistMap could you review this sample?

**Comment by AtmaMani** [comment]
@DavidJVitale could you review this as @jyaistMap is out of office?

**Review by DavidJVitale — APPROVED** [review]
LGTM! this will be a good addition to our admin samples. Approved

**Pull request merged**
