### PR TITLE
updated `part4_visualizing_time_enabled_data_on_the_map_widget.ipynb`

### PR DESCRIPTION
**Pull request by ManushiM**
Changes:
* Changed the `set_time_period` method
* Replaced gifs with updated ones
* Removed `ready` method and replaced it with time lag
* Updated markdown description as required

### CODE REVIEW

**Comment by nanaeaubry** [comment]
@ManushiM Looks good just left very small comments!

**Comment by cariashuang0417** [comment]
Overall LGTM, thanks Manushi! Just left a comment for the parameters for the time_extent() function.

**Comment by ManushiM** [comment]
Thanks for the feedback, I addressed these changes in the next PR.

**Review by jyaistMap — CHANGES_REQUESTED** [review]
* the part4 guide looks good
* the part3 guide is also included in this PR and needs to be removed from your branch. It is using the old 2.3 syntax and should be updated in a separate branch

**Review by jyaistMap — APPROVED** [review]
* part3 no longer present and page looks good rendered locally

**Pull request merged**
