### PR TITLE
Apache 2.0 license specified

### PR DESCRIPTION
**Pull request by AtmaMani**
@rohitgeo I believe with this, we can merge dev to master. If there is nothing else to review, could you create a release with name `v1.0` so the download link is [https://github.com/Esri/arcgis-python-api/archive/v1.0.zip](https://github.com/Esri/arcgis-python-api/archive/v1.0.zip)

### CODE REVIEW

**Comment by rohitgeo** [comment]
Will do, @AtmaMani... Great work on this guide!

**Comment by rohitgeo** [comment]
@AtmaMani merged and released v1.0!

**Comment by AtmaMani** [comment]
thanks @rohitgeo

**Comment by scw** [comment]
@rohitgeo @AtmaMani 🚀 💯 Congrats! I've put the release up on the [Esri channel](https://anaconda.org/Esri/arcgis).

**Pull request merged**
