### PR TITLE
Adds Mussel Farm Detection using MMDetection sample notebook

### PR DESCRIPTION
**Pull request by kapil-varshney**

### CODE REVIEW

**Review by shivanip32 — APPROVED** [review]

**Review by BP-Ent — CHANGES_REQUESTED** [review]
Suggested changes made on ReviewNB

**Comment by kapil-varshney** [comment]
> Suggested changes made on ReviewNB

Thanks @BP-Ent. @priyankatuteja @AtmaMani, the notebook has been updated with the requested changes. Please approve.

**Review by priyankatuteja — APPROVED** [review]

**Comment by AtmaMani** [comment]
@kapil-varshney great sample. Can you edit the filename and title to be more specific? I have added some suggestions in the review comments. @shivanip32 @BP-Ent thank you for the detailed reviews.

**Comment by kapil-varshney** [comment]
> @kapil-varshney great sample. Can you edit the filename and title to be more specific? I have added some suggestions in the review comments. @shivanip32 @BP-Ent thank you for the detailed reviews.

@AtmaMani Thanks for the suggestion. I have changed the name/title to Detecting Mussel Farms using Deep Learning.

**Comment by kapil-varshney** [comment]
> @kapil-varshney great sample. Can you edit the filename and title to be more specific? I have added some suggestions in the review comments. @shivanip32 @BP-Ent thank you for the detailed reviews.

@AtmaMani Thanks for the suggestion. I have changed the name/title to Detecting Mussel Farms using Deep Learning.

**Review by AtmaMani — APPROVED** [review]

**Pull request merged**
