### PR TITLE
SAR to RGB using CycleGAN nb

### PR DESCRIPTION
**Pull request by guneetmutreja**
Contains NB for SAR to RGB image translation using CycleGAN

### CODE REVIEW

**Comment by guneetmutreja** [comment]
@sdash77 Can you please help review this sample.

**Comment by sdash77** [comment]
@shivanip32 Can you do the initial round of review.

**Comment by shivanip32** [comment]
@guneetmutreja, This is a great sample, I have added some suggestions.

**Comment by guneetmutreja** [comment]
@shivanip32 Thank you for reviewing the sample. I have made all the changes you mentioned, please verify them.

**Review by shivanip32 — APPROVED** [review]

**Comment by sdash77** [comment]
@guneetmutreja Can you update the notebook for inferening in pro as its now working.

**Review by AtmaMani — APPROVED** [review]

**Pull request merged**
