### PR TITLE
added release notes for release 1.5.1

### PR DESCRIPTION
**Pull request by jyaistMap**
@AtmaMani @DavidJVitale 
* I recall we changed our workflow that we were pushing releases to the developers site from `master` rather than `dev_site_current`. Let me know if I recall that incorrectly and should push to a different branch. 
* @DavidJVitale Let me know if I should instead run through the process of converting these to html and issue a PR directly to the developers site

### CODE REVIEW

**Comment by DavidJVitale** [comment]
Hey John, looks great -- few comments, remove the strikethrough line and address the bolded differences in the map widget section. And that section should go under 'Fixes', not 'New'. Otherwise looks great!

   "* Numerous fixes __and__ enhancements to the [`map widget`](https://esri.github.io/arcgis-python-api/apidoc/html/arcgis.gis.toc.html#arcgis.gis.GIS.map)\n",
    "  * Added a compass to 2D mode to re-orient north\n",
    "  ~~* Fixed map widget display issues with `tempnb` on notebooks.esri.com \n",~~
    "  * Fixed bug where custom symbology was not _properly displaying__\n",
    "  * Fixed issue when `map.layers` returned incorrect data type for layers\n",
    "  * Fixed issue for an exported map widget not honoring the extent\n",
    "  * Added ability to use __portal__ basemaps with map widget\n",

**Comment by jyaistMap** [comment]
Thanks for reviewing @DavidJVitale and @AtmaMani - 
 * FYI...changed the phrasing on 2 bullet points in the `map widget` fixes and enhancements...and moved it to the Fixes section

**Comment by AtmaMani** [comment]
@jyaistMap the line "Fixed load performance for [gis.map()]https://esri.github.io/arcgis-python-api/apidoc/html/arcgis.gis.toc.html#arcgis.gis.GIS.map() objects" has formatting issue, otherwise it looks good

**Comment by jyaistMap** [comment]
ok, thanks @AtmaMani and @DavidJVitale - think I got all the incorrect hyperlinks and formatting issues cleared up

**Pull request merged**
