### PR TITLE
add the geometry guides in 3 parts

### PR DESCRIPTION
**Pull request by CMPeng**
as referenced in https://github.com/ArcGIS/geosaurus/issues/3217

part 1 - introduction
part 2 - spatial operations
part 3 - spatial filtering

@AtmaMani Though the `as_arcpy()` is not showing correctly in the preview, it did show the expected shape in the `nbviewer.jupyter.org/github/Esri/arcgis-python-api/blob/xxx` link. I am not sure if the shape preview is to be present when the PR gets merged.

### CODE REVIEW

**Comment by AtmaMani** [comment]
@jyaistMap could you do the first round of reviews?

**Comment by jyaistMap** [comment]
Sorry @AtmaMani and @CMPeng - I missed this from a few days ago. I'll review right now.

**Comment by jyaistMap** [comment]
<p>Not sure if this is a problem in my environment, or on drawing without arcpy? </p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/701/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by PGCHM** [comment]
Thank you so much @jyaistMap for all the detailed comments, and yes I think most of the differences are due to that the sample needs to be run on arcpy, and running on a shapely geom engine would result in completely different result (and I have hence created an issue to summarize all the differences between arcpy and shapely driven cases at https://github.com/ArcGIS/geosaurus/issues/3725)

I can go ahead to add arcpy as pre-requisite condition before running this sample, or add a table to explain what are supported and not supported with/out arcpy, whichever sounds better to you.

Since @AtmaMani said he was currently modifying the PR directly on his side, maybe I should wait till he completes the revision and then to check in changes addressing John's comments?

**Comment by CMPeng** [comment]
(Sorry I was placing the previous response using a personal GitHub account, and had to revert it) 
Thank you so much @jyaistMap for all the detailed comments, and yes I think most of the differences are due to that the sample needs to be run on arcpy, and running on a shapely geom engine would result in completely different result (and I have hence created an issue to summarize all the differences between arcpy and shapely driven cases at https://github.com/ArcGIS/geosaurus/issues/3725)

I can go ahead to add arcpy as pre-requisite condition before running this sample, or add a table to explain what are supported and not supported with/out arcpy, whichever sounds better to you.

Since @AtmaMani said he was currently modifying the PR directly on his side, maybe I should wait till he completes the revision and then to check in changes addressing John's comments?

**Comment by AtmaMani** [comment]
@CMPeng yes, I am editing the initial notebooks. I will try to push them up as soon as possible. Please wait until I push up this PR

**Comment by jyaistMap** [comment]
Thanks @CMPeng. I think a prerequisite note about `arcpy` would really help readers of the guide. And +1 for a table summarizing differences between `arcpy` and `shapely`!

**Comment by jyaistMap** [comment]
I wasn't sure how to best review given @AtmaMani said he was making some changes directly, so I opted for doing them in NBReview.

**Comment by AtmaMani** [comment]
<p>This draws on my Mac env</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/701/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AtmaMani** [comment]
<p>yes, I removed this cell</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/701/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AtmaMani** [comment]
<p>I edited it to show the type of the object returned.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/701/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AtmaMani** [comment]
<p>I removed this part and moved it to a few cells earlier</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/701/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AtmaMani** [comment]
<p>thanks, addressed</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/701/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AtmaMani** [comment]
<p>I agree it is very helpful. I have elaborated a bit.</p><p>I cannot hyperlink functions like <code>union</code>  <code>difference</code>  yet because we have not yet discussed the two patterns (which have two separate hyperlinks for hte same functions)</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/701/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AtmaMani** [comment]
<p>Yes good idea</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/701/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AtmaMani** [comment]
<p>agreed, changed to a complex geometry</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/701/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AtmaMani** [comment]
<p>I agree, I am displaying these geometries every now and then.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/701/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AtmaMani** [comment]
<p>agreed, replaced with a complex geometry</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/701/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AtmaMani** [comment]
<p>beautiful!</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/701/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AtmaMani** [comment]
<p>I agree. There isnt much information about this on Desktop or REST API doc. We can work on this as an enhancement</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/701/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AtmaMani** [comment]
<p>good idea, added.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/701/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AtmaMani** [comment]
@CMPeng thank you for this wonderful guide! @jyaistMap thanks for your detailed review. I was able to implement (or had already implemented) most of your suggestions.
@CMPeng I expanded some topics and broke the 3 parts into 4 parts. I had edited some cells for clarity, simplified a few and added illustrations when it seemed complex to comprehend. Please take a look and let me know.

**Comment by CMPeng** [comment]
<p>Thank you soooooooo much @AtmaMani for putting all these pieces together, and I really appreciate your time and efforts in revising the original guides. They look so much better now with the explanations added in Part 1, and more more maps to the final part.</p><p>I noticed that you have removed all the callings of geometryObj.arcpy, so it would not cause any trouble when users are running with only shapely... As such, does that mean I dont need to add the table that illustrates shapely V.S. arcpy any more? since it is now somewhat hidden in the context? Thanks!!</p>

**Comment by AtmaMani** [comment]
<p>You are welcome @CMPeng. Yes I was able to verify that about 90% of the snippets work in non-ArcPy env just as we expect them to. The remaining 10% are known limits in shapely and you have rightly mentioned them in the notebook. </p><p> </p><p>Yes, I removed the <code>as_arcpy</code>  cells and made a note to users about that. As a next step lets investigate if you can automatically switch the iPython display logic to detect if ArcPy is used as backend or not, so the user does not have to</p>

**Pull request merged**
