### PR TITLE
SuperResolution guide

### PR DESCRIPTION
**Pull request by mayank2**
\<insert pull request description here\>

-----

# Checklist

Please go through each entry in the below checklist and mark an 'X' if that condition has been met. Every entry should be marked with an 'X' to be get the Pull Request approved.

- [ ] All `import`s are in the first cell? First block of imports are standard libraries, second block are 3rd party libraries, third block are all `arcgis` imports? Note that in some cases, for samples, it is a good idea to keep the imports next to where they are used, particularly for uncommonly used features that we want to highlight.
- [ ] All `GIS` object instantiations are one of the following?
    - `gis = GIS()`
    - `gis = GIS('https://www.arcgis.com', 'arcgis_python', 'P@ssword123')`
    - `gis = GIS(profile="your_online_profile")`
    - `gis = GIS('https://pythonapi.playground.esri.com/portal', 'arcgis_python', 'amazing_arcgis_123')`
    - `gis = GIS(profile="your_enterprise_portal")`
- [ ] If this notebook requires setup or teardown, did you add the appropriate code to `./misc/setup.py` and/or `./misc/teardown.py`?
- [ ] If this notebook references any portal items that need to be staged on AGOL/Python API playground, did you coordinate with a Python API team member to stage the item the correct way with the api\_data\_owner user?
- [ ] Code refactored & split out across multiple cells, useful comments?
- [ ] Consistent voice/tense/narrative style? Thoroughly checked for typos?
- [ ] All images used like `` instead of ``? All map widgets contain a static image preview? (Call `mapview_inst.take_screenshot()` to do so)
- [ ] All file paths are constructed in an OS-agnostic fashion with `os.path.join()`? (Instead of `r"\foo\bar"`, `os.path.join(os.path.sep, "foo", "bar")`, etc.)
- [ ] **IF YOU WANT THIS SAMPLE TO BE DISPLAYED ON THE DEVELOPERS.ARCGIS.COM WEBSITE**, ping @ DavidJVitale so he can add it to the list for the next deploy

### CODE REVIEW

**Comment by sandeepgadhwal** [comment]
fixes https://github.com/ArcGIS/geosaurus/issues/4159

**Comment by andy121090** [comment]
Is it possible to provide training data for the jupyter notebook? It would be easier to try the sample without having to create  training data using ArcGIS Pro or similar.

**Comment by priyankatuteja** [comment]
> t possible to provide training data for the jupyter notebook? It would be easier to try the sample without having to create training data using ArcGIS Pro or similar.

Hey @andy121090 The notebook has been updated with the training data. You could try that out now.

**Comment by priyankatuteja** [comment]
@sandeepgadhwal Can you please help @mayank2 complete the left over in this guide. Hope to have it inside by 1.8.3 release

**Review by guneetmutreja — CHANGES_REQUESTED** [review]
As discussed, please update the guide with the following information:
1. Explain the newly added "Export Tiles" format for the data creation for SuperResolution model
2. Add it's implementation in arcgis.learn module.
3. If the inferencing steps involved for this model is different than others, I suggest we should add those too.

**Comment by priyankatuteja** [comment]
@guneetmutreja Could you review it

**Review by guneetmutreja — APPROVED** [review]
Looks Good, thanks for the changes.

**Comment by priyankatuteja** [comment]
@mayank2 We should change notebook name to lowercase

**Comment by priyankatuteja** [comment]
@mayank2 
Also as we have a sample notebook already on the page, we could add one line in the end:

To learn more about the workflow of SuperResolution model, you could refer to ....the sample notebook (provide hyperlink)

**Review by priyankatuteja — APPROVED** [review]

**Review by AtmaMani — APPROVED** [review]
Looks good

**Comment by andy121090** [comment]
Hey @priyankatuteja, I tried to follow the guide described in https://developers.arcgis.com/python/sample-notebooks/increase-image-resolution-using-superresolution/ but still getting an error:
Screenshot 2021-02-11 at 15 46 44

**Comment by priyankatuteja** [comment]
@andy121090 I just tried it at my end. It works
image
Could you restart the kernel and try again? To save time as you already downloaded the data, pass in the path of the downloaded training data directly into the path variable.

**Comment by priyankatuteja** [comment]
@andy121090 If it still doesn't work, could you then try using `conda install -c esri arcgis=1.8.3` and try re-running it. This will help me know if this issue is related to environment or arcgis version.

**Comment by andy121090** [comment]
@priyankatuteja I figured it out, the problem is that somehow the extraction of _increase-image-resolution-using-superresolution.zip_ yields _increase-image-resolution-using-superresolution_subset_. Thus `data_path = Path(os.path.join(os.path.splitext(filepath)[0]))` is not correct.
Screenshot 2021-02-11 at 20 12 16

**Comment by priyankatuteja** [comment]
@andy121090 Thanks! I am updating the item with correct name.

**Comment by priyankatuteja** [comment]
@andy121090 The item is now updated correctly. It should work fine! Thanks for reporting it.

**Comment by priyankatuteja** [comment]
@andy121090 The item is now updated correctly. It should work fine! Thanks for reporting it.

**Pull request merged**
