### PR TITLE
Image scene classification sample notebook

### PR DESCRIPTION
**Pull request by 1297rohit**
Added Image Scene Classification Sample Notebook for issue https://github.com/ArcGIS/geosaurus/issues/7337.

Fixed somethings in coastline_classification_using_feature_classifier

### CODE REVIEW

**Comment by priyankatuteja** [comment]
@anushriyaj  Could you help in review of this sample.

**Comment by 1297rohit** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
<p>done</p><p> </p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by anushriyaj** [comment]
LGTM

**Comment by AtmaMani** [comment]
@BP-Ent could you please review this PR?

**Review by BP-Ent — CHANGES_REQUESTED** [review]
Suggested changes made on reviewnb

**Comment by 1297rohit** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
Made the suggested changes in the notebook.

**Review by BP-Ent — CHANGES_REQUESTED** [review]
Minor change suggested on reviewnb. Looks good apart from that!

**Comment by 1297rohit** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1120/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by 1297rohit** [comment]
Made the suggested changes in the notebook.

**Review by BP-Ent — APPROVED** [review]

**Review by AtmaMani — CHANGES_REQUESTED** [review]
Great sample. Can you update all file names so they have just lower cases? You might have to update the links to the video and image files within the notebook as well.

**Comment by 1297rohit** [comment]
Made changes as per the suggestion.

**Comment by AtmaMani** [comment]
Thank you @1297rohit

**Review by AtmaMani — APPROVED** [review]

**Comment by priyankatuteja** [comment]
@AtmaMani Could you revert this pr, as this can't be merged until 3.0 pro is released

**Comment by AtmaMani** [comment]
@priyankatuteja reverted using https://github.com/Esri/arcgis-python-api/pull/1148

**Pull request merged**
