### PR TITLE
Updated Raster Info sample portal to pythonapi playground for Montana image.

### PR DESCRIPTION
**Pull request by jyaistMap**
* updated the portal url to reflect portalapi after creating Imagery Layer
* minor text edits
* sample varies extensively from the [current Raster Info sample](https://developers.arcgis.com/python/sample-notebooks/creating-raster-information-product-using-raster-analytics/) on dev site

### CODE REVIEW

**Comment by AtmaMani** [comment]
@jyaistMap I had the same question, the output cells are empty in this notebook (which is good as we need it empty for notebooks.esri.com) as well as the dev current site. Could you check on it

**Comment by jyaistMap** [comment]
Thanks for the heads up @AtmaMani and @rohitgeo I'll add links to the output images this morning.

**Comment by jyaistMap** [comment]
@AtmaMani @rohitgeo Added images to correct directory and updated links in the notebook.

**Comment by jyaistMap** [comment]
Should be all set now, @AtmaMani

**Pull request merged**
