### PR TITLE
Unet land cover classification sample

### PR DESCRIPTION
**Pull request by Yongyao**
@AtmaMani This sample demonstrates the full workflow of Unet classification and is ready for review.

### CODE REVIEW

**Comment by Yongyao** [comment]
@DavidJVitale @achapkowski Questions about displaying imagery layer. 
1. The opacity parameter doesn't seem to be working.
2. Is there a way to load the colormap from an existing imagery layer (like https://datascienceadv.esri.com/portal/home/item.html?id=c20a7fde3b5c4f63beae7bc24367ec4b)  and apply it to another layer? Right now, I have to manually define a long colormap.

image

**Comment by DavidJVitale** [comment]
@Yongyao  I haven't tested the opacity parameter with a colormap output, only a hosted feature layer. Can you make an issue put a reproducible notebook in it so I can investigate? Much thanks.

**Comment by AtmaMani** [comment]
@CMPeng could you review the first version of this sample?

**Comment by CMPeng** [comment]
Hi @Yongyao please see below for some questions I have -
1. duplicate `context`
```
export = learn.export_training_data(input_raster=naip_input_layer,
                                    output_location=samplefolder,
                                    input_class_data=label_layer.url, 
                                    chip_format="JPEG", 
                                    tile_size={"x":400,"y":400}, 
                                    stride_size={"x":0,"y":0}, 
                                    metadata_format="Classified_Tiles",                                        
                                    context={"startIndex": 0, "exportAllTiles": False, "cellSize": 2},
                                    context = context,
                                    gis = potal_gis)
```
2. hosted elsewhere
Do you know if this is as designed that when hosting the notebook on qaext, but running it with a portal_gis instance that points to datascienceadv, that the call would just fail? If hosted on datascienceadv, then it passes.
```
classify_land_model_package = portal_gis.content.add(item_properties={"type":"Deep Learning Package a1",
                                                                "typeKeywords":"Deep Learning, Raster",
                                                                "title":"Land_Cover_Kent_DL_Model",
                                                                "tags":"deeplearning", 'overwrite':'True'}, 
                                                     data=model_package)
```
3. typo in conclusions -
`In thise notebook`

**Comment by Yongyao** [comment]
@CMPeng Yes, it only works on datascienceadv because `data=model_package` points to a local data folder. Also, this require RA server to work.

**Pull request merged**
