### PR TITLE
change detector notebook updates

### PR DESCRIPTION
**Pull request by kapil-varshney**
Updates the CycleGAN sample notebook with the new export format support in Pro and the 'Detect Changes Using Deep Learning' tool for inference.

### CODE REVIEW

**Comment by priyankatuteja** [comment]
@kapil-varshney  
1. please update the item containing image collection with new format data. 
2. in the inferencing part, please provide a webmap with results obtained from inferencing.

**Comment by mohi9282** [comment]
@kapil-varshney - any updates on the requested changes? Changes need to be reviewed and merged ASAP as the notebook is scheduled for V1.9.1.

cc: @AtmaMani @priyankatuteja

**Comment by mohi9282** [comment]
removing from v1.9.1 milestone per discussion with Kapil.

**Comment by kapil-varshney** [comment]
@priyankatuteja The training data in the new format and notebook can be found at:
 \\ndhfs2\swap\Kapil Varshney\tasks\25_update_sample_changedet
The results are not as good as in the old version. Please look into it.

**Comment by priyankatuteja** [comment]
closing pr, as discussed, i will take it up

**Pull request closed without merging**
