### PR TITLE
sfm-derived point cloud notebook - for cars and background classification

### PR DESCRIPTION
**Pull request by vbhv14**
- [x] added main content and provided sample data for the notebook in the form of `zip`.

### CODE REVIEW

**Review by guneetmutreja — CHANGES_REQUESTED** [review]
Please incorporate the changes discussed, if possible.

**Comment by vbhv14** [comment]
@guneetmutreja 
I have incorporated the suggested changes.
verify the changes for approval.
thanks.

**Review by guneetmutreja — APPROVED** [review]
Looks good to me.

**Comment by guneetmutreja** [comment]
@BP-Ent Can you help review this NB?
@priyankatuteja This nb looks good to me, please carry out the next rounds of review.

**Review by BP-Ent — CHANGES_REQUESTED** [review]
Suggested changes made in ReviewNB

**Comment by vbhv14** [comment]
@BP-Ent thanks, I have incorporated the changes.
let me know if there are any additional edits.

**Review by BP-Ent — APPROVED** [review]

**Review by AtmaMani — APPROVED** [review]
Looks good, nice article. I like the numerous useful suggestions presented in the data prep part of the sample - would come in handy.

**Comment by AtmaMani** [comment]
@vbhv14 thanks for the sample. @guneetmutreja @BP-Ent thanks for your detailed reviews!

**Pull request merged**
