### PR TITLE
adds image captioning guide

### PR DESCRIPTION
**Pull request by divyanshj16**
@priyankatuteja @guneetmutreja Please review this.

### CODE REVIEW

**Comment by priyankatuteja** [comment]
@divyanshj16 Please have a look at the changes suggested.

**Review by anurag89sharma — APPROVED** [review]

**Comment by anurag89sharma** [comment]
Looks fine to me.

**Review by priyankatuteja — CHANGES_REQUESTED** [review]
image

This isn't fixed yet

**Review by priyankatuteja — APPROVED** [review]

**Review by jyaistMap — CHANGES_REQUESTED** [review]
Made small grammar suggestion. Looks good.

**Review by AtmaMani — APPROVED** [review]

**Pull request merged**
