### PR TITLE
detect poppy blooms sample

### PR DESCRIPTION
**Pull request by CMPeng**
Addressed Issues @AtmaMani found in https://github.com/ArcGIS/geosaurus/issues/2267
Thanks Atma!!

For more correspondence to the revision suggestions, please refer back to the #2267 (I have added bullet points for those that need further explanations).

### CODE REVIEW

**Comment by CMPeng** [comment]
@AtmaMani Do you mind reviewing the latest commit? I have addressed the above mentioned four revision comments.
Thanks!

**Comment by AtmaMani** [comment]
@CMPeng all changes look good but the bokeh charts are now duplicated. I am able to see the interactive charts, so can you remove the screenshots?

**Comment by CMPeng** [comment]
Hi @AtmaMani 
do you mean that you can see duplicate bokeh plots for Figures 3,4,5, 7 and 8 now? 
But I am not able to see the duplicate ones from ReviewNB and the PR though...

**Comment by AtmaMani** [comment]
I was able to see the duplicate charts when viewing via nbviewer. The best way to check this is to export to HTML

Sent from my iPhone

On Aug 20, 2019, at 5:40 PM, Chunming Peng <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @AtmaMani<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_AtmaMani&d=DwMCaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=xHWT1UKrSPwunDr8iPrAMQ&m=-tMeI_8372QppjGvrZwM23ztp5rHgEV8UH0cveFtkyA&s=Ga0BwFx-31cN3UipbgyF3ygRQjFio15z5I7uV7ZoOHQ&e=>
do you mean that you can see duplicate bokeh plots for Figures 3,4,5, 7 and 8 now?
But I am not able to see the duplicate ones from ReviewNB and the PR though...

**Comment by CMPeng** [comment]
@AtmaMani 
I have removed the bokeh plots from the ipynb. Turns out the html created with nbconvert already has the dynamic plots... Can you please review again? thanks!

**Pull request merged**
