### PR TITLE
adding edge_detection_sample_notebook

### PR DESCRIPTION
**Pull request by sdash77**
# Checklist

Please go through each entry in the below checklist and mark an 'X' if that condition has been met. Every entry should be marked with an 'X' to be get the Pull Request approved.

- [ ] All `import`s are in the first cell? First block of imports are standard libraries, second block are 3rd party libraries, third block are all `arcgis` imports? Note that in some cases, for samples, it is a good idea to keep the imports next to where they are used, particularly for uncommonly used features that we want to highlight.
- [ ] All `GIS` object instantiations are one of the following?
    - `gis = GIS()`
    - `gis = GIS('https://www.arcgis.com', 'arcgis_python', 'P@ssword123')`
    - `gis = GIS(profile="your_online_profile")`
    - `gis = GIS('https://pythonapi.playground.esri.com/portal', 'arcgis_python', 'amazing_arcgis_123')`
    - `gis = GIS(profile="your_enterprise_portal")`
- [ ] If this notebook requires setup or teardown, did you add the appropriate code to `./misc/setup.py` and/or `./misc/teardown.py`?
- [ ] If this notebook references any portal items that need to be staged on AGOL/Python API playground, did you coordinate with a Python API team member to stage the item the correct way with the api\_data\_owner user?
- [ ] Code refactored & split out across multiple cells, useful comments?
- [ ] Consistent voice/tense/narrative style? Thoroughly checked for typos?
- [ ] All images used like `` instead of ``? All map widgets contain a static image preview? (Call `mapview_inst.take_screenshot()` to do so)
- [ ] All file paths are constructed in an OS-agnostic fashion with `os.path.join()`? (Instead of `r"\foo\bar"`, `os.path.join(os.path.sep, "foo", "bar")`, etc.)
- [ ] **IF YOU WANT THIS SAMPLE TO BE DISPLAYED ON THE DEVELOPERS.ARCGIS.COM WEBSITE**, ping @ DavidJVitale so he can add it to the list for the next deploy

### CODE REVIEW

**Review by guneetmutreja — CHANGES_REQUESTED** [review]
Please incorporate the suggested changes.

**Comment by guneetmutreja** [comment]
Also, please provide the data to export training data like raster file and feature class

**Review by guneetmutreja — CHANGES_REQUESTED** [review]
Please incorporate the changes requested.

**Comment by priyankatuteja** [comment]
@guneetmutreja What's the update on this one? Is it running fine now?

**Comment by guneetmutreja** [comment]
@priyankatuteja the NB needs updates. @sdash77 Please incorporate the changes as suggested.

**Comment by guneetmutreja** [comment]
@priyankatuteja the NB needs updates. @sdash77 Please incorporate the changes as suggested.

**Review by guneetmutreja — CHANGES_REQUESTED** [review]
The tool throws an error while running Polygon To Centerline tool, request a re-check of the tool.

**Review by guneetmutreja — CHANGES_REQUESTED** [review]
The tool throws an error while running Polygon To Centerline tool, request a re-check of the tool.

**Comment by guneetmutreja** [comment]
Kindly perform the following changes:

1. Change the screenshot of the results, inferencing should be done on nearby areas that are not used while training
2. Add a line: as the model has been trained on a limited amount of data, it is expected to only work well in nearby areas and similar geographies in the Results section of the notebook

**Review by guneetmutreja — APPROVED** [review]
Thanks for the changes @sdash77. Approving it.

**Review by priyankatuteja — CHANGES_REQUESTED** [review]
@sdash77 Please incorporate the changes suggested.

**Review by AtmaMani — APPROVED** [review]

**Pull request merged**
