### PR TITLE
Animal species identification NB

### PR DESCRIPTION
**Pull request by guneetmutreja**
Contains animal species identification notebook

-----

# Checklist

Please go through each entry in the below checklist and mark an 'X' if that condition has been met. Every entry should be marked with an 'X' to be get the Pull Request approved.

- [X] All `import`s are in the first cell? First block of imports are standard libraries, second block are 3rd party libraries, third block are all `arcgis` imports? Note that in some cases, for samples, it is a good idea to keep the imports next to where they are used, particularly for uncommonly used features that we want to highlight.
- [X] All `GIS` object instantiations are one of the following?
    - `gis = GIS()`
    - `gis = GIS('https://www.arcgis.com', 'arcgis_python', 'P@ssword123')`
    - `gis = GIS(profile="your_online_profile")`
    - `gis = GIS('https://pythonapi.playground.esri.com/portal', 'arcgis_python', 'amazing_arcgis_123')`
    - `gis = GIS(profile="your_enterprise_portal")`
- [X] If this notebook requires setup or teardown, did you add the appropriate code to `./misc/setup.py` and/or `./misc/teardown.py`?
- [X] If this notebook references any portal items that need to be staged on AGOL/Python API playground, did you coordinate with a Python API team member to stage the item the correct way with the api\_data\_owner user?
- [X] Code refactored & split out across multiple cells, useful comments?
- [X] Consistent voice/tense/narrative style? Thoroughly checked for typos?
- [X] All images used like `` instead of ``? All map widgets contain a static image preview? (Call `mapview_inst.take_screenshot()` to do so)
- [X] All file paths are constructed in an OS-agnostic fashion with `os.path.join()`? (Instead of `r"\foo\bar"`, `os.path.join(os.path.sep, "foo", "bar")`, etc.)
- [X] **IF YOU WANT THIS SAMPLE TO BE DISPLAYED ON THE DEVELOPERS.ARCGIS.COM WEBSITE**, ping @ DavidJVitale so he can add it to the list for the next deploy

### CODE REVIEW

**Comment by priyankatuteja** [comment]
@BP-Ent Your feedback will be very helpful. Please review this one.

**Comment by priyankatuteja** [comment]
@BP-Ent Your feedback will be very helpful. Please review this one.

**Review by BP-Ent — CHANGES_REQUESTED** [review]
Suggested changes made in ReviewNB

**Comment by guneetmutreja** [comment]
@BP-Ent Thank you for the detailed review. I have amended all the changes you suggested.

**Comment by guneetmutreja** [comment]
@BP-Ent Thank you for the detailed review. I have amended all the changes you suggested.

**Comment by guneetmutreja** [comment]
@priyankatuteja I have made the changes suggested by you, please have a look.

**Comment by priyankatuteja** [comment]
@guneetmutreja Thanks for the changes, a few more suggestions:
1. Change code from 
image

  to `Path(os.path.join(os.path.splitext(filepath)[0]))` 

2.  Can we provide an accurate link which directly downloads the data when clicked.
image

3. To make this sample running, we also need json file. i see the training data is provided so wither you can comment out these cells and mention that if the users want to  download the whole data then they may uncomment those cells. 
image

4. tfms not used, can we remove them
image

5. The default backbone is already resnet34, we may remove this from the method to make it look simpler.

6. can u do lr = model.lr_find(), then in fit method, model.fit(5, lr) will automate the workflow.

7. heading change: Inferencing -->Model Inference

8. We can also show the inferenced results on the map widget for visualization.
image
 
I think we should also mention in the note section about the arcgis enterprise version (10.8.1) used as classify objects isn't supported for older versions.

**Comment by priyankatuteja** [comment]
@guneetmutreja Thanks for the changes, a few more suggestions:
1. Change code from 
image

  to `Path(os.path.join(os.path.splitext(filepath)[0]))` 

2.  Can we provide an accurate link which directly downloads the data when clicked.
image

3. To make this sample running, we also need json file. i see the training data is provided so wither you can comment out these cells and mention that if the users want to  download the whole data then they may uncomment those cells. 
image

4. tfms not used, can we remove them
image

5. The default backbone is already resnet34, we may remove this from the method to make it look simpler.

6. can u do lr = model.lr_find(), then in fit method, model.fit(5, lr) will automate the workflow.

7. heading change: Inferencing -->Model Inference

8. We can also show the inferenced results on the map widget for visualization.
image
 
I think we should also mention in the note section about the arcgis enterprise version (10.8.1) used as classify objects isn't supported for older versions.

**Comment by priyankatuteja** [comment]
The resulting feature class after running inference tool returns invalid shape column that doesn't get displayed on the map widget. The fix has been made in 10.9 build. @guneetmutreja if this issue can be worked out with the released 10.8.1, we could move ahead else we should wait for the next release.

**Comment by priyankatuteja** [comment]
@guneetmutreja 10.8.1 is released, please re run your notebook against playground portal. Let me know when it's ready

**Comment by guneetmutreja** [comment]
@BP-Ent I have made all the changes you suggested, kindly verify and approve the same.
@priyankatuteja I have amended all the required changes. This notebook currently is supported on Enterprise 10.9 or later.

**Comment by guneetmutreja** [comment]
@BP-Ent I have made all the changes you suggested, kindly verify and approve the same.
@priyankatuteja I have amended all the required changes. This notebook currently is supported on Enterprise 10.9 or later.

**Review by BP-Ent — CHANGES_REQUESTED** [review]
Changes suggested on ReviewNB

**Comment by BP-Ent** [comment]
@guneetmutreja Just some minor revisions. Should be good to go after these!

**Comment by guneetmutreja** [comment]
@BP-Ent Thanks for the review, changes amended.

**Review by priyankatuteja — APPROVED** [review]

**Pull request merged**
