### PR TITLE
Remove guides using the jupyter_dashboards package

### PR DESCRIPTION
**Pull request by nanaeaubry**
Unable to find and install this package with current dependencies. Removing the three guides in this section that use the package

### CODE REVIEW

**Review by nparavicini7 — CHANGES_REQUESTED** [review]
There seems to be a new replacement package for jupyter dashboards, found here: https://github.com/voila-dashboards. @jyaistMap do you think we should try to keep these samples and rework with this new package, or just can them?

**Review by jyaistMap — APPROVED** [review]
* added note to the 3 samples and will merge this PR in a couple weeks

image

image

image

**Comment by jyaistMap** [comment]
> There seems to be a new replacement package for jupyter dashboards, found here: https://github.com/voila-dashboards. @jyaistMap do you think we should try to keep these samples and rework with this new package, or just can them?

Wish I would have seen your note @nparavicini7 before I hunted down that archived repo. We'll remove them for now, and then we can reconvene to see if there are samples worth exploring in the future.

**Comment by jyaistMap** [comment]
* merging and closing
* logged [#12126](https://github.com/ArcGIS/geosaurus/issues/12126) to investigate voila

**Review by nparavicini7 — APPROVED** [review]

**Pull request merged**
