### PR TITLE
crime clusters nb

### PR DESCRIPTION
**Pull request by priyankatuteja**
one of the examples at https://developers.arcgis.com/rest/services-reference/run-python-script-examples.htm

### CODE REVIEW

**Comment by AtmaMani** [comment]
@CMPeng could you do the first round of reviews for this PR?

**Comment by CMPeng** [comment]
@priyankatuteja Thanks for providing this wonderful notebook, very informational and inspiring, esp. when it introduces the usage of run_python_script_task(). Please checkout my comments posted above :)
cc @AtmaMani

**Comment by priyankatuteja** [comment]
<p>Thanks! @CMPeng I am not sure if i get your point. I would like to explain about the graph though, the top heading starts where it shows what all can be done with BDFS item. The notebook aims to showcase only these functionalities as mentioned in the graph. However, it doesn't mention how to create a BDFS or check if GIS has geoanalytics configured. Please help me know which part should i add from the first half of the notebook</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/663/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by priyankatuteja** [comment]
<p>Avoid using local paths, such as C:\bigdata, <strong>unless</strong> <strong>the same data folder is available on all nodes of the server site</strong>.</p><p> </p><p>I think i can explain it. People having enterprise account most likely have datastore and GA server on two different machines, Now the path has to be accessible to both the datastore and GA server. that said, it it is a local path, it may add BDFS successfully but people can run into errors like </p><p> </p><pre class="ql-syntax" spellcheck="false">{"messageCode":"BD_101042","message":"Unable to access file share.  Please verify that your ArcGIS Server user account has access to the file share."}
Failed to execute (DescribeDataset).
Failed.
</pre>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/663/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by priyankatuteja** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/663/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by priyankatuteja** [comment]
<p>good suggestion,, i can provide hyperlink to the page that explains how to read and write layer  pyspark <a href="https://developers.arcgis.com/rest/services-reference/using-webgis-layers-in-pyspark.htm" target="_blank">https://developers.arcgis.com/rest/services-reference/using-webgis-layers-in-pyspark.htm</a> </p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/663/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by priyankatuteja** [comment]
<p>good suggestion,, i can provide hyperlink to the page that explains how to read and write layer  pyspark <a href="https://developers.arcgis.com/rest/services-reference/using-webgis-layers-in-pyspark.htm" target="_blank">https://developers.arcgis.com/rest/services-reference/using-webgis-layers-in-pyspark.htm</a> </p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/663/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by priyankatuteja** [comment]
<p>Great!</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/663/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by priyankatuteja** [comment]
<p>silhouette score is what helps to know what value of n will give optimal number of clusters. I can provide hyperlink to some link explaining it</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/663/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by priyankatuteja** [comment]
<p>Good suggestion. Thanks for the wonderful suggestions.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/663/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by priyankatuteja** [comment]
<p>Good suggestion. Thanks for the wonderful suggestions.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/663/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by priyankatuteja** [comment]
@CMPeng  I have incorporated your suggestions. Thanks for taking out time to review.

**Comment by CMPeng** [comment]
<p>Hi @priyankatuteja I did not mean that you need to modify the graph, actually I think the graph itself is pretty self-explaining. Just that I think it is more relevant to the second half of your notebook, so might be better if placed before where you start using describe_data() or other related operations. If you would like to keep it at where it is, I am fine with that, but will recommend to add a figure caption stating that these operations will be discussed in later sections.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/663/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by priyankatuteja** [comment]
<p>I have added it in the middle of the introduction where it talks about all those tools providing an overview</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/663/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AtmaMani** [comment]
@priyankatuteja thanks for the sample, @CMPeng  thanks for reviewing. Looks good to me, merging.

**Pull request merged**
