### PR TITLE
guide `part2_locating_addresses` fixed for the new map widget

### PR DESCRIPTION
**Pull request by tarunkukreja003**
guide `part2_locating_addresses` fixed for the new map widget.

Following changes were made:

 - updating gis.map() to Map()
 -  adding `spatialReference` to convert location to Point to display on the map
 - updating links
 - updating/adding images
 - minor typos

### CODE REVIEW

**Review by nparavicini7 — CHANGES_REQUESTED** [review]
Looks great overall! Just had a couple really minor requests that I put in comments

**Comment by jyaistMap** [comment]
<p>Please add a hyperlink in that sentence:</p><p>For a list of valid WKID values, see the <a href="https://developers.arcgis.com/rest/services-reference/enterprise/using-spatial-references/" target="_blank">Using spatial references</a> documentation.</p><p> </p><ul><li>markdown hyperlinks are text surrounded by square brackets directly followed by parentheses with the url in it</li></ul>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1953/discussion/#comment-2316807408'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by jyaistMap — CHANGES_REQUESTED** [review]
- submitted [pr #8](https://github.com/tarunkukreja003/arcgis-python-api-fork/pull/8) on your fork

**Review by jyaistMap — APPROVED** [review]
looks good reviewed locally and nbreview

**Pull request merged**
