### PR TITLE
RA guide - image classification and segmentation

### PR DESCRIPTION
**Pull request by Yongyao**
https://github.com/ArcGIS/geosaurus/issues/2266

### CODE REVIEW

**Comment by Yongyao** [comment]
Thanks to @rhea-j , I was able to complete the image classification workflow.

**Comment by CMPeng** [comment]
thanks @Yongyao for the great guide - it is informative and straight to the point. 
I have some suggestions, mostly are for words/grammar. And some are just because I dont understand the concept/tool well enough, thinking it might be good that general readers can use more images or explanations.

**Comment by Yongyao** [comment]
@AtmaMani I've addressed @CMPeng 's comments and it's ready for you to review.

**Comment by AtmaMani** [comment]
@Yongyao looks good, I have asked for a map and suggested for a couple of changes

**Comment by Yongyao** [comment]
@AtmaMani I updated the notebook based on your comments.

**Comment by AtmaMani** [comment]
@Yongyao the classification section still shows only 1 output map with the input layer displayed (`filtered_image`). It would be useful to show this and the classified output next to it. Could you update this

**Comment by Yongyao** [comment]
@AtmaMani Another map showing the classification result has been added. I misunderstood you comments. Question: when displaying the filtered landsat imagery layer, it still shows the entire landsat layer rather than a single filtered image. Is this expected behavior?

**Comment by AtmaMani** [comment]
@Yongyao I think that is expected, per my understanding filter applies to full-resolution processing. To get the behavior of displaying a single scene, you might have to set a clip / mask. @CMPeng could you confirm?

**Comment by CMPeng** [comment]
@Yongyao and @AtmaMani , for the filtering, if you input some criteria but does not get selected results (instead a full set), I think that means your specified criteria is not valid. Try getting the `selected.filtered_rasters()` to see if the selection set is really been generated; if it is returning everything, then try the criteria again with the REST API.

**Comment by Yongyao** [comment]
`selected.filtered_rasters()` only returns the selected objectID and @CMPeng thinks this might be related to a JS issue that David fixed a while ago.  @DavidJVitale , would you mind taking a look when you get a chance?

**Comment by AtmaMani** [comment]
Merged this PR as the widget issue is separate and need not hold up this PR.

**Pull request merged**
