### PR TITLE
safe streets to school notebook

### PR DESCRIPTION
**Pull request by priyankatuteja**
This sample is based on ArcGIS learn lesson at https://learn.arcgis.com/en/projects/policy-mapping-safe-streets-to-schools/lessons/create-a-policy-map.htm

### CODE REVIEW

**Comment by AtmaMani** [comment]
@Yongyao could you do the first round of reviews for this sample?

**Comment by Yongyao** [comment]
@priyankatuteja Nicely written sample. Please see my comments through reviewNB

**Comment by AtmaMani** [comment]
@priyankatuteja could you review the suggestions and post an update when its ready for review?

**Comment by priyankatuteja** [comment]
@Yongyao Thanks for the review, I will incorporate these suggestions

**Comment by priyankatuteja** [comment]
@Yongyao I have included the suggested changes. Please. Please find the ppt attached here.
[safe_street_to_schools.pptx](https://github.com/Esri/arcgis-python-api/files/3723028/safe_street_to_schools.pptx)

**Comment by AtmaMani** [comment]
@priyankatuteja looks good, I asked for a couple of minor changes.

**Comment by AtmaMani** [comment]
thanks @priyankatuteja and @Yongyao

**Pull request merged**
