### PR TITLE
Migration guide updates next

### PR DESCRIPTION
**Pull request by achapkowski**
updated guide 6 for network analysis

### CODE REVIEW

**Review by nanaeaubry — APPROVED** [review]

**Review by jyaistMap — APPROVED** [review]
@achapkowski @nanaeaubry 
* the guide looks good - but the map display for map1 in the first example looks different from the original in that it looks like point symbols are not displaying. Can you check that out?

**Comment by nanaeaubry** [comment]
@jyaistMap I can see the points on map 1:

image


This is with latest build

**Comment by jyaistMap** [comment]
@nanaeaubry @achapkowski 

> @jyaistMap I can see the points on map 1:
> 
> image
> 
> This is with latest build

The map on production and in the original notebook looks like this:
image

Has the data changed so that all those surrounding points are no longer in the data?

**Comment by nanaeaubry** [comment]
@jyaistMap AH! It seems the picture marker symbol might not exists anymore. Will change that!

**Comment by nanaeaubry** [comment]
@jyaistMap The picture marker doesn't seem to exist anymore, I changed to simple marker symbol and updated the screenshot. Doesn't look as nice but we can look into finding another picture marker in another update

**Comment by jyaistMap** [comment]
Thanks @nanae! Looks good locally and in nbreview

**Pull request merged**
