### PR TITLE
Landsat8_to_Sentinel2 nb

### PR DESCRIPTION
**Pull request by guneetmutreja**
Notebook to showcase Landsat 8 to Sentinel-2 using Pix2Pix.

### CODE REVIEW

**Review by BP-Ent — CHANGES_REQUESTED** [review]
Suggested changes made on reviewnb

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1147/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1147/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1147/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1147/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1147/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1147/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1147/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1147/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1147/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1147/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1147/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1147/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1147/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1147/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1147/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1147/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1147/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1147/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1147/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
@BP-Ent Thank you for reviewing the notebook, I have made all the changes you suggested.

**Comment by priyankatuteja** [comment]
@anushriyaj  Could you please run this notebook locally and approve pr if all cells work fine

**Comment by anushriyaj** [comment]
The Notebook works fine.

**Review by anushriyaj — APPROVED** [review]

**Comment by guneetmutreja** [comment]
@priyankatuteja Added the sample data as suggested.

**Review by priyankatuteja — APPROVED** [review]

**Pull request merged**
