### PR TITLE
Scanned map digitization

### PR DESCRIPTION
**Pull request by SurajBaloni**
Sample guide for Scanned map digitization.

### CODE REVIEW

**Comment by SurajBaloni** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/Esri/arcgis-python-api/pull/774/discussion/) on ReviewNB
> 
> _atishay14 commented on 2020-09-21T18:58:43Z_
> ----------------------------------------------------------------
> 
> Why image is named as species name? can say scanned map

In case of multiple images scanned map will get repeated. So I thought to use the specie name

**Comment by AtmaMani** [comment]
@BP-Ent could you review this PR?

**Review by atishay14 — APPROVED** [review]
Approving the changes.

**Review by priyankatuteja — CHANGES_REQUESTED** [review]
@SurajBaloni I have suggested minor changes, in addition to those also change the notebook name to lowercase. Thanks for the wonderful guide!

**Comment by SurajBaloni** [comment]
@BP-Ent, @priyankatuteja  thanks for the suggestions.

**Review by AtmaMani — APPROVED** [review]

**Comment by AtmaMani** [comment]
@SurajBaloni thank you for this guide! @atishay14 @BP-Ent @priyankatuteja thank you for pretty detailed reviews!

**Pull request merged**
