### PR TITLE
Guide for deep learning (object detection)

### PR DESCRIPTION
**Pull request by Yongyao**
It now consists of 3 notebooks.

1. Geospatial-deep-learning: a high-level intro for geospatial deep learning and the module itself
2. Object-detection: the end-to-end workflow without getting into too much detail about SSD
3. How ssd works: an in-depth explanation about SSD and where it's coming from

### CODE REVIEW

**Comment by AtmaMani** [comment]
@Yongyao the updated DL guide greatly improves the initial draft. I found a few typos, can you please address them

**Comment by Yongyao** [comment]
@AtmaMani Typo corrected.

**Comment by AtmaMani** [comment]
I missed this in the initial review. Can you store the images in https://github.com/Esri/arcgis-python-api/tree/master/static/img folder and not under the deep learning folder?

**Comment by Yongyao** [comment]
@AtmaMani Done

**Comment by AtmaMani** [comment]
@Yongyao I see a `img-backup` folder, can you remove it

**Pull request merged**
