### PR TITLE
 spatial and temporal distribution of service calls using big data tools

### PR DESCRIPTION
**Pull request by priyankatuteja**
\<insert pull request description here\>

-----

# Checklist

Please go through each entry in the below checklist and mark an 'X' if that condition has been met. Every entry should be marked with an 'X' to be get the Pull Request approved.

- [x] All `import`s are in the first cell? First block of imports are standard libraries, second block are 3rd party libraries, third block are all `arcgis` imports?
- [x] All `GIS` object instantiations are one of the following?
    - `gis = GIS('https://www.arcgis.com', 'arcgis_python', 'P@ssword123')`
    - `gis = GIS(profile="your_online_profile")`
    - `gis = GIS('https://pythonapi.playground.esri.com/portal', 'arcgis_python', 'amazing_arcgis_123')`
    - `gis = GIS(profile="your_enterprise_portal")`
- [x] If this notebook requires setup or teardown, did you add the appropriate code to `./misc/setup.py` and/or `./misc/teardown.py`?
- [] If this notebook references any portal items that need to be staged on AGOL/Python API playground, did you coordinate with a Python API team member to stage the item the correct way with the api\_data\_owner user?
- [x] Code refactored & split out across multiple cells, useful comments?
- [x] Consistent voice/tense/narrative style? Thoroughly checked for typos?
- [x] All images used like `` instead of ``? All map widgets contain a static image preview? (Call `mapview_inst.take_screenshot()` to do so)
- [x] All file paths are constructed in an OS-agnostic fashion with `os.path.join()`? (Instead of `r"\foo\bar"`, `os.path.join(os.path.sep, "foo", "bar")`, etc.)
- [] **IF YOU WANT THIS SAMPLE TO BE DISPLAYED ON THE DEVELOPERS.ARCGIS.COM WEBSITE**, ping @ DavidJVitale so he can add it to the list for the next deploy

### CODE REVIEW

**Comment by AtmaMani** [comment]
@priyankatuteja are you waiting to get BDFS configured on PythonAPI playground portal for this PR?

**Comment by priyankatuteja** [comment]
> @priyankatuteja are you waiting to get BDFS configured on PythonAPI playground portal for this PR?

@AtmaMani I am waiting to get the sample reviewed and for that, I assume you need data to test the notebook. Please let me know where to add BDFS for this sample so this could be reviewed and approved accordingly

**Comment by priyankatuteja** [comment]
> @priyankatuteja are you waiting to get BDFS configured on PythonAPI playground portal for this PR?

@AtmaMani I am waiting to get the sample reviewed and for that, I assume you need data to test the notebook. Please let me know where to add BDFS for this sample so this could be reviewed and approved accordingly

**Comment by AtmaMani** [comment]
@priyankatuteja yes please follow up on the email thread you started to get the data published and update the connection strings accordingly. Meanwhile I will review the content

**Comment by AtmaMani** [comment]
@jyaistMap could you do the first round of reviews for this PR?

**Comment by jyaistMap** [comment]
Hi @priyankatuteja I'm reviewing the sample, but do not have access to `\\DELDEVAL031\datastore`. Are you able to access `\\JYAIST2\samplereview`? Can you place the data there?

**Comment by jyaistMap** [comment]
@AtmaMani @priyankatuteja 
I set up a big data file share on the pythonapi playground using data I retrieved after searching for `new orleans service calls` - see the link to the search results [here](https://catalog.data.gov/dataset?q=new+orleans+service+calls&sort=score+desc%2C+name+asc&as_sfid=AAAAAAVK63d5vaLpeqOHo5T2oOEf6-oPnbls8dfFHHeGqvKAdYeUvhLGRSmYYroidrhMPr31FqdulXb16-3u5CizHLXaG5R77OlZLXi2kHgpEcnRDYXiwAtW9pt5tpH-WLF84us%3D&as_fid=ace4d3f9ae192b7437b0f4142d9db0d3c607a259).  I tested the notebook against that big data files share item, and am making some additional notes.

**Comment by priyankatuteja** [comment]
@jyaistMap Thanks for the suggestions. I was occupied with python api testing and documentation. Apologies for the delayed response. I will be incorporating these suggestions soon. Also placing the data on \\JYAIST2\sample_review for further testing of the sample.

**Comment by priyankatuteja** [comment]
@jyaistMap I do not have access to \JYAIST2\sample_review. But, I have added you and Atma to have access to \\DELDEVAL031\datastore. Please let me know if that still does not work.

**Comment by priyankatuteja** [comment]
@AtmaMani, @jyaistMap  I have made changes to the notebook. Please let me know if any other changes required.

**Comment by AtmaMani** [comment]
@priyankatuteja the latest revision looks much better. This is a really good sample. I think we can borrow from this when we rewrite the geoanalytics module guide. I have asked a question about one of the aggregation methods, could you take a look at that?

**Comment by priyankatuteja** [comment]
@AtmaMani Thanks for the review! I have made the changes you suggested.

**Comment by AtmaMani** [comment]
@priyankatuteja thanks for the sample, @jyaistMap thanks for the thorough review

**Pull request merged**
