### PR TITLE
Salary automl fairness

### PR DESCRIPTION
**Pull request by moonlanderr**
\<insert pull request description here\>

-----

# Checklist

Please go through each entry in the below checklist and mark an 'X' if that condition has been met. Every entry should be marked with an 'X' to be get the Pull Request approved.

- [ ] All `import`s are in the first cell? 
    - [ ] First block of imports are standard libraries
    - [ ] Second block are 3rd party libraries
    - [ ] Third block are all `arcgis` imports? Note that in some cases, for samples, it is a good idea to keep the imports next to where they are used, particularly for uncommonly used features that we want to highlight.
- [ ] All `GIS` object instantiations are one of the following?
    - `gis = GIS()`
    - `gis = GIS('home')` or `gis = GIS('pro')`
    - `gis = GIS(profile="your_online_portal")`
    - `gis = GIS(profile="your_enterprise_portal")`
- [ ] If this notebook requires setup or teardown, did you add the appropriate code to `./misc/setup.py` and/or `./misc/teardown.py`?
- [ ] If this notebook references any portal items that need to be staged on AGOL/Python API playground, did you coordinate with a Python API team member to stage the item the correct way with the `api_data_owner` user?
- [ ] If the notebook requires working with local data (such as CSV, FGDB, SHP, Raster files), upload the files as items to the [Geosaurus Online Org](geosaurus.maps.arcgis.com/) using `api_data_owner` account and change the notebook to first download and unpack the files.
- [ ] Code simplified & split out across multiple cells, useful comments?
- [ ] Consistent voice/tense/narrative style? Thoroughly checked for typos?
- [ ] All images used like `` instead of ``? All map widgets contain a static image preview? (Call `mapview_inst.take_screenshot()` to do so)
- [ ] All file paths are constructed in an OS-agnostic fashion with `os.path.join()`? (Instead of `r"\foo\bar"`, `os.path.join(os.path.sep, "foo", "bar")`, etc.)
- [ ] Is your code formatted using [Jupyter Black](https://www.freecodecamp.org/news/auto-format-your-python-code-with-black/)? You can use Jupyter Black to format your code in the  notebook.
- [ ] **If this notebook showcases deep learning capabilities, please go through the following checklist:**
    - [ ] Are the inputs required for `Export Training Data Using Deep Learning` tool published on geosaurus org (api data owner account) and added in the notebook using `gis.content.get` function?
    - [ ] Is training data zipped and published as Image Collection? Note: Whole folder is zipped with name same as the notebook name.
    - [ ] Are the inputs required for model inferencing published on geosaurus org (api data owner account) and added in the notebook using `gis.content.get` function? Note: This includes providing test raster and trained model.
    - [ ] Are the inferenced results displayed using a webmap widget?
- [ ] **IF YOU WANT THIS SAMPLE TO BE DISPLAYED ON THE DEVELOPERS.ARCGIS.COM WEBSITE**, ping @jyaistMap so he can add it to the list for the next deploy.

### CODE REVIEW

**Comment by moonlanderr** [comment]
<p>corrected.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387418'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>removed unwanted</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387397'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>Now I have shown this by just breaking up the male vs female counts , with showing male bias</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387444'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>replaced vanilla</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387509'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added descriptions</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387473'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added the how automl and fairness works, where users can check the detail</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387569'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added brief explanation</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387585'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added explanation</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387585'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added brief explanation on sensitive variable</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387607'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>so here I thought to mention the grid searching by automl, do you mean something else by strategy? I am not sure what is internally happening. Could you add this section here, referring to the startegy it is using, </p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387632'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>I explained that here  "The model report shows that <code>2_Default_LightGBM_SampleWeigthing_Update_2</code> is the best trained model and the respective demograpihc_parity_ratio is now 0.84 which is up from 0.29, which is also higher than the minimum threshold of 0.80."</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387656'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>It is showing the table properly in firefox, is it due to browser?  I think it will be in the table format when it gets published, otherwise will add as image</p><p> </p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387676'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>same as above, showing ok in my machine, </p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387700'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387722'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387751'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387776'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387796'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>same, as I think it would get fixed once published</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387823'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>will get fixed in publishing as with earlier notebooks</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387858'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>removed part of drawback, the rest is ok, slightly hinting that new biases have crept in but can be worked on further.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387886'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>I think that this will depend on the user data, and the automl fairness guide is there to help for that. Since this is now getting a bit heavy with technical detail and concepts.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387922'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
@KarthikDutt , added the suggestions, pls check

**Comment by KarthikDutt** [comment]
<p>The dataset consists of 32,561 records, with 21,790 males and 10,771 females, suggesting a bias favoring males. THis statement is incorrect. The dataset is biased because males are more likely to be classified as earning more than 50k compared to women and not because there is less representation of women in the dataset.  </p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387418'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by KarthikDutt** [comment]
<p>Please refer to previous comment. </p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387444'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by KarthikDutt** [comment]
<p>Internally we are using an approach called Reweighing. </p><p>Reweighing is a preprocessing technique that Weights the examples in each (group, label) combination differently to ensure fairness before classification&nbsp;</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387632'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by KarthikDutt** [comment]
<p>I am using chrome. </p><p>I feel it is better to use images. In case you are sure that it will be fine after publishing, then you can ignore this.  </p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387676'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by BP-Ent — CHANGES_REQUESTED** [review]
Suggested changes made on reviewNB

**Comment by moonlanderr** [comment]
<p>added a basic analysis of male vs female higher salary stats that indicate bias</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387444'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2332688694'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2332688708'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2332688716'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2332688726'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2332688744'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2332688754'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2332688772'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2332688783'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2332688798'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2332688814'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387632'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2332688838'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>yes, it will be formatted further by the publishing team, will give it the proper display</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2149387676'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2332688861'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2332688876'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1836/discussion/#comment-2332688920'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by moonlanderr** [comment]
@BP-Ent , all suggestions added pls check

**Comment by moonlanderr** [comment]
@KarthikDutt , I have corrected the bias indication paragraph, pls check,

**Review by KarthikDutt — APPROVED** [review]

**Review by priyankatuteja — APPROVED** [review]

**Pull request merged**
