### PR TITLE
Updated output formats for notebooks missing output on production site

### PR DESCRIPTION
**Pull request by jyaistMap**
* Update map widget cells output from current format to use embedded base64 images to prevent cells from missing output on production:
   * [Using imagery layers](https://developers.arcgis.com/python/guide/using-imagery-layers/)
   * [Using raster analysis](https://developers.arcgis.com/python/guide/using-raster-analysis/)
   * [Advanced raster concepts](https://developers.arcgis.com/python/guide/raster-analysis-advanced-concepts/)
* Updated format for cells ouputting gifs from using IPython.display to use markdown format for new plugin
  * [Guide to Orthomapping Part 2](https://developers.arcgis.com/python/guide/orthomapping-guide-2/#323-use-dem-to-visualize-scenes)

### CODE REVIEW

**Comment by jyaistMap** [comment]
<p>Ran a cell to get output from  <em>color_infrared.url:</em></p><pre class="ql-syntax" spellcheck="false">https://landsat2.arcgis.com/arcgis/rest/services/Landsat/MS/ImageServer
</pre><p> </p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1366/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jyaistMap** [comment]
<p>Removed the extra text. Thanks, @rhea-j!</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1366/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by rhea-j — APPROVED** [review]
Looks good. Thanks @jyaistMap !

**Comment by jyaistMap** [comment]
|Before|After|
|---|---|
image|image

**Pull request merged**
