### PR TITLE
extracting_sinholes_from_aerial_imagery

### PR DESCRIPTION
**Pull request by shivanip32**
\<insert pull request description here\>

-----

# Checklist

Please go through each entry in the below checklist and mark an 'X' if that condition has been met. Every entry should be marked with an 'X' to be get the Pull Request approved.

- [ ] All `import`s are in the first cell? First block of imports are standard libraries, second block are 3rd party libraries, third block are all `arcgis` imports?
- [ ] All `GIS` object instantiations are one of the following?
    - `gis = GIS('https://www.arcgis.com', 'arcgis_python', 'P@ssword123')`
    - `gis = GIS(profile="your_online_profile")`
    - `gis = GIS('https://pythonapi.playground.esri.com/portal', 'arcgis_python', 'amazing_arcgis_123')`
    - `gis = GIS(profile="your_enterprise_portal")`
- [ ] If this notebook requires setup or teardown, did you add the appropriate code to `./misc/setup.py` and/or `./misc/teardown.py`?
- [ ] If this notebook references any portal items that need to be staged on AGOL/Python API playground, did you coordinate with a Python API team member to stage the item the correct way with the api\_data\_owner user?
- [ ] Code refactored & split out across multiple cells, useful comments?
- [ ] Consistent voice/tense/narrative style? Thoroughly checked for typos?
- [ ] All images used like `` instead of ``? All map widgets contain a static image preview? (Call `mapview_inst.take_screenshot()` to do so)
- [ ] All file paths are constructed in an OS-agnostic fashion with `os.path.join()`? (Instead of `r"\foo\bar"`, `os.path.join(os.path.sep, "foo", "bar")`, etc.)
- [ ] **IF YOU WANT THIS SAMPLE TO BE DISPLAYED ON THE DEVELOPERS.ARCGIS.COM WEBSITE**, ping @ DavidJVitale so he can add it to the list for the next deploy

### CODE REVIEW

**Comment by priyankatuteja** [comment]
https://github.com/ArcGIS/geosaurus/issues/2924

**Comment by CMPeng** [comment]
<p>Nice work @shivanip32 - This is a good notebook demonstrating use of MaskRCNN, and quite informational. I have placed my comments as above. Thanks!</p>

**Comment by priyankatuteja** [comment]
As discussed this notebook's PR is made at https://github.com/ArcGIS/arcgis-ai-planning/pull/69. @AtmaMani This is only for demo purpose now. You may close this PR.

**Comment by priyankatuteja** [comment]
> Nice work @shivanip32 - This is a good notebook demonstrating use of MaskRCNN, and quite informational. I have placed my comments as above. Thanks!

@CMPeng Thanbks for you time and efforts. @shivanip32 You can still incorporate these changes for making a better demo notebook.

**Comment by AtmaMani** [comment]
This is in interesting sample, perhaps can be added later after it addresses the suggestions mentioned earlier. Closing this per @priyankatuteja

**Pull request closed without merging**
