### PR TITLE
changed to using profile and fixed a few other issues

### PR DESCRIPTION
**Pull request by Yongyao**

### CODE REVIEW

**Comment by AtmaMani** [comment]
For ArcGIS/Geosaurus#1805

**Comment by Yongyao** [comment]
@AtmaMani Changed to online profile. The reason I am only list top 3 items is because the results have more than 10 items and I don't want to list all of them. Is checking the length necessary?

**Comment by AtmaMani** [comment]
@Yongyao listing 3 is ok, but we need to cover the scenario when the search return has less than your index. Since we are searching `outside_org`, hypothetically, this search can return less than 3 items. I like defensive programming.

**Comment by Yongyao** [comment]
@AtmaMani I see your concern now, but items[:3] won't throw out of boundary error even if there are less than 3 items, it will just list whatever it has. This has been tested.

**Comment by AtmaMani** [comment]
Good point, thanks @Yongyao

**Pull request merged**
