### PR TITLE
Fixing 6858 - modified datetime import

### PR DESCRIPTION
**Pull request by akhilnegi**
Fixes - https://github.com/ArcGIS/geosaurus/issues/6858

Fixes datetime import error.

### CODE REVIEW

**Review by sumanttyagi — COMMENTED** [review]
- [ ] 1. gis = GIS('home') is giving the below error . 

`"ImportError: Could not import arcpy` 
While running ,  gis = GIS ( username='#######' , password = "********") seems fine. Documentation says "URL is Optional string. If URL is None, then the URL will be ArcGIS Online 

- [ ]  2.  similar change (datetime.datetime.now().microsecond)) in below line :
       `crime_hotspots_madison = find_hot_spots(madison_crime_layer, 
                                        context={"extent":
                                                 {"xmin":-10091700.007046243,"ymin":5225939.095608932,
                                                  "xmax":-9731528.729766665,"ymax":5422840.88047145,
                                                  "spatialReference":{"wkid":102100,"latestWkid":3857}}},
                                        output_name="crime_hotspots_madison" + str(**datetime.datetime.now().microsecond)**)`

Apart from it i would like to suggest to put a Note mentioning for waiting the map to be loaded before running add layer cell.

**Comment by akhilnegi** [comment]
hi @sumanttyagi,

 1. gis = GIS('home') is giving the below error. - This is not how we actually create GIS objects, the actual usage is as follows:
     Decleration:
     > gis = GIS(username=<username>,  password=<password>, profile='home')
     Subsequent usage:
     > gis = GIS(profile='home')
Before publishing publically, we remove the credentials.
2. similar change (datetime.datetime.now().microsecond)) in below line - DONE
3. Apart from it i would like to suggest to put a Note mentioning for waiting the map to be loaded before running add layer cell. - Is there a specific reason to do this?

**Comment by akhilnegi** [comment]
@sumanttyagi  correction to my previous comment, gis = GIS('home') will error on the local system but should work on Notebook server by connecting to the home GIS.

**Comment by sumanttyagi** [comment]
> 3\. Apart from it i would like to suggest to put a Note mentioning for waiting the map to be loaded before running add layer cell. - Is there a specific reason to do this?

Sometime, if we run the add layer cell before loading of the basemap , it is not able to overlay the features map on basemap.

**Review by sumanttyagi — APPROVED** [review]

**Review by priyankatuteja — APPROVED** [review]

**Review by AtmaMani — APPROVED** [review]

**Pull request merged**
