### PR TITLE
Coastline classification NB

### PR DESCRIPTION
**Pull request by guneetmutreja**
This Notebook shows how to classify coastlines using feature classifier model.

-----

# Checklist

Please go through each entry in the below checklist and mark an 'X' if that condition has been met. Every entry should be marked with an 'X' to be get the Pull Request approved.

- [ ] All `import`s are in the first cell? First block of imports are standard libraries, second block are 3rd party libraries, third block are all `arcgis` imports? Note that in some cases, for samples, it is a good idea to keep the imports next to where they are used, particularly for uncommonly used features that we want to highlight.
- [ ] All `GIS` object instantiations are one of the following?
    - `gis = GIS()`
    - `gis = GIS('home')`
    - `gis = GIS(profile="your_online_portal")`
    - `gis = GIS('https://pythonapi.playground.esri.com/portal')`
    - `gis = GIS(profile="your_enterprise_portal")`
- [ ] If this notebook requires setup or teardown, did you add the appropriate code to `./misc/setup.py` and/or `./misc/teardown.py`?
- [ ] If this notebook references any portal items that need to be staged on AGOL/Python API playground, did you coordinate with a Python API team member to stage the item the correct way with the api\_data\_owner user?
- [ ] Code refactored & split out across multiple cells, useful comments?
- [ ] Consistent voice/tense/narrative style? Thoroughly checked for typos?
- [ ] All images used like `` instead of ``? All map widgets contain a static image preview? (Call `mapview_inst.take_screenshot()` to do so)
- [ ] All file paths are constructed in an OS-agnostic fashion with `os.path.join()`? (Instead of `r"\foo\bar"`, `os.path.join(os.path.sep, "foo", "bar")`, etc.)
- [ ] **IF YOU WANT THIS SAMPLE TO BE DISPLAYED ON THE DEVELOPERS.ARCGIS.COM WEBSITE**, ping @ DavidJVitale so he can add it to the list for the next deploy

### CODE REVIEW

**Comment by priyankatuteja** [comment]
@guneetmutreja Well written!!! @shivanip32 Please upload this notebook on geosaurus org and test it for try it live

**Comment by priyankatuteja** [comment]
@guneetmutreja Some changes to be made:

- [ ] provide a subset of data if you would like to have this sample available as try it live,
- [ ] Sentinel 2 views is not supported in Pro 2.8 for either export or inferencing.
image

Can you provide a local raster and corresponding labels for users and change the screenshots accordingly.

**Comment by priyankatuteja** [comment]
@BP-Ent  Could you please help in review?

**Review by BP-Ent — CHANGES_REQUESTED** [review]
Suggested changes made on ReviewNB

**Comment by guneetmutreja** [comment]
@BP-Ent Thanks for the review, I have amended the changes you suggested, please have a look at them.

**Comment by BP-Ent** [comment]
@guneetmutreja Looks good!

**Review by priyankatuteja — APPROVED** [review]
pls change the screenshot as discussed offline. We won't make it try it live given large amt. of data and imagery limitation

**Review by rohitgeo — APPROVED** [review]
Nice!

**Pull request merged**
