### PR TITLE
Updated Analyzing NYC taxi data sample notebook to use pythonapi playground

### PR DESCRIPTION
**Pull request by jyaistMap**
* uploaded source data to server and added the big data file share
* added some additional text explaining spatial reference and messaging
* updated image PR requests for the results forthcoming

### CODE REVIEW

**Comment by AtmaMani** [comment]
@jyaistMap should this be a PR to `dev_current` branch instead?

**Comment by DavidJVitale** [comment]
@AtmaMani since this is a sample notebook, we aren't using the CI/CD process. We are manually converting to HTML due to the previously discussed issue with static map images in the developer's website (but no images for the notebooks).

**Comment by AtmaMani** [comment]
@DavidJVitale makes sense, thanks.

**Comment by jyaistMap** [comment]
@AtmaMani - as @DavidJVitale explained, for sample notebooks we're following the former workflow rather than the CI/CD workflow because of the issue with static map images.

**Pull request merged**
