### PR TITLE
Dev site current (replace 3 NA guide notebooks with 7 new nb)

### PR DESCRIPTION
**Pull request by CMPeng**
tL;Dr

ref: https://github.com/ArcGIS/geosaurus/issues/2850

### CODE REVIEW

**Comment by AtmaMani** [comment]
@DavidJVitale going forward, are we using the `python.yml` file here to reflect updates on public website?

**Comment by DavidJVitale** [comment]
@AtmaMani We aren't using that `python.yaml` file tracked in this repository, that old system proved too complicated and not useful. We should remove that file in this repo to avoid confusion -- sorry about that.

When there are large changes needed to be made to the developers website layout, we should make a PR on the `arcgis-for-developers` repo directly.

**Comment by DavidJVitale** [comment]
@CMPeng has done just that with this PR at the developers website:

https://github.com/ArcGIS/arcgis-for-developers/pull/9067

So we should review the changes to the `python.yaml` file there

**Comment by CMPeng** [comment]
@DavidJVitale 
Shall I remove the python.yml file to be checked in here? Or resolve the conflicts?
cc @AtmaMani

**Comment by AtmaMani** [comment]
@CMPeng following @DavidJVitale's comment, could you delete the yaml file and update this PR? That will avoid this confusion going forward

**Comment by DavidJVitale** [comment]
@CMPeng @AtmaMani It would be great if you could remove that file! Much appreciated :)

**Comment by CMPeng** [comment]
thanks @AtmaMani and @DavidJVitale 
Yaml file removed from the commit.

**Comment by CMPeng** [comment]
@AtmaMani title changed for Part 7 - also done here.

**Pull request merged**
