### PR TITLE
fix deep learning guides

### PR DESCRIPTION
**Pull request by nanaeaubry**
I did not have to re-render anything. These were simple changes that were made to fit the new methods such as using folder.add rather than contentManager.add

### CODE REVIEW

**Review by nparavicini7 — APPROVED** [review]
lgtm, edited text

**Review by nparavicini7 — CHANGES_REQUESTED** [review]
folder.add() future stuff again sorry didn't mean to approve lol

**Review by jyaistMap — APPROVED** [review]
* submitted and merged #2017 to correct setting a _basemap_

**Comment by jyaistMap** [comment]
* folder.add syntax looks correct

**Pull request merged**
