### PR TITLE
tflite sample added

### PR DESCRIPTION
**Pull request by guneetmutreja**
This PR contains a sample that showcases TfLite support.

### CODE REVIEW

**Comment by guneetmutreja** [comment]
@priyankatuteja Can you please do a review for this sample.

**Comment by priyankatuteja** [comment]
@guneetmutreja I missed out on some points earlier when I didn't run the sample locally. There are a few more:

1. I downloaded the EOL data and ran the sample, it seems that the data link you pointed has classes with class codes and not class names. So data.show_batch isn't showing the same classes.

image

2. The path of the training data should contain a folder with name "images" which otherwise would give an error that it could not find images folder.  So users will need to unzip tar and rename/name their folder name to **images**.

3. I got this kind of warning message, not sure if this should be considered a point to notice.

image

**Comment by priyankatuteja** [comment]
@guneetmutreja I missed out on some points earlier when I didn't run the sample locally. There are a few more:

1. I downloaded the EOL data and ran the sample, it seems that the data link you pointed has classes with class codes and not class names. So data.show_batch isn't showing the same classes.

image

2. The path of the training data should contain a folder with name "images" which otherwise would give an error that it could not find images folder.  So users will need to unzip tar and rename/name their folder name to **images**.

3. I got this kind of warning message, not sure if this should be considered a point to notice.

image

**Comment by guneetmutreja** [comment]
<p>As per the discussion, we have to add these lines itself as the integration of this model with Survey123 app is in beta phase.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/694/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
@priyankatuteja Thank you for the review, I have made all the changes you suggested. Request your review.

**Comment by guneetmutreja** [comment]
<p>@AtmaMani, the work that is integrated with the Survey123 app  is still in beta phase and the hyperlink to that is not available. We can surely update the sample once the link is available. </p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/694/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>@AtmaMani, Thank you. I have made the changes from pt. 1-4. </p><p>The link provided contains a zipped folder containing a script as well as a json file. As the script and json file are not directly related to the API and does not contain any functionality belonging to ArcGIS API for Python, I believe putting it up on the repo may create some confusions among our users. So, we should avoid doing that. What is your thought on this?</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/694/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
@AtmaMani Thank you for the review. I have incorporated the changes you suggested.

**Comment by AtmaMani** [comment]
<p>@guneetmutreja, It is ok to checkin, unless the file is very big. For instance entity recognizer has files in https://github.com/Esri/arcgis-python-api/tree/master/samples/04_gis_analysts_data_scientists/data/EntityRecognizer</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/694/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AtmaMani** [comment]
@guneetmutreja thanks for the sample. @priyankatuteja thanks for the detailed review.
@guneetmutreja I think it is ok to check-in the supporting files. For instance entity recognizer has files in https://github.com/Esri/arcgis-python-api/tree/master/samples/04_gis_analysts_data_scientists/data/EntityRecognizer. You can create a folder and check in there.

**Pull request merged**
