### PR TITLE
Ga samples updated

### PR DESCRIPTION
**Pull request by priyankatuteja**
- [x] taxi sample
- [x] hurricanes reconstruct tracks
- [x] crime clustering
- [x] service calls
- [ ] air quality

### CODE REVIEW

**Review by AtmaMani — APPROVED** [review]

**Comment by AtmaMani** [comment]
@priyankatuteja can you resolve the merge conflict

**Review by shivanip32 — APPROVED** [review]
all tools tested except run_python_script, discussed with @priyankatuteja.

**Comment by priyankatuteja** [comment]
@shivanip32 issue with run python script is fixed. Please test and update!

**Comment by mohi9282** [comment]
@shivanip32 @priyankatuteja could you please provide an update on this issue?

**Pull request merged**
