### PR TITLE
UC nbs - Yongyao

### PR DESCRIPTION
**Pull request by Yongyao**

### CODE REVIEW

**Comment by CMPeng** [comment]
@Yongyao  quick question, shall we expect to see the local data used int he sample notebook in the PR as well? e.g.
`data = "./data/sample_data.gdb/Zoning"`
Seems to be missing here.

**Comment by Yongyao** [comment]
@CMPeng , not sure if we need to attach data for this nbs. @AtmaMani Shall we? The total amount of data is larger than 100M in this case.

**Comment by AtmaMani** [comment]
@CMPeng @Yongyao lets hold off merging this PR. I have concerns about checking in large files like this, hence made #473 
Additionally, we could open a public-facing, read-only folder on box/onedrive and host datasets there instead of in the repo

**Comment by DavidJVitale** [comment]
@Yongyao can you change this PR to merge into the `conferences_talks` branch instead of `master`? I think this should be a good thing. @AtmaMani @CMPeng thoughts?

**Comment by AtmaMani** [comment]
@Yongyao yes please change PR so it merges to `conference_talks`

**Pull request closed without merging**
