### PR TITLE
map and chart corona viruses

### PR DESCRIPTION
**Pull request by CMPeng**
This PR contains 2 notebooks, not sure if needed to combine them (both are a bit long in paragraphs).
1. Map the corona virus outbreak
2. chart the time-series of corona virus development

### CODE REVIEW

**Comment by AtmaMani** [comment]
@priyankatuteja could you do the first round of reviews for these notebooks?
@CMPeng I think the time series analysis notebook can go in the data-scientist section instead of content-publisher section.

**Comment by CMPeng** [comment]
@priyankatuteja thank you so much for the valuable comments. I have addressed in the new commits accordingly. Can you please check if those look OK? Many thanks :)

**Comment by priyankatuteja** [comment]
<p>@CMPeng Thanks for making changes. I have suggested some more changes, if you could try geocoding the cases and display it on map widget. </p>

**Comment by CMPeng** [comment]
@priyankatuteja the mapping part is in the second notebook; I have split time-series charting and the outbreak mapping into two notebooks. Can you please check out the 2nd notebook on this PR? thanks!

**Comment by priyankatuteja** [comment]
@CMPeng Thanks for the follow-up! I have added the review for 2nd sample also.

**Comment by AtmaMani** [comment]
@CMPeng I have marked this PR with 'do not merge'. Once you push the changes, please remove it so I can review it

**Comment by CMPeng** [comment]
<p>Thank you so much @<a href="https://github.com/priyankatuteja" target="_blank">priyankatuteja</a> for all the helpful reviews and suggestions. I have addressed them in the new PR <a href="https://github.com/Esri/arcgis-python-api/pull/685" target="_blank">https://github.com/Esri/arcgis-python-api/pull/685</a> (because I was having difficulties merging the latest changes to this PR). </p><p>CC @<a href="https://github.com/AtmaMani" target="_blank">AtmaMani</a></p><p> </p><p>Closing this PR, and moving onto the new one.</p>

**Pull request closed without merging**
