### PR TITLE
add guide for appending features

### PR DESCRIPTION
**Pull request by jyaistMap**
@AtmaMani Please review and let me know what may need reworked. 
@CMPeng Thought you could take a look through the scenarios I posed and let me know your thoughts.

-----

# Checklist

Please go through each entry in the below checklist and mark an 'X' if that condition has been met. Every entry should be marked with an 'X' to be get the Pull Request approved.

- [ ] All `import`s are in the first cell? First block of imports are standard libraries, second block are 3rd party libraries, third block are all `arcgis` imports?
- [ ] All `GIS` object instantiations are one of the following?
    - `gis = GIS('https://www.arcgis.com', 'arcgis_python', 'P@ssword123')`
    - `gis = GIS(profile="your_online_profile")`
    - `gis = GIS('https://pythonapi.playground.esri.com/portal', 'arcgis_python', 'amazing_arcgis_123')`
    - `gis = GIS(profile="your_enterprise_portal")`
- [ ] If this notebook requires setup or teardown, did you add the appropriate code to `./misc/setup.py` and/or `./misc/teardown.py`?
- [ ] If this notebook references any portal items that need to be staged on AGOL/Python API playground, did you coordinate with a Python API team member to stage the item the correct way with the api\_data\_owner user?
- [ ] Code refactored & split out across multiple cells, useful comments?
- [ ] Consistent voice/tense/narrative style? Thoroughly checked for typos?
- [ ] All images used like `` instead of ``? All map widgets contain a static image preview? (Call `mapview_inst.take_screenshot()` to do so)
- [ ] All file paths are constructed in an OS-agnostic fashion with `os.path.join()`? (Instead of `r"\foo\bar"`, `os.path.join(os.path.sep, "foo", "bar")`, etc.)

### CODE REVIEW

**Comment by CMPeng** [comment]
@jyaistMap Thanks for inviting me to look at this work. It is so neatly written, totally educating for me :)
Quick questions :) - 
1. If I understand correctly, users will need to download the csv item from online, upload it to online again, then to proceed. why do we need to download the csv file? 
2. If the feature service is a complicated one, per say, made from two tabled "join" or "relate" to each other, does this process still work?

**Comment by jyaistMap** [comment]
Hi @CMPeng Glad you are reviewing it. Did the meeting this morning clear up why we have to download and publish items for each `arcgis_python` login to illustrate append?

**Comment by CMPeng** [comment]
Yes @jyaistMap I now understand :) thanks for the explanation.
and I have finished running the sample notebook on my machine - everything works out quite well, just with two places that I got stuck a little bit -
1. at the cell
```
downingtown_parcels_fgdb = [d 
                            for d in gis.content.search("*", max_items=50) 
                            if d.type == "File Geodatabase" 
                            and "Downingtown" in d.title][0]
downingtown_parcels_fgdb
```
I have to specify the max_items, or else the returned item is None (because the default 10 items being returned by search() might not have fgdb or "Downingtown" in the title at all)
2. at the cell
```
if not os.path.exists(os.path.join(cwd, "sierra_leone")):
    os.mkdir(os.path.join(cwd, "sierra_leone"))

# Assign a variable to the full path of the new directory
wd = [os.path.join(guide_dir, dir) 
    for dir in os.listdir(guide_dir) 
      if 'sierra_leone' in dir][0]
```
I saw an error with `guide_dir` not defined; also, when defining `guide_dir`, if it is not in the level structure of `guide_dir`>`cwd`>`sierra_leone`, I got wd as None...

**Comment by jyaistMap** [comment]
Thanks, @CMPeng Oops. The `cwd` and `guide_dir` variables were for testing. Should have removed those. I'll add `max_items` to that query, too.

**Comment by AtmaMani** [comment]
@jyaistMap could you checkout my edits and tell if its good to merge?

**Comment by jyaistMap** [comment]
Thanks @AtmaMani 
I merged the edits you suggested, and added some additional ones where I noticed some misspellings.

**Pull request merged**
