### PR TITLE
Pointcnn sample nb update, as per the latest changes till 1.9.0

### PR DESCRIPTION
**Pull request by vbhv14**
- [x] updated the whole workflow based on new enhancements and depreciation in the API and PointCNN workflow.
- [x] updated, public data as per new GP workflow.
- [x] improved grammar, formatting and added more info. about parameters.

### CODE REVIEW

**Comment by Hackeraagayaphirse** [comment]
Hey bro I want a help I am fresher would you help me

**Comment by priyankatuteja** [comment]
@sumanttyagi Could you please review this pr.

**Review by sumanttyagi — CHANGES_REQUESTED** [review]
- [x] (1)
 Above cell no. 2 can we update the Note or make similar changes as suggested below
Note: The data used in this sample notebook can be downloaded from here, in a zip file format. Or We can search for the item/content using the id '50390f56a0e740ac88c72ae1fb1eda7a''as shown in below cell click on hyperlink to download the data. After data is downloaded from either of the methods, It has both 'training data' and 'test data', where 'test data' is used for inferencing and generating 3D models.

- [ ] (2) 
Under the headline "Classification using the trained model" , can we mentioned a line about the change in symbology setup for visualization.

Apart from it there are few screenshots in dark mode. Kindly update if change is required

**Comment by vbhv14** [comment]
@sumanttyagi 
I have incorporated the suggested changes.
verify the changes for approval.
thanks.

**Review by sumanttyagi — APPROVED** [review]
looks good to me @priyankatuteja

**Review by AtmaMani — APPROVED** [review]

**Comment by AtmaMani** [comment]
@vbhv14 thanks for the update. @sumanttyagi thanks for the reviews

**Pull request merged**
