### PR TITLE
network analysis guide 2nd half, with data

### PR DESCRIPTION
**Pull request by CMPeng**
- Generate Origin Destination Cost Matrix (Part 5) - 2 modules
- Solve Location Allocation (Part 6) 
- Vehicle Routing Problem Service (Part 7)

(The table in the markdown cell looks a little weird but should be correct when opening from jupyter)

*The PR only contains guides from 5-7, and parts 1-4 in the prev PR https://github.com/Esri/arcgis-python-api/pull/528*

- Network Dataset and Network Analysis (Part 1) 
- Find Routes (Part 2) - 2 modules
- Generate Service Area (Part 3)
- Find Closest Facility (Part 4)

*Parts 8 and 9 are in internal archive on geosaurus*
https://github.com/ArcGIS/geosaurus/pull/2783

### CODE REVIEW

**Comment by AtmaMani** [comment]
For https://github.com/ArcGIS/geosaurus/issues/2416

**Comment by AtmaMani** [comment]
@CMPeng I reviewed part 5 of NA guide. It looks pretty good. I asked for a few changes.

**Comment by CMPeng** [comment]
Thanks @AtmaMani 
Please check the latest commit for the changes I have done to address your rev suggestions to Part 5. More over, (1) the explanations to the straight lines are added to Fig 2, and before the execution of solvers; (2) The first and the third illustrative maps are converted to gif, but the 2nd map is still a static image (since the output layer is added at once to the map view).

**Comment by AtmaMani** [comment]
<p>@CMPeng, I just reviewed notebook 6, it reads well. I asked for a few clarifications.</p>

**Comment by CMPeng** [comment]
Thanks @AtmaMani - your revision suggestions to Part6 are addressed. 
PLUS. I did not add the async process condition check as a while loop, because I think it will be more meaningful if user can use the wait time processing other cells (that are not relevant). Some texts have been added to explain the situation.

**Comment by AtmaMani** [comment]
@CMPeng I just reviewed part 7. It is well written with apt selection of examples. I asked for a few changes, including animating the map and splitting part 7 into notebooks

**Comment by CMPeng** [comment]
Thanks @AtmaMani 
Part_7 is also revised according to your comments. Please check the latest commit :)

**Comment by AtmaMani** [comment]
Thank you @CMPeng this is an excellent guide with a great set of visuals.

**Pull request merged**
