### PR TITLE
updated login passwords for samples, guides, etc..

### PR DESCRIPTION
**Pull request by achapkowski**
updated login passwords for samples, guides, etc..

### CODE REVIEW

**Review by jyaistMap — APPROVED** [review]
- issued PR against the issue_0001 branch for suggested changes
- local notebooks lgtm

**Review by mohi9282 — APPROVED** [review]
@achapkowski thanks for making these changes. Reviewed all files and changes look good to me.

**Comment by rohitgeo** [comment]
This will break Try It Live samples

**Comment by rohitgeo** [comment]
This will break Try It Live samples

**Pull request merged**
