### PR TITLE
Updates to notebooks so they are synced with Developer site Guide html pages

### PR DESCRIPTION
**Pull request by jyaistMap**
Notebooks on master branch need updated to sync with guide page corrections needed for developer site:
 * understanding-conda.ipynb kernel metadata
 * install-and-set-up.ipynb has new sections and typo corrections
 * system-requirements.ipynb has new info

PR to developers site to update html pages forthcoming

### CODE REVIEW

**Comment by rohitgeo** [comment]
The install guide has a lot of information on the different versions of Pro (1.3, 1.4, 2.0.x and 2.1).

I get a feeling that we should branch it out into a new page so the main installation guide is simpler with just these options:

Preinstalled:
* Try it live
* Have ArcGIS Pro? Go here...

Install:
* conda
* pip
* docker

**Comment by jyaistMap** [comment]
@rohitgeo I'll draft a page for Pro, probably having Pro 2.1 in the Pre-Installed and the Have Pro 2.0 or earlier in the installed.

**Comment by jyaistMap** [comment]
@rohitgeo If [PR#6511](https://github.com/ArcGIS/arcgis-for-developers/pull/6511) gets merged..it'd be a good idea to merge this PR to synch up these guide notebooks with the html pages docs on developers site. The new structure can be put in with a subsequent PR.

**Comment by AtmaMani** [comment]
In interest of time, let us break out the Pro install pages for after DevSummit (March 2018)

**Pull request merged**
