### PR TITLE
Adds PointCNN Guide.

### PR DESCRIPTION
**Pull request by divyanshj16**
Add guide for PointCNN and setup steps too.

@Tamrat-B Please review this.

### CODE REVIEW

**Comment by dmitrykudinov** [comment]
not sure why, but the offered ReviewNB hangs forever and crashes Chrome eventually for me:
image

is there a different option to review the notebook?

**Comment by dmitrykudinov** [comment]
is this the same one here? https://nbviewer.jupyter.org/github/Esri/arcgis-python-api/blob/5e589f7b681aeb728105bc96d11080ad7b032212/guide/14-deep-learning/how_pointcnn_works.ipynb   - if so, I'm looking at it...

**Comment by Tamrat-B** [comment]
@dmitrykudinov Yes it crashed for me and Rohit as well. @rohitgeo is going to reach out to the tools author but meanwhile yes that's the one i'll be looking at as well..

**Comment by dmitrykudinov** [comment]
1. There are numerous syntax and grammatical errors - copy-paste the text into Word document, set the syntax check for **English-US** and fix all the errors.

2. "Point cloud" is a two word term, not one.

3. follow consistent capitalization / terminology: sometimes it's XConv, sometimes Xconv, or even X-Conv.

4. PointCNN by itself is not a model; PointCNN is a deep neural network. The common deep learning terminology is that a persisted neural network, which has gone through some training, is called a model. Such model can be used for inferencing, or to continue the training from a particular moment in time (checkpoint), of for transfer-learning. The first paragraph needs to be rewritten accordingly.

5. The "For advanced users" section needs more details describing how all the parameters work. Illustrate the Figure 1 with the `encoder_params` example.  Show other architectures from the original paper and how they can be matched by `encode_params` settings.

5.1.  some of the PointCNN architectures can be asymmetric, e.g.:
image
But I do not see the `decoder_params` in the constructor. Are we not supporting asymmetric options?

5.2.  How do I configure skip-links between the encoder-decoder?

6. "Get up and running" section needs to be renamed into "Setup steps" or something more indicative. But the main thing: is this for Windows? or Linux? We need multiple sub-sections if the setup steps differ per supported OS.

**Comment by rohitgeo** [comment]
Reviewnb had been fixed. We can use it now as well... @dmitrykudinov @tamrat-b

**Comment by Tamrat-B** [comment]
@rohitgeo @divyanshj16 I’m reworking the document. I will try and complete it tomorrow and will share it here. Will incorporate Dmitry’s feedback as well.

**Comment by dmitrykudinov** [comment]
Installing on Ubuntu using the above instructions.

When running 
`conda install -c esri -c plotly -c owlas laspy=1.6.0 plotly=4.5.0 plotly-orca psutil h5py=2.10.0 transforms3d`
getting
```
PackagesNotFoundError: The following packages are not available from current channels:

  - laspy=1.6.0
```

image

**Comment by dmitrykudinov** [comment]
When running 
`pip install --no-binary torch-cluster==1.4.5 torch-cluster==1.4.5 --no-cache-dir`
getting
```
...
ModuleNotFoundError: No module named 'torch'

```

image

**Comment by divyanshj16** [comment]
@dmitrykudinov The esri channel has laspy for windows, but not on linux.
@rohitgeo who can help us on this?

**Comment by dmitrykudinov** [comment]
Does the Python version matter? e.g. latest miniconda comes with Python 3.8.2, but i am not sure if all the dependencies support it already.

**Comment by divyanshj16** [comment]
I am not sure about that.

**Comment by divyanshj16** [comment]
@dmitrykudinov 

----------------------------------------------------------------------------------------------------------
But I do not see the `decoder_params` in the constructor. Are we not supporting asymmetric options?

5.2. How do I configure skip-links between the encoder-decoder?
-----------------------------------------------------------------------------------------------------------

We only support symmetric decoders. We cannot configure skip links.

**Comment by dmitrykudinov** [comment]
on Ubuntu (probably the same on WIndows): after installing all the components, running `jupyter-lab` as is will not let user to have access to the kernel with PointCNN. In order to do this, before running `jupyter-lab`, I had to install the `ipykernel` into the conda `pytorcharcgis` environment:

```
#installing ipykernel into jupyter-lab
conda install ipykernel
python -m ipykernel install --user --name pytorcharcgis --display-name="pytorcharcgis env"
```

and only then

`jupyter-lab`

**Comment by dmitrykudinov** [comment]
`data.show_batch(...)` draws nothing in the output cell:
image

**Comment by rohitgeo** [comment]
> The esri channel has laspy for windows, but not on linux. @rohitgeo who can help us on this?

@DavidJVitale can you work with @scw on adding laspy on linux.

**Comment by Tamrat-B** [comment]
> @rohitgeo @divyanshj16 I’m reworking the document. I will try and complete it tomorrow and will share it here. Will incorporate Dmitry’s feedback as well.

Hi @divyanshj16 @rohitgeo @dmitrykudinov 

Please review the document below. I have reworked the entire content. Ideally we can spend one more cycle to improve the advanced section, adding additional setup instructions (ubuntu) etc... if time permits. You all should have edit privileges. 
 
https://esriis-my.sharepoint.com/:w:/g/personal/tamr3060_esri_com/EXf87h0I5pROg-8K-dst7eQBC_cVIOfwUS-qX4yG1o-jjg?e=ch55NH 

@divyanshj16 we can convert it to notebook once we are satisfied with all the changes...

**Comment by dmitrykudinov** [comment]
I have set up three different ubuntu machines with the working 1.8 PointCNN API, here are the steps I used in all the cases:

```
# Setup of 1.8 PointCNN on Ubuntu

conda create --name pytorcharcgis
conda activate pytorcharcgis

#default minicinda's Python 8.3.2 does not work with the pytorch we need
conda install python=3.7.3

conda install -c conda-forge requests-toolbelt requests_ntlm
conda install -c esri -c fastai -c pytorch arcgis fastai=1.0.54 pytorch=1.1.0 cudatoolkit=10 scikit-image pillow=6.2.1 fastprogress=0.1.21 --no-pin

#conda install -c esri -c plotly -c owlas laspy=1.6.0 plotly=4.5.0 plotly-orca psutil h5py=2.10.0 transforms3d
conda install -c esri -c plotly -c owlas plotly=4.5.0 plotly-orca psutil h5py=2.10.0 transforms3d

#installed laspy==1.6.0. via pip as conda says esri channel doesn't have it
pip install laspy==1.6.0

pip install --no-binary torch-cluster==1.4.5 torch-cluster==1.4.5 --no-cache-dir
pip install --no-binary torch-sparse==0.4.3 torch-sparse==0.4.3 --no-cache-dir
pip install --no-binary torch-scatter==1.4.0 torch-scatter==1.4.0 --no-cache-dir
pip install --no-binary torch-geometric==1.3.2 torch-geometric==1.3.2 --no-cache-dir

#installing ipykernel into jupyter-lab
conda install ipykernel
python -m ipykernel install --user --name pytorcharcgis --display-name="pytorcharcgis env"

# plotly display fix
#if no nodejs installed:
conda install -c conda-forge nodejs 
#if nodejs is older than 8.3.0:
conda update -c conda-forge nodejs 

#from https://plot.ly/python/getting-started/#jupyterlab-support-python-35
conda install jupyterlab=1.2
conda install "ipywidgets=7.5"
# Avoid "JavaScript heap out of memory" errors during extension installation
# (OS X/Linux)
export NODE_OPTIONS=--max-old-space-size=4096

# Jupyter widgets extension
jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.1 --no-build

# jupyterlab renderer support
jupyter labextension install jupyterlab-plotly@1.5.1 --no-build

# FigureWidget support
jupyter labextension install plotlywidget@1.5.1 --no-build

# Build extensions (must be done to activate extensions since --no-build is used above)
jupyter lab build

# Unset NODE_OPTIONS environment variable
# (OS X/Linux)
unset NODE_OPTIONS


```

**Comment by rohitgeo** [comment]
Thank you @divyanshj16, @Tamrat-B and @dmitrykudinov - the guide is coming along nicely. I have made further edits (with track changes).

@divyanshj16 can you please convert it to notebook and include in the PR? Rename the file to point_cloud_segmentation_using_pointcnn.ipynb. Also, include @dmitrykudinov 's unix script at https://github.com/Esri/arcgis-python-api/tree/master/misc/tools/pointcnn_ubuntu.sh and link to it from this guide in the Setup section.

**Pull request merged**
