### PR TITLE
potential cougar habitat sample notebook

### PR DESCRIPTION
**Pull request by priyankatuteja**
this sample is based on http://desktop.arcgis.com/en/analytics/case-studies/which-areas-are-good-cougar-habitat-.htm

### CODE REVIEW

**Comment by priyankatuteja** [comment]
@Yongyao Could you please help in review of this sample?

**Comment by CMPeng** [comment]
<p>@&nbsp;priyankatuteja This is an interesting notebook, and really fun to read along. Please see my comments above.</p>

**Comment by priyankatuteja** [comment]
@CMPeng  and @Yongyao Thanks for the review. I will be making the suggested changes soon, currently occupied in testing for the upcoming release.

**Comment by priyankatuteja** [comment]
@CMPeng I have made changes and made the introduction lighter. Can you please look at it again and let me know.

**Comment by CMPeng** [comment]
Thanks @priyankatuteja  - the modified version looks pretty good to me. cc @AtmaMani

**Comment by priyankatuteja** [comment]
@CMPeng Thanks for your feedback.

**Comment by AtmaMani** [comment]
@priyankatuteja could you rename this file so it is in all lowercase?

This is good sample which show cases suitability analysis on vector datasets using the derive new locations tool. @priyankatuteja thanks for authoring, @CMPeng thanks for the reviews.

**Comment by priyankatuteja** [comment]
@AtmaMani I have made the name lowercase, somehow missed the first letter. Thanks for your feedback.

**Pull request merged**
