### PR TITLE
update the feed api to v3

### PR DESCRIPTION
**Pull request by CMPeng**
closing https://github.com/Esri/arcgis-python-api/pull/1276, since the api has been updated to v3 (from NASA);
the new sample here uses the updated api, and has corrected the missing data entry (as suggested by Rob Levey from NASA).

### CODE REVIEW

**Comment by CMPeng** [comment]
Hi @jyaistMap,
I have closed the previous PR at https://github.com/Esri/arcgis-python-api/pull/1276, and this new PR addresses the API updates and missing data entry issues. Thanks,
Chunming

**Review by jyaistMap — CHANGES_REQUESTED** [review]
Overall notebook looks great. 
* I made some comments in NBReview
* had conversation with Chunming about the data download procedures and adding a toc

**Comment by CMPeng** [comment]
> Overall notebook looks great.
> 
> * I made some comments in NBReview
> * had conversation with Chunming about the data download procedures and adding a toc

Hi @jyaistMap,
I have addressed all comments you made here, except for the data download part. In order to download the data, not only that you need to create an account, but you also have to authorize the download by linking the access to [GES DISC](https://disc.gsfc.nasa.gov/) to your account, before kick-start the download process with wget or curl. NASA provides a guide that really helps (https://disc.gsfc.nasa.gov/data-access).

Unfortunately, I cannot archive the data along with the notebook - Joanne said this is violating Maxar and NASA's copyright agreement.

Also, if I understand your teams message correctly, does that I mean I don't need to create the TOC in the notebook? since the dev site automatically derives `h2` and `h3` headlines?? Many thanks,
Chunming

**Comment by jyaistMap** [comment]
Correct, @CMPeng You don't need to create the table of Contents in the notebook.  The dev site automatically derives the appropriate headings based on the markdown in the markdown cell (based on the ## or ###)

**Pull request merged**
