### PR TITLE
landcover mapping sample to showcase no data support

### PR DESCRIPTION
**Pull request by guneetmutreja**
Sample to showcase no data support

### CODE REVIEW

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/704/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Thanks</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/704/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>done.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/704/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/704/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
@priyankatuteja Thank you for the review. I have made all the changes you suggested.

**Comment by AtmaMani** [comment]
@BP-Ent could you review this sample?

**Comment by guneetmutreja** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/704/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guneetmutreja** [comment]
@BP-Ent Thank you for the review. @AtmaMani I have incorporated all the changes Breck suggested.

**Comment by priyankatuteja** [comment]
@AtmaMani This sample is missing one imagery data that needs to be provided to users. @guneetmutreja  As discussed in person, please incorporate those changes in a new PR.

**Pull request merged**
