### PR TITLE
part 1 GA guide

### PR DESCRIPTION
**Pull request by priyankatuteja**
Part 1 of GA guide includes the introduction to big data 

-----

# Checklist

Please go through each entry in the below checklist and mark an 'X' if that condition has been met. Every entry should be marked with an 'X' to be get the Pull Request approved.

- [x] All `import`s are in the first cell? First block of imports are standard libraries, second block are 3rd party libraries, third block are all `arcgis` imports? Note that in some cases, for samples, it is a good idea to keep the imports next to where they are used, particularly for uncommonly used features that we want to highlight.
- [x] All `GIS` object instantiations are one of the following?
    - `gis = GIS()`
    - `gis = GIS('https://www.arcgis.com', 'arcgis_python', 'P@ssword123')`
    - `gis = GIS(profile="your_online_profile")`
    - `gis = GIS('https://pythonapi.playground.esri.com/portal', 'arcgis_python', 'amazing_arcgis_123')`
    - `gis = GIS(profile="your_enterprise_portal")`
- [x] If this notebook requires setup or teardown, did you add the appropriate code to `./misc/setup.py` and/or `./misc/teardown.py`?
- [x] If this notebook references any portal items that need to be staged on AGOL/Python API playground, did you coordinate with a Python API team member to stage the item the correct way with the api\_data\_owner user?
- [x] Code refactored & split out across multiple cells, useful comments?
- [x] Consistent voice/tense/narrative style? Thoroughly checked for typos?
- [ ] All images used like `` instead of ``? All map widgets contain a static image preview? (Call `mapview_inst.take_screenshot()` to do so)
- [x] All file paths are constructed in an OS-agnostic fashion with `os.path.join()`? (Instead of `r"\foo\bar"`, `os.path.join(os.path.sep, "foo", "bar")`, etc.)
- [ ] **IF YOU WANT THIS SAMPLE TO BE DISPLAYED ON THE DEVELOPERS.ARCGIS.COM WEBSITE**, ping @ DavidJVitale so he can add it to the list for the next deploy

### CODE REVIEW

**Review by AtmaMani — CHANGES_REQUESTED** [review]
@priyankatuteja great introduction for the GAX chapter of the guide book.

Requested changes:
## What is Geospatial big data?
### Volume
 - [x] Add "Some examples of volume in big data" before "Every 60 seconds:"
### What is GeoAnalytics Server?
 - [x] In the hex diagram, change 'Tools to use proximity' to 'Tools that analyze proximity' and 'Custom analysis endpoint' to 'Extend with custom tools'
- [x] change "Object model diagram..." to "Layout of the `arcgis.geoanalytics` module" As this is not an OMD in the strictest sense. What we provide is rather an abstracted layout diagram.
- [x] can we expand each of the analysis capabilities in the layout diagram? I feel the true power of the module comes out when we list the available tools

**Comment by priyankatuteja** [comment]
@AtmaMani I added the changes, but I am struggling in changing the Layout to include names of all the tools in a confined diagram. If you have a suggestion for a layout structure, it will be helpful.

**Review by AtmaMani — CHANGES_REQUESTED** [review]
Revisions look good thanks. Can you lowercase the filename?

**Comment by AtmaMani** [comment]
Closes https://github.com/ArcGIS/geosaurus/issues/4386

**Review by AtmaMani — APPROVED** [review]

**Pull request merged**
