### PR TITLE
Added guide for retraining windows/doors model

### PR DESCRIPTION
**Pull request by deepinderdeol**
This is a new guide for retraining the default Esri Windows and Doors model that is used by the Interactive Object Detection tool in ArcGIS Pro 2.7. The notebook is being shared as a guide instead of a sample because of the additional step requiring unzipping the DLPK.

@rohitgeo can you please review.

Thanks.

### CODE REVIEW

**Comment by deepinderdeol** [comment]
@vikashranjan26 @vbhv14 can you please review this guide.
Thanks.

**Comment by priyankatuteja** [comment]
@deepinderdeol We could keep it as a sample notebook because the unzipping part isn't needed. The latest arcgis 1.8.3 has an enhancement that takes care of unzipping part if a user provides a .dlpk path instaed of .emd path,. So you should be able to search/get item and then download it. Further get path where the data got downloaded and pass it into the from_model.

sample code:

```
import os, zipfile
from pathlib import Path
from arcgis.gis import GIS
gis = GIS('home')
model = gis.content.get('8c0078cc7e314e31b20001d94daace5e')
modelpath = training_data.download(file_name=model.name)
```

**Comment by deepinderdeol** [comment]
@priyankatuteja the Windows-Doors DLPK that is currently shared online has to be unzipped because recreating model directly from this DLPK does not work - I will forward you the email discussion on this. Because unzipping is required, it was decided to add this notebook as a guide instead of a sample.

**Comment by deepinderdeol** [comment]
@vbhv14 thanks for reviewing. Notebook has been updated based on your suggestions - please let me know if any other edits are needed.

Regarding unzipping of DLPK - as has been discussed in the email on this issue, we will not be replacing the currently shared DLPK at this time. The reason primarily is that the new Interactive-Detection-Tool is hooked directly to this DLPK and we do not want to get into a situation where we end up breaking the tool for ArcGIS Pro 2.7. We can replace the DLPK and update this guide at a future release.

**Review by vbhv14 — APPROVED** [review]
@deepinderdeol thanks for the changes.

**Comment by deepinderdeol** [comment]
Please let me know when this is good to merge. My understanding is that more than one reviewer-approval is usually required.

**Comment by shivanip32** [comment]
@deepinderdeol, It will look better if we can print the outputs of show_batch, show_results, data.classes, lr_find, fcnn.fit(), average_precision_score value. Then it will be more user friendly and user will get to know how the workflow works and what to expect, right now the guide only shows code. If we can add a paragraph for export training data it will be more informative, user might not know how to export data for a 3d model. You can refer the [object detection model guide](https://developers.arcgis.com/python/guide/object-detection/).

**Comment by deepinderdeol** [comment]
@shivanip32 thanks for the review.

**Regarding exporting training data** - currently there are no tools in ArcGIS Pro for exporting training images from 3D scenes for 3D features (buildings, windows etc.). Users will either need to capture screenshots from ArcGIS Pro and label using something like LabelImg, or they can look for open source datasets - we used OpenImages dataset for training the default model. Please note that there are also data licensing issues with using ArcGIS Pro exported images for training DL models. Do we want to add this information in the guide or should we let users figure out where/how they will get the training images?

**Showing outputs** - the only data for which we got licensing approval was OpenImages, which is what the default model is trained with. We do not have permission to use any other images _(open-source OR Pro-exported data)_ so if we were to show output (show batch, results etc.) we will need to basically retrain the model with the same data that we have already used. I think we can leave the guide as-is, without showing any output. Please let me know if showing output is still required and I can make the edits.

**Comment by deepinderdeol** [comment]
@AtmaMani guide has been updated. 
As discussed, I did not add the code for downloading/previewing the dlpk. The dlpk url was updated to use the short link provided by Vaibhav.

**Pull request merged**
