### PR TITLE
multi gpu training guide

### PR DESCRIPTION
**Pull request by priyankatuteja**
multi gpu training guide https://github.com/ArcGIS/geosaurus/issues/4306

### CODE REVIEW

**Comment by priyankatuteja** [comment]
in progress, not yet complete

**Comment by priyankatuteja** [comment]
@KarthikDutt and @vikashranjan26 Could you please provide suggestions to improve the guide

**Comment by priyankatuteja** [comment]
@KarthikDutt and @vikashranjan26 Could you please provide suggestions to improve the guide

**Comment by KarthikDutt** [comment]
Minor review comments below . I couldn't for some reason use Notebook Reviewer , hence posting my review comments below. 

Line - In this guide, we will walk you through how arcgis.learn models with PyTorch backend support training in multiple GPUs. 
Comment - add a comma after backend. 
	            Instead of 'training in multiple GPUs', consider 'training across multiple GPUs' 

Line - Once you know how many GPU's are available, you can use one of the ways to train your model.
Consider changing it to 
'Once you know how many GPU's are available, you can use **either of** the two ways to train your model'

Line - Either of the two ways has its own significance
Consider changing this to:
'**Each** of the two ways has its own significance'

Line - They are easy ways of wrapping your code to add the capability of training the model on multiple GPUs.
Consider merging this statement with previous one to make it:
'Each of the two ways has its own significance and offer easy way of wrapping your code to add the capability of training the model on multiple GPUs.'

 Line - Data Parallelism is when we split the mini-batch of samples into multiple smaller mini-batches and run the computation for each of the smaller mini-batches in parallel
Consider changing this to:
' Data Parallelism is when we split the mini-batch of samples into multiple smaller mini-batches and run the computation for each of the smaller mini-batches in parallel **across multiple GPUs**.

Line - One can wrap a Module in DataParallel and it will be parallelized over multiple GPUs in the batch dimension
Consider changing this to as we are speaking directly to the user in the previous sentences.
'**You** can wrap a Module in DataParallel and it will be parallelized over multiple GPUs in the batch dimension'

Line - This makes it easy for users to utilize multiple GPUS
Consider changing this to:
'This makes it easy for users to utilize multiple **GPUs**'

Line - Model parallelism: **is is** when we 
Change this to:
Model parallelism: is when we 

Line - It parallelizes the application of the given module by 
Consider changing this to:
'**This approach** parallelizes the application of the given module by' 

Line - To run, copy paste the command in your command prompt:
Consider changing this to:
'**Execute the command** shown below in your command prompt:'

**Review by KarthikDutt — CHANGES_REQUESTED** [review]
Added my suggestions in the comments. Please incorporate where applicable.

**Comment by priyankatuteja** [comment]
@KarthikDutt I have made the changes you suggested. Thanks!

**Comment by priyankatuteja** [comment]
@KarthikDutt I have made the changes you suggested. Thanks!

**Comment by priyankatuteja** [comment]
@BP-Ent Please review the utilize_multiple_gpus_to_train_model.ipynb

**Comment by priyankatuteja** [comment]
@BP-Ent Please review the utilize_multiple_gpus_to_train_model.ipynb

**Comment by priyankatuteja** [comment]
@vikashranjan26 Please take out time to verify the commands and model names that have been supported with  multi-gpu enhancement.

**Comment by priyankatuteja** [comment]
@vikashranjan26 Please take out time to verify the commands and model names that have been supported with  multi-gpu enhancement.

**Review by BP-Ent — CHANGES_REQUESTED** [review]
Minor changes suggested on ReviewNB

**Pull request closed without merging**
