### PR TITLE
deep learning samples

### PR DESCRIPTION
**Pull request by priyankatuteja**
@shivanip32 please check the following are updated
- world imagery reference removed #search world imagery in ctrl+F and check for any keyword left
- search method changed to get method
- sample is working in try t live (please upload the notebook on geosaurus org and run #create a test folder) #make sure to change runtime to 5.0 with gpu

Notebooks: #tick them as you complete testing it
- [ ] address-standardization-and-correction-with-sequencetosequence.ipynb #take notebook from this pr
- [ ] [automate_road_surface_investigation_using_deep_learning.ipynb](https://geosaurus.maps.arcgis.com/home/item.html?id=72b6c19f5944424f830b44346f0fef89)
- [ ] automate_building_footprint_extraction_using_instance_segmentation.ipynb #take notebook from this pr
- [x] automatic_road_extraction_using_deep_learning.ipynb #take notebook from this pr
- [ ] [building_reconstruction_using_mask_rcnn.ipynb](https://geosaurus.maps.arcgis.com/home/item.html?id=3b3f9bacf88c4661911cb8c0e1a95757)
- [x] change_detection_of_buildings_from_satellite_imagery.ipynb #take notebook from this pr
- [x] detecting_and_categorizing_brick_kilns_from_satellite_imagery.ipynb #take notebook from this pr
- [ ] extracting_building_footprints_from_drone_data.ipynb
- [x] land_parcel_extraction_using_edge_detection_deep_learning_model #take notebook from this pr
- [ ] swimming pools updated
- [ ] pixtopix sample updated
- [ ] textclassifier notebook updated path
- [ ] temperature forecast
- [ ] tower and trees detection sample updated to be live
- [ ] streams extraction updated
- [ ] tabular sample updated
- [ ] supreres updated
- [ ] shipwrecks updated
- [ ] hyperspectral sample updated
- [ ] lulc sparse data sample updated

### CODE REVIEW

**Comment by priyankatuteja** [comment]
image

image

**Comment by priyankatuteja** [comment]
@shivanip32 Please complete https://github.com/ArcGIS/geosaurus/issues/6279 for doing review of the two missing notebooks on agol org.

issue fixed https://github.com/ArcGIS/geosaurus/issues/6351

**Comment by shivanip32** [comment]
[building_reconstruction_using_mask_rcnn](https://geosaurus.maps.arcgis.com/home/notebook/notebook.html?id=5a13d700c75d4df796b7067c6659ab43#)

Error:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _try_get_data(self, timeout)
    760         try:
--> 761             data = self._data_queue.get(timeout=timeout)
    762             return (True, data)

/opt/conda/lib/python3.7/multiprocessing/queues.py in get(self, block, timeout)
    103                     timeout = deadline - time.monotonic()
--> 104                     if not self._poll(timeout):
    105                         raise Empty

/opt/conda/lib/python3.7/multiprocessing/connection.py in poll(self, timeout)
    256         self._check_readable()
--> 257         return self._poll(timeout)
    258 

/opt/conda/lib/python3.7/multiprocessing/connection.py in _poll(self, timeout)
    413     def _poll(self, timeout):
--> 414         r = wait([self], timeout)
    415         return bool(r)

/opt/conda/lib/python3.7/multiprocessing/connection.py in wait(object_list, timeout)
    920             while True:
--> 921                 ready = selector.select(timeout)
    922                 if ready:

/opt/conda/lib/python3.7/selectors.py in select(self, timeout)
    414         try:
--> 415             fd_event_list = self._selector.poll(timeout)
    416         except InterruptedError:

/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py in handler(signum, frame)
     65         # Python can still get and update the process status successfully.
---> 66         _error_if_any_worker_fails()
     67         if previous_handler is not None:

RuntimeError: DataLoader worker (pid 442) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-8-ee99c62a182b> in <module>
----> 1 data.show_batch(rows=2)

/opt/conda/lib/python3.7/site-packages/arcgis/learn/_utils/rcnn_masks.py in show_batch_rcnn_masks(self, rows, alpha, **kwargs)
     42     n_items = min(n_items, len(self.x))
     43 
---> 44     x_batch, y_batch = get_nbatches(data_loader, n_items)
     45     x_batch = torch.cat(x_batch)
     46     y_batch = torch.cat(y_batch)

/opt/conda/lib/python3.7/site-packages/arcgis/learn/_utils/common.py in get_nbatches(data_loader, nbatches)
    288         i+=1
    289         try:
--> 290             x, y = next(dl_iterater)
    291             x_batch.append(x)
    292             y_batch.append(y)

/opt/conda/lib/python3.7/site-packages/fastai/basic_data.py in __iter__(self)
     73     def __iter__(self):
     74         "Process and returns items from `DataLoader`."
---> 75         for b in self.dl: yield self.proc_batch(b)
     76 
     77     @classmethod

/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    343 
    344     def __next__(self):
--> 345         data = self._next_data()
    346         self._num_yielded += 1
    347         if self._dataset_kind == _DatasetKind.Iterable and \

/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    839 
    840             assert not self._shutdown and self._tasks_outstanding > 0
--> 841             idx, data = self._get_data()
    842             self._tasks_outstanding -= 1
    843 

/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _get_data(self)
    806         else:
    807             while True:
--> 808                 success, data = self._try_get_data()
    809                 if success:
    810                     return data

/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _try_get_data(self, timeout)
    772             if len(failed_workers) > 0:
    773                 pids_str = ', '.join(str(w.pid) for w in failed_workers)
--> 774                 raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
    775             if isinstance(e, queue.Empty):
    776                 return (False, None)

RuntimeError: DataLoader worker (pid(s) 442, 445) exited unexpectedly
```

**Comment by shivanip32** [comment]
lr_find is failing in [building_reconstruction_using_mask_rcnn](https://geosaurus.maps.arcgis.com/home/notebook/notebook.html?id=5a13d700c75d4df796b7067c6659ab43#)

```
lr = model.lr_find()
lr
```
Error:
```
LR Finder is complete, type {learner_name}.recorder.plot() to see the graph.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-ed468e037d0d> in <module>
      1 # The users can visualize the learning rate of the model with comparative loss.
----> 2 lr = model.lr_find()
      3 lr

/opt/conda/lib/python3.7/site-packages/arcgis/learn/models/_arcgis_model.py in lr_find(self, allow_plot)
    538         except Exception as e:
    539             # if some error comes in lr_find
--> 540             raise e
    541         finally:
    542             self.learn.metrics = metrics

/opt/conda/lib/python3.7/site-packages/arcgis/learn/models/_arcgis_model.py in lr_find(self, allow_plot)
    535             metrics = self.learn.metrics
    536             self.learn.metrics = []
--> 537             self.learn.lr_find()
    538         except Exception as e:
    539             # if some error comes in lr_find

/opt/conda/lib/python3.7/site-packages/fastai/train.py in lr_find(learn, start_lr, end_lr, num_it, stop_div, wd)
     39     cb = LRFinder(learn, start_lr, end_lr, num_it, stop_div)
     40     epochs = int(np.ceil(num_it/len(learn.data.train_dl)))
---> 41     learn.fit(epochs, start_lr, callbacks=[cb], wd=wd)
     42 
     43 def to_fp16(learn:Learner, loss_scale:float=None, max_noskip:int=1000, dynamic:bool=True, clip:float=None,

/opt/conda/lib/python3.7/site-packages/fastai/basic_train.py in fit(self, epochs, lr, wd, callbacks)
    198         else: self.opt.lr,self.opt.wd = lr,wd
    199         callbacks = [cb(self) for cb in self.callback_fns + listify(defaults.extra_callback_fns)] + listify(callbacks)
--> 200         fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
    201 
    202     def create_opt(self, lr:Floats, wd:Floats=0.)->None:

/opt/conda/lib/python3.7/site-packages/fastai/basic_train.py in fit(epochs, learn, callbacks, metrics)
     99             for xb,yb in progress_bar(learn.data.train_dl, parent=pbar):
    100                 xb, yb = cb_handler.on_batch_begin(xb, yb)
--> 101                 loss = loss_batch(learn.model, xb, yb, learn.loss_func, learn.opt, cb_handler)
    102                 if cb_handler.on_batch_end(loss): break
    103 

/opt/conda/lib/python3.7/site-packages/fastai/basic_train.py in loss_batch(model, xb, yb, loss_func, opt, cb_handler)
     24     if not is_listy(xb): xb = [xb]
     25     if not is_listy(yb): yb = [yb]
---> 26     out = model(*xb)
     27     out = cb_handler.on_loss_begin(out)
     28 

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

/opt/conda/lib/python3.7/site-packages/torchvision/models/detection/generalized_rcnn.py in forward(self, images, targets)
     68         if isinstance(features, torch.Tensor):
     69             features = OrderedDict([('0', features)])
---> 70         proposals, proposal_losses = self.rpn(images, features, targets)
     71         detections, detector_losses = self.roi_heads(features, proposals, images.image_sizes, targets)
     72         detections = self.transform.postprocess(detections, images.image_sizes, original_image_sizes)

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

/opt/conda/lib/python3.7/site-packages/torchvision/models/detection/rpn.py in forward(self, images, features, targets)
    470         proposals = self.box_coder.decode(pred_bbox_deltas.detach(), anchors)
    471         proposals = proposals.view(num_images, -1, 4)
--> 472         boxes, scores = self.filter_proposals(proposals, objectness, images.image_sizes, num_anchors_per_level)
    473 
    474         losses = {}

/opt/conda/lib/python3.7/site-packages/torchvision/models/detection/rpn.py in filter_proposals(self, proposals, objectness, image_shapes, num_anchors_per_level)
    393             boxes, scores, lvl = boxes[keep], scores[keep], lvl[keep]
    394             # non-maximum suppression, independently done per level
--> 395             keep = box_ops.batched_nms(boxes, scores, lvl, self.nms_thresh)
    396             # keep only topk scoring predictions
    397             keep = keep[:self.post_nms_top_n()]

/opt/conda/lib/python3.7/site-packages/torchvision/ops/boxes.py in batched_nms(boxes, scores, idxs, iou_threshold)
     74     offsets = idxs.to(boxes) * (max_coordinate + 1)
     75     boxes_for_nms = boxes + offsets[:, None]
---> 76     keep = nms(boxes_for_nms, scores, iou_threshold)
     77     return keep
     78 

/opt/conda/lib/python3.7/site-packages/torchvision/ops/boxes.py in nms(boxes, scores, iou_threshold)
     34         by NMS, sorted in decreasing order of scores
     35     """
---> 36     return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
     37 
     38 

/opt/conda/lib/python3.7/site-packages/torch/_ops.py in __getattr__(self, op_name)
     59         # for overloads and raise an exception if there are more than one.
     60         qualified_op_name = '{}::{}'.format(self.name, op_name)
---> 61         op = torch._C._jit_get_operation(qualified_op_name)
     62         # let the script frontend know that op is identical to the builtin op
     63         # with qualified_op_name

RuntimeError: No such operator torchvision::nms
```

**Comment by priyankatuteja** [comment]
@shivanip32 

image

it is working on try it live, you can restart the notebook and try. The issue you faced might have been because you were running multiple notebooks simultaneously

**Review by shivanip32 — APPROVED** [review]

**Pull request merged**
