### PR TITLE
volcano erauption sample

### PR DESCRIPTION
**Pull request by CMPeng**
- [ ] Address Atma's reviews
 - [ ] Address BP's reviews
 - [ ] pending distribution license

### CODE REVIEW

**Comment by priyankatuteja** [comment]
@CMPeng Is this PR ready for review?

**Comment by CMPeng** [comment]
Hi @priyankatuteja yes, I have heard back from Maxar and Noaa. Will add some citations, and involve Breck for the first round of reviews. Thanks!

**Comment by jyaistMap** [comment]
* talked with @CMPeng and this sample needs rewritten because the url changed for the feeds site, and the content changes as well

**Comment by CMPeng** [comment]
> * talked with @CMPeng and this sample needs rewritten because the url changed for the feeds site, and the content changes as well

Yes per conversation with @jyaistMap - the Feed API has been upgraded to 3.0 and the Tonga Volcano entry has been missing ever since, and I am contacting their data administrators about this missing info.

**Comment by CMPeng** [comment]
Closing this PR, and addressing the changes to the new PR https://github.com/Esri/arcgis-python-api/pull/1398

**Pull request closed without merging**
