### PR TITLE
Updated CycleGAN sample with new export support format

### PR DESCRIPTION
**Pull request by kapil-varshney**
Updated the CycleGAN sample notebook with the new export support for CycleGAN in Pro.

### CODE REVIEW

**Comment by kapil-varshney** [comment]
@priyankatuteja The changes have been made over https://github.com/Esri/arcgis-python-api/pull/994

**Comment by kapil-varshney** [comment]
@priyankatuteja The changes have been made over https://github.com/Esri/arcgis-python-api/pull/994

**Comment by priyankatuteja** [comment]
@kapil-varshney  
1. update image collection item as the exported data come sin new format now
2. remove world imagery reference from the export part, we need to provide a local RGB imagery , should not be using world imagery at all.
3. Add the model inferencing section using Pro

**Comment by priyankatuteja** [comment]
https://github.com/Esri/arcgis-python-api/pull/952/files

**Comment by mohi9282** [comment]
@kapil-varshney - any updates on the requested changes? Changes need to be reviewed and merged ASAP as the guide is scheduled for V1.9.1.

cc: @AtmaMani @priyankatuteja

**Comment by mohi9282** [comment]
removing from v1.9.1 milestone per discussion with Kapil.

**Comment by kapil-varshney** [comment]
@guneetmutreja As discussed, can you please update the notebook?

**Comment by priyankatuteja** [comment]
closing pr, as discussed @guneetmutreja will make changes and create a new pr

**Pull request closed without merging**
