### PR TITLE
add covid19 samples

### PR DESCRIPTION
**Pull request by CMPeng**
New PR to continue with https://app.reviewnb.com/Esri/arcgis-python-api/pull/598/

COVID19 sample in 3 parts:
1. global mapping (using Feature Layer instead of the Github link provided by JHU)
2. time-series charting (using the Github link provided by JHU))
3. predictive analysis (using the Github link provided by JHU))

### CODE REVIEW

**Comment by CMPeng** [comment]
Hi @AtmaMani a question regarding to your comment in the previous PR "the time series analysis notebook can go in the data-scientist section instead of content-publisher section" (that @priyankatuteja reminded me of), do you mean only part_2 and _3 in this case? or all three parts of them? Thanks!

**Comment by AtmaMani** [comment]
@CMPeng I reviewed part 1, its a great notebook. Please find my suggestions on the reviewnb app.

**Comment by AtmaMani** [comment]
closes ArcGIS/Geosaurus#4023

**Comment by AtmaMani** [comment]
@CMPeng this is great work and is going to be a valuable addition to our data science series of samples.

**Comment by CMPeng** [comment]
<p>@AtmaMani, the link you provided does not contain province names, and also geo-enrichment module does not have province level info for that of China. I have changed the data source to be using a feature layer I created under api_data_owner account to replace the original source.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/685/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by CMPeng** [comment]
<p>@AtmaMani, I think there is a bug with the ClassColorRenderer in the Map Widget, because whenever I changed the classification method from Natural breaks to other types, and the changes are not applied in the display.</p><p> </p><p>Also, I checked when the map widget is saved into a web map, the config panel in the home app actually shows that it is using something called "ManualBreaks", and when I changed it to Natural breaks in the settings there, the map starts to show completely different patterns from the map widget (in the notebook). Please see the three screenshots I have added to the notebook (in which I have said this is what it looks like when saved as web map item, and its symbology changed).</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/685/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by CMPeng** [comment]
<p>@AtmaMani, I have added a new paragraph trying to put more explanation, and also pasted an external link for further references.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/685/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by CMPeng** [comment]
<p>Plot is modified, and please check out the newly added explanations.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/685/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by CMPeng** [comment]
<p>Yes, typo corrected.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/685/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by CMPeng** [comment]
<p>yes, output removed - no print() actions now.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/685/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by CMPeng** [comment]
<p>@AtmaMani, the plots are once again created with the newly updated stats. Please check again if the plots look jumpy to you. For me, it is looking OK.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/685/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by CMPeng** [comment]
<p>Thank you so much @AtmaMani for the detailed suggestions, and I have addressed all the comments (or at least tried to). Two issues that still might need attention would be:</p><ol><li>the Natural breaks classColorRenderer (it must have been a bug, because it does not correspond to the MapViewer in the browser)</li><li>More explanations added to the Compositing part (split and stack cycles)</li></ol>

**Comment by AtmaMani** [comment]
<p>Ok sounds good</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/685/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AtmaMani** [comment]
<p>Yes, I think we have a bug in the renderer generation code (in Python API side), we will address it separately</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/685/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AtmaMani** [comment]
<p>Yes the changes look good, thanks Chunming</p>

**Comment by AtmaMani** [comment]
<p>The look better now</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/685/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
