### PR TITLE
Tropospheric NO2 Monitoring using Sentinel-5P over Wuhan

### PR DESCRIPTION
**Pull request by shivanip32**
Tropospheric NO2 Monitoring using Sentinel-5P over Wuhan
-----

# Checklist

Please go through each entry in the below checklist and mark an 'X' if that condition has been met. Every entry should be marked with an 'X' to be get the Pull Request approved.

- [x] All `import`s are in the first cell? First block of imports are standard libraries, second block are 3rd party libraries, third block are all `arcgis` imports? Note that in some cases, for samples, it is a good idea to keep the imports next to where they are used, particularly for uncommonly used features that we want to highlight.
- [x] All `GIS` object instantiations are one of the following?
    - `gis = GIS()`
    - `gis = GIS('https://www.arcgis.com', 'arcgis_python', 'P@ssword123')`
    - `gis = GIS(profile="your_online_profile")`
    - `gis = GIS('https://pythonapi.playground.esri.com/portal', 'arcgis_python', 'amazing_arcgis_123')`
    - `gis = GIS(profile="your_enterprise_portal")`
- [ ] If this notebook requires setup or teardown, did you add the appropriate code to `./misc/setup.py` and/or `./misc/teardown.py`?
- [x] If this notebook references any portal items that need to be staged on AGOL/Python API playground, did you coordinate with a Python API team member to stage the item the correct way with the api\_data\_owner user?
- [x] Code refactored & split out across multiple cells, useful comments?
- [x] Consistent voice/tense/narrative style? Thoroughly checked for typos?
- [x] All images used like `` instead of ``? All map widgets contain a static image preview? (Call `mapview_inst.take_screenshot()` to do so)
- [x] All file paths are constructed in an OS-agnostic fashion with `os.path.join()`? (Instead of `r"\foo\bar"`, `os.path.join(os.path.sep, "foo", "bar")`, etc.)
- [x] **IF YOU WANT THIS SAMPLE TO BE DISPLAYED ON THE DEVELOPERS.ARCGIS.COM WEBSITE**, ping @ DavidJVitale so he can add it to the list for the next deploy

### CODE REVIEW

**Comment by AtmaMani** [comment]
@shivanip32 @priyankatuteja @guneetmutreja hold off on reviewing this sample. There is a way programmatically search and download 5P data using `sentinelsat` library and there is a way to convert netCDF to `Raster` layers using ArcPy and the new `Raster` object. I will push an update to this in a few days and you can review that.

There is one outstanding issue that I need to resolve in `Raster` class and I can push my notebooks up this PR (or I will create a new one)

**Comment by shivanip32** [comment]
@AtmaMani, could you find time to update the steps for programmatically search and download 5P data using sentinelsat library and to convert netCDF to Raster layers using ArcPy and the new Raster object.

**Comment by AtmaMani** [comment]
@shivanip32 I have solved the programmatic download and added a few more enhancements (such as concurrent downloads etc.) I changed the analysis workflow to build out a multivariate multidimensional dataset for two different years and compare the no2 differences. You can find my work in progress [notebooks here](https://github.com/AtmaMani/arcgis-python-api/tree/atma-no2-monitoring/samples/04_gis_analysts_data_scientists/no2_monitoring). I plan to finish this by the end of this sprint if everything works out.

**Comment by priyankatuteja** [comment]
@AtmaMani Awesome! Looking forward to seeing the upcoming sample notebook. Meanwhile, closing this PR as discussed with @shivanip32

**Pull request closed without merging**
