### PR TITLE
Update DevLabs

### PR DESCRIPTION
**Pull request by ChrisFrenchPDX**
I'm making changes to the Python DevLabs (https://github.com/ArcGIS/arcgis-for-developers/pull/8153) and so I also need to make changes to the Jupyter lab notebooks.

- I've updated the Jupyter notebooks, including adding a new notebook as a "Starter App", similar for what we do with the JavaScript API.
- In the coming months, we are changing `DevLabs` to `tutorials`, so I've started with that change in this update.
- I've tried to change variable names to keep them more readable, and I've tested the code in the notebooks to make sure they work.
- Use `Path` from `pathlib` instead of `os` to access system files and resources.

### CODE REVIEW

**Comment by alaframboise** [comment]
@jyaistMap @AtmaMani he guys, just we are still making a few changes to the labs, but wanted to double-check you will be able to update the external notebook solutions to support the DevLabs > Tutorial name change?  Thanks!

**Comment by patrickarlt** [comment]
@jyaistMap @AtmaMani we are planning on wrapping up https://github.com/ArcGIS/arcgis-for-developers/pull/8153 this week. We also would like these changes merged so everything is consistent between the lab text and the actual solutions.

**Comment by AtmaMani** [comment]
@ChrisFrenchPDX the contents of the notebooks look good. Thanks for not just updating verbatim but also the code. The URLs point to `labs` and the folder name in our repo is `labs`. Should we change these to `tutorials`?

**Comment by ChrisFrenchPDX** [comment]
> @ChrisFrenchPDX the contents of the notebooks look good. Thanks for not just updating verbatim but also the code. The URLs point to `labs` and the folder name in our repo is `labs`. Should we change these to `tutorials`?

Thanks @AtmaMani! At the moment, the URLs will stay the same, so everything should be good.

**Pull request merged**
