### PR TITLE
Delhi sample

### PR DESCRIPTION
**Pull request by guneetmutreja**
- [x] All `import`s are in the first cell? First block of imports are standard libraries, second block are 3rd party libraries, third block are all `arcgis` imports?
- [x] All `GIS` object instantiations are one of the following?
    - `gis = GIS('https://www.arcgis.com', 'arcgis_python', 'P@ssword123')`
    - `gis = GIS(profile="your_online_profile")`
    - `gis = GIS('https://pythonapi.playground.esri.com/portal', 'arcgis_python', 'amazing_arcgis_123')`
    - `gis = GIS(profile="your_enterprise_portal")`
- [x] If this notebook requires setup or teardown, did you add the appropriate code to `./misc/setup.py` and/or `./misc/teardown.py`?
- [x] If this notebook references any portal items that need to be staged on AGOL/Python API playground, did you coordinate with a Python API team member to stage the item the correct way with the api\_data\_owner user?
- [x] Code refactored & split out across multiple cells, useful comments?
- [x] Consistent voice/tense/narrative style? Thoroughly checked for typos?
- [x] All images used like `` instead of ``? All map widgets contain a static image preview? (Call `mapview_inst.take_screenshot()` to do so)
- [x] All file paths are constructed in an OS-agnostic fashion with `os.path.join()`? (Instead of `r"\foo\bar"`, `os.path.join(os.path.sep, "foo", "bar")`, etc.)
- [ ] **IF YOU WANT THIS SAMPLE TO BE DISPLAYED ON THE DEVELOPERS.ARCGIS.COM WEBSITE**, ping @ DavidJVitale so he can add it to the list for the next deploy

### CODE REVIEW

**Comment by guneetmutreja** [comment]
https://github.com/ArcGIS/geosaurus/issues/2847

**Comment by guneetmutreja** [comment]
@moonlanderr I've made these changes, please review it and let me know if there are more

**Comment by moonlanderr** [comment]
@AtmaMani this sample is ready for further review. You may add to your review list.

**Comment by guneetmutreja** [comment]
@AtmaMani Did you get a chance to have a look at the notebook? Any updates or changes, I need to incorporate?

**Comment by AtmaMani** [comment]
@guneetmutreja not yet. It has been a busy week.

**Comment by AtmaMani** [comment]
<p>Change file name so it is same as the title. Use lowercase and no spaces or special characters.</p>

**Comment by AtmaMani** [comment]
@shivanip32, @moonlanderr thanks for the detailed review
@guneetmutreja this is a good sample, I have asked for a few changes including the file name. For future, I would recommend expanding this sample by running a veg analysis on prior date (2015) and the current one on 2017 to see if you observe a change in green cover %

**Comment by guneetmutreja** [comment]
<p>@Atma thanks for the review. I have made all the changes you suggested and made a commit. Please have a look at the same. I will surely work on your recommendations for expanding the notebook in the near future. </p>

**Comment by AtmaMani** [comment]
Looks good, thanks @guneetmutreja

**Pull request merged**
