### PR TITLE
pointcnn guide update

### PR DESCRIPTION
**Pull request by vbhv14**
- [x] fixed, references to APA 6th.

- [x] env set up steps .
 
- [x] add best practices section.

### CODE REVIEW

**Comment by priyankatuteja** [comment]
@divyanshj16  Could you help in reviewing the best practices section

**Review by guneetmutreja — CHANGES_REQUESTED** [review]
Please incorporate the changes mentioned by @divyanshj16.

**Comment by vbhv14** [comment]
@divyanshj16 added the changes you suggested.
let me know if anything else is needed in the best practices section.
like, any best-practices/tips you think I might have missed, which will be useful for the user.

**Review by guneetmutreja — APPROVED** [review]
Thank you for the changes.

**Review by AtmaMani — APPROVED** [review]

**Pull request merged**
