### PR TITLE
Update the Using the map widget Guide for the 2.4 release

### PR DESCRIPTION
**Pull request by jyaistMap**
* updated the guide for 2.4 syntax
* added a gif to illustrate the basemap code

### CODE REVIEW

**Review by nanaeaubry — APPROVED** [review]
Looked through the notebook changes and everything looks great!

**Review by cariashuang0417 — APPROVED** [review]
Overall looks good to me! Just commented on some hyperlink broken and narrative needs to update. I forgot if the hyperlink for developer website pages will be working fine after doc is built, if so then just ignore those comments 😅

**Comment by jyaistMap** [comment]
<p>The code is correct in the guide.  The cells will not run when previewing because in the source notebook the code is actually code that displays an image.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1906/discussion/#comment-2291891690'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jyaistMap** [comment]
<p>Done! Thanks...I missed that!</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1906/discussion/#comment-2291891719'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jyaistMap** [comment]
<p>Removed the markdown that made it a hyperlink and updated the sentence. I can't find the app.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1906/discussion/#comment-2291891744'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jyaistMap** [comment]
<p>The relative links will not work directly in a review unless you've built the website locally.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1906/discussion/#comment-2291891762'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jyaistMap** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1906/discussion/#comment-2291891704'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
