### PR TITLE
PointCNN sample

### PR DESCRIPTION
**Pull request by vbhv14**
this PR is for sample notebook for PointCNN.
Best practices will be added to the pointcnn guide.

### CODE REVIEW

**Comment by guneetmutreja** [comment]
A few changes I would like to suggest:

1. The Classified output shows all classification from some template (codes) where 0 and 1 belong to the classified points and everything else. The name of the 0 class is “Never Classified” and 1 is "Unassigned", we should change it to some more logical name may be- Classified for class 0. See if the template can also be replaced as I feel it is not relevant here and can be a bit confusing for users.
As an instance, I trained a building footprint detection model and after classification, it got mapped to 0 (with "Never classified name") but the template also has a building class at number 6 which may confuse users.

image

**Comment by guneetmutreja** [comment]
2.	The model builder has local paths for the DB that throws an error, try to replace it with relative paths.

image

**Comment by guneetmutreja** [comment]
3.	Mention the point that we need to filter out only building points from the output and pass it to the model builder, also try to show the steps to do it.

4.	Try to create a tool out of the model builder as users may use it as it is atleast for the case we are presenting in the notebook (building footprint detection) and may not be interested to manually edit the model builder and run it.

**Review by guneetmutreja — CHANGES_REQUESTED** [review]
Please see if we can incorporate the changes I mentioned.

**Comment by vbhv14** [comment]
> Please see if we can incorporate the changes I mentioned.

thanks,
 the 'relative paths', 'run from tool', etc. _(point, 2,3, & 4.)_ fixed via updating the AGOL item.
In the notebook, I have added general instructions for _other points_ & specific instructions to address _point 1_.

**Comment by guneetmutreja** [comment]
Hello @vbhv14,
Please incorporate the remaining changes as discussed.

**Review by guneetmutreja — CHANGES_REQUESTED** [review]
Requested a few changes.

**Comment by vbhv14** [comment]
> Requested a few changes.

done, thanks.

**Comment by priyankatuteja** [comment]
@BP-Ent Please review this one. Thanks!

**Review by priyankatuteja — CHANGES_REQUESTED** [review]
@vbhv14 I have suggested few changes. Thanks for giving this great sample.

**Comment by BP-Ent** [comment]
@priyankatuteja Hi Priyanka, would it be easier for me to edit this after your initial changes are implemented?

**Comment by AtmaMani** [comment]
@BP-Ent yes, I'd wait until previous reviewers comments are addressed

**Comment by BP-Ent** [comment]
Thanks, @AtmaMani!

**Review by guneetmutreja — APPROVED** [review]
The code in the NB is tested and it now runs without any errors.
Approving it.

Others can have a look at the design point and grammar errors in the NB.

**Review by BP-Ent — CHANGES_REQUESTED** [review]
Suggested changes made in ReviewNB

**Review by vssk88 — APPROVED** [review]

**Comment by vbhv14** [comment]
continued on https://github.com/Esri/arcgis-python-api/pull/823.
After incorporating the suggested changes here.

**Pull request closed without merging**
