### PR TITLE
Covid19 sample - part 1

### PR DESCRIPTION
**Pull request by nanaeaubry**
Updated the code, ran the code, updated the screenshots

### CODE REVIEW

**Review by cariashuang0417 — APPROVED** [review]
Code and maps looks good through locally built developer websites! Left some suggestions of data change and new mapping module related changes for the narrative

**Review by jyaistMap — CHANGES_REQUESTED** [review]
submitted #1984 with changes to this pr

**Comment by jyaistMap** [comment]
<p>I'm leaving the note as is since it still displays the data as of 2021. I think at the release after 2.4 we'll remove these samples since the Covid epidemic is in a different phase.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1975/discussion/#comment-2316769874'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jyaistMap** [comment]
<p>Updated.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1975/discussion/#comment-2316769915'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jyaistMap** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1975/discussion/#comment-2316769932'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jyaistMap** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1975/discussion/#comment-2316769947'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
