### PR TITLE
adding a new sample for automatic natural disaster identification

### PR DESCRIPTION
**Pull request by CMPeng**
with the title specified in 
`add_to_map.add_layer(fc, {"title": event["title"]})`

Now the web map shows layers in the TOC, though these added FC still would not list as linked layers on the item home page - https://datascienceqa.esri.com/portal/home/item.html?id=0564444477744b88978b67937b315987

Another issue, is that renderers did not seem to work as in -
`add_to_map.add_layer(fc, renderer_var)`
or
`add_to_map.add_layer(fc, renderer_dict[disaster_type])`
Seems that feature collection as input cannot be rendered with pre-defined symbols (location-based). Is there a way that I can set the symbol or renderer somewhere else?

Lastly, if changing the gis connection to be on AGO, then the web map being created is not showing feature collection but tables. Is this a bug? https://geosaurus.maps.arcgis.com/home/item.html?id=f317cfea51ca45cbbf0ccb8f21dcb471

### CODE REVIEW

**Comment by CMPeng** [comment]
Hi @AtmaMani 
This is not yet the final draft. Just curious do you know why I am getting server error when I tried to run this against pythonapi playground? e.g. 
image

But it works fine to datascienceqa.

**Comment by CMPeng** [comment]
**Ready for review** @AtmaMani 
This is the part 1 of natural disaster auto identification. Because of the length and also results from "part 2" has not been good enough, is it ok that I check in this one first?
Also Atma, please advise if it is OK to have the top three images shown like this? Thanks!

**Comment by AtmaMani** [comment]
@CMPeng this is a very useful notebook that illustrates how the automation and data wrangling aspects of the Python and the API can benefit a decision maker. However, it is a bit complex to read, some of it may be due to wrangling GeoJSON. What are your thoughts on using an external library to read GeoJSON? Can you explore shapely, geojsonio, geopandas for IO?

Apart from that, some minor comments are below:
 - [very beginning] Can we display these images in simple markdown cells instead of using display() function? Why should we read them in as Image files? We don't appear to analyze them later on.
 - [Step1. preparation] Rewrite as "If you would like to save the resulting web map to a different portal, say your ArcGIS Enterprise deployment, then create another GIS object for that portal. Like earlier, the GIS connection can be created via profile, or using u/p..."
 - [exact search function] Should you do the actual search after the if/else block that adjusts the item type string? It appears changed string is not used later on in the current implementation
 - [text below exact search] Replace "This" with "The" in "This Python API displays maps..."
 - [Step 2: Understanding...]     Understanding the data structure of **the EO** Feed.
    Collector of events **has** listed the geospatial 
 - [splidDataFrameList function] can we snake the method name instead of camel casing it? I suggest renaming to "split_DataFrame_list()". Same for the function defined inside
 - [map3 output] Can we animate this as a GIF? I think the code will animate the widget, would be good to capture that as GIF and embed

Overall, I really like this notebook. I can see many people benefitting from this work.

**Comment by CMPeng** [comment]
Hi @AtmaMani 
When you have time, can you please take a look at this PR VS. https://github.com/Esri/arcgis-python-api/pull/437? Different implementations. This PR is reading it as in JSON, while the #437 is reading it as GeoJSON. 
I can explain the difference in person, if that is easier :)
Thanks!!

**Comment by AtmaMani** [comment]
@CMPeng can we close this in favor of #437 ?

**Comment by CMPeng** [comment]
Sure! thanks @AtmaMani

**Pull request closed without merging**
