### PR TITLE
Updated sample notebook to use data in pythonapi playground

### PR DESCRIPTION
**Pull request by jyaistMap**
* changed url for GIS to use python api playground
* edited convert features to raster cell to use units of spatial reference

### CODE REVIEW

**Comment by DavidJVitale** [comment]
This looks good @jyaistMap , all code cells appear to work. One quick thing to check, is this square output the expected layer to be drawn?

screen shot 2018-08-01 at 9 37 56 am

**Comment by AtmaMani** [comment]
@DavidJVitale yes, this is expected, you are just seeing the extent of the polygon layer (rectangular borders).

@jyaistMap towards the end you are specifying the cell size in decimal degrees, I think specifying in feet is preferable (original code) as it is easier to think in terms of feet and the analysis started off with the same cell size earlier when running the `calculate_density()` operation

**Comment by jyaistMap** [comment]
@AtmaMani 
* The `convert_feature_to_raster` function repeatedly failed unless I used the units of the input spatial reference (in this case, decimal degrees for 4326). Running the tool with the value of 150 feet attempted to create an output raster cell size of 150 degrees and failed:
```pytb
Failed.
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-35-5f2c78fc9195> in <module>()
      1 buffer_raster = convert_feature_to_raster(commercial_buffers.layers[0],
      2                                           output_cell_size={'distance':150, 'units':'feet'},
----> 3                                           output_name='buffer_raster_jy81')

/opt/conda/lib/python3.6/site-packages/arcgis/raster/analytics.py in convert_feature_to_raster(input_feature, output_cell_size, value_field, output_name, gis)
    371     task_url, job_info, job_id = _analysis_job(gptool, task, params)
    372 
--> 373     job_info = _analysis_job_status(gptool, task_url, job_info)
    374     job_values = _analysis_job_results(gptool, task_url, job_info, job_id)
    375     item_properties = {

/opt/conda/lib/python3.6/site-packages/arcgis/geoprocessing/_support.py in _analysis_job_status(gptool, task_url, job_info)
    147 
    148                 if job_response.get("jobStatus") == "esriJobFailed":
--> 149                     raise Exception("Job failed.")
    150                 elif job_response.get("jobStatus") == "esriJobCancelled":
    151                     raise Exception("Job cancelled.")

Exception: Job failed.
```
* Testing with the `Feature to Raster` gp tool in Pro (which I'm assuming is the tool the service is based on) defaults to a value of 5.36932116000344E-04. It generates an empty raster when using a value of 150 in Pro on a gdb fclass of the heart attack incidence.
* I tested of a Feature Collection projected into State Plane (wkid 2272) and I could use a value of 150 feet in the `convert_feature_to_raster` function, but when using data projected but the `zone_map.draw(commercial_buffers)` was adding that layer in Africa and I was unable to use `project` to get it to work.

I concluded the best option was to make a note in the markdown cell that convert_feature_to_raster used the units of the input spatial reference. Let me know your thoughts.

**Comment by AtmaMani** [comment]
@jyaistMap thanks for the explanation. Ok, we will go with your changes. We can check with spatial analyst team if this is to be expected.

**Pull request merged**
