### PR TITLE
Predict floods notebook

### PR DESCRIPTION
**Pull request by priyankatuteja**
https://learn.arcgis.com/en/projects/predict-floods-with-unit-hydrographs/

### CODE REVIEW

**Comment by priyankatuteja** [comment]
@CMPeng You had beautifully reviewed the crime clustering notebook. If you could review this one also. Thanks!

**Comment by CMPeng** [comment]
<p>Thanks @<a href="https://github.com/priyankatuteja" target="_blank">priyankatuteja</a> for contributing this great notebook, I really like this in-depth walk-through of dealing with water flow velocity, time and unit hydrographs.</p><p>Besides what are addressed in previous comments, I would also suggest that you can please add one line to the first paragraph of introduction, it might be something like "the steps and the output maps will look like ..." (well, in a better way than what I wrote here).</p>

**Comment by priyankatuteja** [comment]
<p>it's actually not missing but the resulting raster is also black colored. I'll update this map with blue colored pixel to differentiate it</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/661/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by priyankatuteja** [comment]
<p>yes they look perfect in the notebook</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/661/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by priyankatuteja** [comment]
<p>i am using the defaults which is NORMAL and D8. I am adding a hyperlink to api reference.Does that work</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/661/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by priyankatuteja** [comment]
<p>yes, looks like you are right. I tried with data_type as "float" as well as "integer". It gives same result.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/661/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by priyankatuteja** [comment]
<p>values less that 0.02 will be mapped to 0.02 and same happens for values above 2.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/661/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by priyankatuteja** [comment]
<p>it is a standalone table not attached to a raster</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/661/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by priyankatuteja** [comment]
@CMPeng I have incorporated the changes. Thanks a lot!

**Comment by AtmaMani** [comment]
@priyankatuteja thank you for this sample, @CMPeng thank you for the detailed reviews.

**Pull request merged**
