### PR TITLE
pavement cracks sample notebook

### PR DESCRIPTION
**Pull request by priyankatuteja**
- [x] All `import`s are in the first cell? First block of imports are standard libraries, second block are 3rd party libraries, third block are all `arcgis` imports?
- [x] All `GIS` object instantiations are one of the following?
    - `gis = GIS('https://www.arcgis.com', 'arcgis_python', 'P@ssword123')`
    - `gis = GIS(profile="your_online_profile")`
    - `gis = GIS('https://pythonapi.playground.esri.com/portal', 'arcgis_python', 'amazing_arcgis_123')`
    - `gis = GIS(profile="your_enterprise_portal")`
- [x] If this notebook requires setup or teardown, did you add the appropriate code to `./misc/setup.py` and/or `./misc/teardown.py`?
- [x] If this notebook references any portal items that need to be staged on AGOL/Python API playground, did you coordinate with a Python API team member to stage the item the correct way with the api\_data\_owner user?
- [x] Code refactored & split out across multiple cells, useful comments?
- [x] Consistent voice/tense/narrative style? Thoroughly checked for typos?
- [x] All images used like `` instead of ``? All map widgets contain a static image preview? (Call `mapview_inst.take_screenshot()` to do so)
- [x] All file paths are constructed in an OS-agnostic fashion with `os.path.join()`? (Instead of `r"\foo\bar"`, `os.path.join(os.path.sep, "foo", "bar")`, etc.)
- [ ] **IF YOU WANT THIS SAMPLE TO BE DISPLAYED ON THE DEVELOPERS.ARCGIS.COM WEBSITE**, ping @ DavidJVitale so he can add it to the list for the next deploy

### CODE REVIEW

**Comment by AtmaMani** [comment]
@Yongyao could you review this?

**Comment by priyankatuteja** [comment]
@AtmaMani and @Yongyao I need to make further changes to this workflow. So, I will let you know when this gets ready for review.

**Comment by priyankatuteja** [comment]
@AtmaMani and @Yongyao This notebook is ready to review.

**Comment by priyankatuteja** [comment]
@Yongyao Thanks! This was useful.

**Comment by priyankatuteja** [comment]
@Yongyao This sample also needs to have code which converts the data into  format that arcgis.learn expects. As discussed with @rohitgeo, I will add that part after which you may review it again.
Thanks

**Comment by AtmaMani** [comment]
@priyankatuteja I am applying the 'DO NOT MERGE' label. Please remove it when you add the additional content and you think is ready for final reviews

**Comment by priyankatuteja** [comment]
@Yongyao I do not permissions to remove DO NOT MERGE label from this PR. This notebook is ready for review. Could you remove the label and help in review.

**Comment by priyankatuteja** [comment]
@AtmaMani Thanks for the review, The idea to convert a dataframe to spatially enabled dataframe using from_xy is really helpful. code looks much better. I have made the changes. Can you please have a look at those and let me know if this is fine.

**Comment by Boukary** [comment]
Hi @priyankatuteja, @AtmaMani 

This notebook is really useful, Thanks a lot for the effort
I have a couple of questions if possible : 

1 - how many epochs do I need to achieve the same accuracy you have in the notebook with ssd-resnet101 ?
2 - how can I access the "crack points" feature layer generated? it s owned by "demos_deldev" account. I searched in "arcgis_python" demo accounts but couldn't find it. [(link)](https://developers.arcgis.com/python/sample-notebooks/automate-road-surface-investigation-using-deep-learning/)
3 - Where can I find the videos you used in prediction ? are GPS locations for each frame embedded in that video? 

Thanks in advance

**Comment by priyankatuteja** [comment]
> Hi @priyankatuteja, @AtmaMani
> 
> This notebook is really useful, Thanks a lot for the effort
> I have a couple of questions if possible :
> 
> 1 - how many epochs do I need to achieve the same accuracy you have in the notebook with ssd-resnet101 ?
> 2 - how can I access the "crack points" feature layer generated? it s owned by "demos_deldev" account. I searched in "arcgis_python" demo accounts but couldn't find it. [(link)](https://developers.arcgis.com/python/sample-notebooks/automate-road-surface-investigation-using-deep-learning/)
> 3 - Where can I find the videos you used in prediction ? are GPS locations for each frame embedded in that video?
> 
> Thanks in advance

@Boukary Thanks for your response!
1. I trained the model for 30 epochs as shown in the sample notebook.
2. Really sorry for this trouble. Please find the crack points layer at https://geosaurus.maps.arcgis.com/home/item.html?id=dd8d79434c9d4a7e9fed0cfd16a8efd9
3. Yes, the video has GPS info. I have uploaded the video and its corresponding csv file at https://geosaurus.maps.arcgis.com/home/item.html?id=c27597f2cd394d6e9c3770d645355123.

**Comment by kawtarelk** [comment]
Hi @priyankatuteja a massive thank you for your effort 
can you help me plz to find code of  satellite images segmentation for agricultural fields

**Comment by priyankatuteja** [comment]
@kawtarelk I am not sure if I got your question but still trying to answer it, 
https://github.com/Esri/arcgis-python-api/blob/master/samples/04_gis_analysts_data_scientists/land_cover_classification_using_unet.ipynb is an example of semantic segmentation and https://github.com/Esri/arcgis-python-api/blob/master/samples/04_gis_analysts_data_scientists/automate_building_footprint_extraction_using_instance_segmentation.ipynb for instance segmentation, Provided you have labeled agriculture data, you could use one of these based on your need.

**Comment by priyankatuteja** [comment]
@kawtarelk I am not sure if I got your question but still trying to answer it, 
https://github.com/Esri/arcgis-python-api/blob/master/samples/04_gis_analysts_data_scientists/land_cover_classification_using_unet.ipynb is an example of semantic segmentation and https://github.com/Esri/arcgis-python-api/blob/master/samples/04_gis_analysts_data_scientists/automate_building_footprint_extraction_using_instance_segmentation.ipynb for instance segmentation, Provided you have labeled agriculture data, you could use one of these based on your need.

**Comment by Boukary** [comment]
Hi @priyankatuteja @AtmaMani 

Thanks a lot for uploading the CSV file and video for road defect detection (i didn't check it in detailed but I think the video is not the same you have in the notebook, no worries, thanks for that)

I m using an AWS P2 Linux instance to train a Unet segmentation model, and I m using the export deep learning tool in ArcGIS Pro to prepare the training samples, but uploading this big data (9GB) from my windows laptop to Linux VM takes a lot of time. 

So I decided to use ArcGIS python API (arcgis v1.8.0) in Linux to prepare data over there. I have 2 questions basically : 
1 - how can I open a big .tif image in a map (in a jupyter notebook on Linux)
2 - if I should use the [Raster class](https://developers.arcgis.com/python/api-reference/arcgis.raster.toc.html#arcgis.raster.Raster) in raster module to load this local .tif image, how can I install arcpy with arcgis 1.8.0, I tried with conda install and pip install but it didn't work?

Thanks in advance

**Comment by DavidJVitale** [comment]
Hi @Boukary , `arcpy` is a licensed Esri product that can only be run in an ArcGIS Pro context -- since ArcGIS Pro is Windows only, running arcpy in Linux is not supported. So the Raster class won't work for you at this time on your Linux machine unless you upload the image as an imagery service, which I'm guessing defeats the whole purpose for you. Sorry about the inconvenience.

If you need a solution right now for viewing local rasters in a jupyter notebook on a Linux machine, you could try using [rasterio](https://rasterio.readthedocs.io/en/latest/quickstart.html). It might have enough tools to fit your need for viewing/analyzing a local static tif image.

**Comment by Boukary** [comment]
Hi @DavidJVitale 

Thanks a lot for the quick reply,

I see what you are saying, fortunately my final goal is not viewing, it s actually training an Unet model with my local raster on Linux GPU VM, following this[ tutorial notebook
](https://developers.arcgis.com/python/sample-notebooks/extracting-building-footprints-from-drone-data/), 
Is it possible to prepare the data for deep learning (preprocessing + exporting) without using arcpy?
Is there any way to run ArcGIS Pro 2.5 in Linux ? with Wine for example?

Thanks

**Pull request merged**
