### PR TITLE
New solar

### PR DESCRIPTION
**Pull request by moonlanderr**
\<insert pull request description here\>

-----

# Checklist

Please go through each entry in the below checklist and mark an 'X' if that condition has been met. Every entry should be marked with an 'X' to be get the Pull Request approved.

- [ ] All `import`s are in the first cell? First block of imports are standard libraries, second block are 3rd party libraries, third block are all `arcgis` imports? Note that in some cases, for samples, it is a good idea to keep the imports next to where they are used, particularly for uncommonly used features that we want to highlight.
- [ ] All `GIS` object instantiations are one of the following?
    - `gis = GIS()`
    - `gis = GIS('https://www.arcgis.com', 'arcgis_python', 'P@ssword123')`
    - `gis = GIS(profile="your_online_profile")`
    - `gis = GIS('https://pythonapi.playground.esri.com/portal', 'arcgis_python', 'amazing_arcgis_123')`
    - `gis = GIS(profile="your_enterprise_portal")`
- [ ] If this notebook requires setup or teardown, did you add the appropriate code to `./misc/setup.py` and/or `./misc/teardown.py`?
- [ ] If this notebook references any portal items that need to be staged on AGOL/Python API playground, did you coordinate with a Python API team member to stage the item the correct way with the api\_data\_owner user?
- [ ] Code refactored & split out across multiple cells, useful comments?
- [ ] Consistent voice/tense/narrative style? Thoroughly checked for typos?
- [ ] All images used like `` instead of ``? All map widgets contain a static image preview? (Call `mapview_inst.take_screenshot()` to do so)
- [ ] All file paths are constructed in an OS-agnostic fashion with `os.path.join()`? (Instead of `r"\foo\bar"`, `os.path.join(os.path.sep, "foo", "bar")`, etc.)
- [ ] **IF YOU WANT THIS SAMPLE TO BE DISPLAYED ON THE DEVELOPERS.ARCGIS.COM WEBSITE**, ping @ DavidJVitale so he can add it to the list for the next deploy

### CODE REVIEW

**Comment by AtmaMani** [comment]
@moonlanderr is this PR a work in progress or ready for review?

**Comment by moonlanderr** [comment]
@AtmaMani this is ready for review, after including Brecks' suggestion

**Comment by AtmaMani** [comment]
@BP-Ent could you do the first round of reviews?

**Comment by BP-Ent** [comment]
@AtmaMani if I'm not mistaken, much of the review for this notebook was already performed in this [issue](https://github.com/Esri/arcgis-python-api/pull/688) [notebook](https://app.reviewnb.com/Esri/arcgis-python-api/pull/688/files/). I'm not sure how the two got separated .

**Comment by moonlanderr** [comment]
@AtmaMani, @BP-Ent , yes almost all of it was reviewed by @BP-Ent , and his suggestion is included in this PR, it can be taken up by the next reviewer. Only a new graph was added in this PR.

**Comment by BP-Ent** [comment]
@moonlanderr @AtmaMani Looking at the current ReviewNB in this PR, the changes suggested previously are not present. Should they be showing in ReviewNB?

**Comment by AtmaMani** [comment]
@BP-Ent since this is a new PR, the comments made in the old PR may not show up as comments in this one. However, per @moonlanderr's note, the comments should be incorporated into the content of the notebook itself. If you are not finding those, please let us know. Else, I will review this PR early next week and merge it.

**Comment by BP-Ent** [comment]
@AtmaMani @moonlanderr Sorry, that's what I meant. The previous suggested changes aren't present in the content of the Notebook itself. At least when viewed in ReviewNB.

Previous suggestions:
image


Current view in ReviewNB:
image

**Comment by AtmaMani** [comment]
@moonlanderr could you look into this?

**Comment by moonlanderr** [comment]
@BP-Ent added the previous suggestions which were missing, can you check it now

**Comment by BP-Ent** [comment]
@moonlanderr Just found two minor edits.

**Review by BP-Ent — CHANGES_REQUESTED** [review]
Two small changes made in ReviewNB.

**Comment by moonlanderr** [comment]
@AtmaMani @BP-Ent all changes are added

**Comment by AtmaMani** [comment]
@moonlanderr can you delete the duplicate file and rename the other one appropriately?

**Comment by moonlanderr** [comment]
@AtmaMani deleted the duplicate file, and for the renaming if it is okay I would like to retain the name, since it actually helps me in keeping track of the current file out of the several edited files that I work on

**Comment by AtmaMani** [comment]
@moonlanderr unfortunately our production system uses filenames for slugs (urls). As you can imagine, we want the urls to be indicative of the content, hence the request to change the filename. As before, file names need to be in all lowercases, hyphens between words (instead of underscores) to make them urlsafe.

**Comment by moonlanderr** [comment]
@AtmaMani renamed the file with lowercases and hyphens

**Comment by moonlanderr** [comment]
@AtmaMani do you have any suggestions/update for the solar sample after your review

**Comment by AtmaMani** [comment]
@moonlanderr I still don't see the file names changed. I notice your commit but it does not seem to make the change

**Comment by priyankatuteja** [comment]
@ArcGISPyAPIBot retest this please

**Comment by moonlanderr** [comment]
@AtmaMani can you check now - changed the filename

**Review by AtmaMani — APPROVED** [review]

**Pull request merged**
