### PR TITLE
Added image to reflect set_time_extent operation in Hurricane Geoanalytics sample.

### PR DESCRIPTION
**Pull request by jyaistMap**
* Current image reflects results from _add_layer(agg_result)_
* This image reflects _set_time_extent('1860', '1870')_ run in last cell
* PR to update the [Hurricane Geoanalytics sample](https://developers.arcgis.com/python/sample-notebooks/creating-hurricane-tracks-using-geoanalytics/) to reference the pythonapi playground data forthcoming

### CODE REVIEW

**Comment by jyaistMap** [comment]
@DavidJVitale Current notebook on developer's site references images with upper case _PNG_ and are not displaying:
  * [subset_map](http://esri.github.io/arcgis-python-api/notebooks/nbimages/04_HurricaneGeoanalytics_01.PNG) at beginning of notebook: 
  * [processed_map](http://esri.github.io/arcgis-python-api/notebooks/nbimages/04_HurricaneGeoanalytics_02.PNG) at end of notebook

Do we need to change the image extensions of the files at esri.github.io to get around the developer site bug?

**Comment by DavidJVitale** [comment]
@jyaistMap, I was only aware of the uppercase .png file bug being specific to images that are being hosted by the developer's website. If they are being hosted by esri.github.io, I don't see why an uppercase .png would cause an error. __provided that both the notebook and the file hosted on github.io have both .png or both .PNG__.

I can see both of those images on the on the hurricane geoanalytics sample developer's website page, can you not?

**Comment by jyaistMap** [comment]
@AtmaMani Can you approve this PR so I can do the subsequent PR to get the hurricanes sample updated? This image will reflect the last cell run in the notebook as it stands right now. I'll continue today to research creating the gif animating through 10-yr intervals.

**Comment by jyaistMap** [comment]
Hi @AtmaMani @rohitgeo @DavidJVitale The updated notebook is online at [Creating hurricane tracks using GeoAnalytics](http://localhost:8000/python/sample-notebooks/creating-hurricane-tracks-using-geoanalytics/), but the image uploaded used to illustrate filtering on _map.set_time_extent_ is not loaded to esri.github.io yet so the _Alt_text_ is what appears online. Can one of you transfer the image from [here](https://github.com/Esri/arcgis-python-api/blob/gh-pages/notebooks/nbimages/04_HurricaneGeoanalytics_time.png) to esri.github.io?

**Comment by AtmaMani** [comment]
@jyaistMap the issue was casing of the extension (.PNG vs .png). I updated and pushed the image to gh-pages, should be fixed now.

**Pull request merged**
