### PR TITLE
Update raster data and notebook

### PR DESCRIPTION
**Pull request by nanaeaubry**
Closes: https://github.com/ArcGIS/geosaurus/issues/9339

Update with new data found by Manushi and re-run the notebook

### CODE REVIEW

**Review by ManushiM — APPROVED** [review]
Looks good to me! Thanks!

**Comment by nanaeaubry** [comment]
@ManushiM  It won't let me merge for some reason. Can you do it?

**Review by ManushiM — APPROVED** [review]

**Comment by ManushiM** [comment]
for some reason it also doesn't let me merge. @jyaistMap can you please take a look at this?

**Review by jyaistMap — CHANGES_REQUESTED** [review]
@ManushiM @nanaeaubry 

* the notebook still displays the credentials for the `arcgis_python` user - can we please change those to `your_enterprise_profile`?
* if the data changes, from what I see, the raster functions applied to the new data are different from the original data, changing the display. The original guide used a gif to display a loop through raster functions:
  * in the [Imagery Layers](https://developers.arcgis.com/python/samples/creating-raster-information-product-using-raster-analytics/#imagery-layers) section, the cell calls the gif located at _`../static/img/sample_04_rasterinfo2.gif`.  Changing the data will require producing a new gif and/or applying a different set of raster functions to the Imagery Layer for display
* The tabbed map in the last cell also utilizes a gif
  * the last cell of the notebook displays the gif at `../static/img/sample_04_rasterinfo_tab.gif` and a new gif needs produced to display in this notebook

adding @rhea-j @kreetichandran to assist

**Comment by rhea-j** [comment]
Can we directly use the service instead of accessing the item. 
In that we can continue using the Landsat 8 Views imagery layer

imglyr = arcgis.raster.ImageryLayer('https://landsat2.arcgis.com/arcgis/rest/services/Landsat8_Views/ImageServer')

**Comment by nanaeaubry** [comment]
@rhea-j @jyaistMap @ManushiM 
Please see new implementation, I changed credentials and access the imagery layer directly

**Review by rhea-j — APPROVED** [review]

**Comment by nanaeaubry** [comment]
@jyaistMap I can't merge this for some reason. Can you please merge it?

**Pull request merged**
