### PR TITLE
Find Places Devlab

### PR DESCRIPTION
**Pull request by mpayson**
Solution for a new Python Find Places DevLab. The DevLab preview is available internally [here](https://mp-py-devlab-find-places-preview-dev.developers.arcgis.com/labs/python/find-places/)

### CODE REVIEW

**Comment by DavidJVitale** [comment]
@AtmaMani did you test this with the new widget? Do you want me to run through that?

**Comment by AtmaMani** [comment]
@DavidJVitale Yes, could you check this against the new widget?

**Comment by mpayson** [comment]
thanks Atma, [done](https://github.com/Esri/arcgis-python-api/pull/290/commits/45365bb68a323632518cad58dfba15ae6feb0ccb#diff-6c65f073186bb4a49d4f49f3058c15c3R171)!

**Comment by AtmaMani** [comment]
@mpayson could you send this PR to `dev_site_current` instead of `master`? This will helps us deploy to production via CICD.

**Comment by AtmaMani** [comment]
@mpayson I am working on doing a manual merge of this

**Comment by mpayson** [comment]
closing and switching to #295

**Pull request closed without merging**
