### PR TITLE
Added Glacial Terminus extraction notebook

### PR DESCRIPTION
**Pull request by guneetmutreja**
Contains sample notebook to showcase MMSegmentation capability in the form of glacial terminus extraction usecase.

### CODE REVIEW

**Comment by priyankatuteja** [comment]
@anushriyaj Please review this PR.

**Comment by priyankatuteja** [comment]
@anushriyaj Please review this PR.

**Review by anushriyaj — APPROVED** [review]
LGTM

**Comment by AtmaMani** [comment]
@BP-Ent could you please review this PR?

**Review by BP-Ent — CHANGES_REQUESTED** [review]
Suggested change made on reviewNB

**Comment by guneetmutreja** [comment]
@shivanip32 @BP-Ent I have amended the changes you both have suggested. Please have a look at them.

**Review by shivanip32 — APPROVED** [review]
LGTM

**Review by AtmaMani — APPROVED** [review]

**Comment by AtmaMani** [comment]
@guneetmutreja thanks for this great sample. The results from the DL model is quite powerful. @anushriyaj @shivanip32 @BP-Ent thanks for your detailed reviews.

**Review by BP-Ent — COMMENTED** [review]
LGTM

**Pull request merged**
