### PR TITLE
`analyzing_growth_factors_of_airbnb_properties_in_new_york_city.ipynb` sample notebook now running and fixed

### PR DESCRIPTION
**Pull request by tarunkukreja003**
sample notebook fixed and corrected
resolves [9750](https://github.com/ArcGIS/geosaurus/issues/9750)

### CODE REVIEW

**Review by ManushiM — APPROVED** [review]
LGTM

**Comment by jyaistMap** [comment]
@tarunkukreja003 

the cells where the map widget appear are not correctly displaying. For guides and samples, please refer to the [How to embed map images in your notebooks wiki](https://github.com/Esri/arcgis-python-api/wiki/How-to-embed-map-images-in-your-notebooks) for instructions and let me know if you have questions.

image

image

**Review by jyaistMap — CHANGES_REQUESTED** [review]
Map widget cells need updated.

**Review by jyaistMap — APPROVED** [review]
Thanks, @tarunkukreja003!

**Pull request merged**
