### PR TITLE
Sample notebook for extracting building footprints from drone data

### PR DESCRIPTION
**Pull request by sandeepgadhwal**
Adding Sample Notebook for "Extracting Building Footprints From Drone Data"

### CODE REVIEW

**Comment by AtmaMani** [comment]
@sandeepgadhwal is this a work in progress or ready for review?

**Comment by sandeepgadhwal** [comment]
It can be reviewed now.

Get Outlook for Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__aka.ms_ghei36&d=DwIF-g&c=n6-cguzQvX_tUIrZOS_4Og&r=ZJq8Nd_Nq2m-nKxK1E3YdfSi_C6zqdne6SK5q5vp3URCh9dy72-sUiwh91yK08hBqvfOP9Ek4ja03AhauWbZajnH4nyLuZhbxymt0BpMREA&m=gPVzl-k7jkh14q78z5-jQ1DVz3xSsTwOZb9Mz9kgO1A&s=ddKDVReqGHICVHK93EvltPnWqUjbZeDGveueRrhvm2o&e= >

________________________________

**Comment by priyankatuteja** [comment]
**Suggestions**:
1) Add Table of contents 

2) This is an example of how you can explain your workflow. I wrote it from my point of understanding, you can edit this too. 

> (Building footprints is one of the popular GIS layers which is widely used 
> for visualization and analysis. Some of the popular analysis include 
> base map preparation, humanitarian aid and disaster management 
> and transportation problem. 
> 
> There are several ways of generating building footprints. 
> One of these include manual digitization by using tools to draw outline of a building. 
> However, it is a labor intensive and time consuming process. To overcome these problems,
> deep learning integrated with ArcGIS is a modern approach to automate the
> extraction of building footprints.
> 
> In this sample, we will go through the following workflows:
> 1) Exporting data 
> 2) Training a building footprint model 
> 3) Extracting footprints 
> 
> We will use map image service that has labelled footprints for the region affected by Woolsey fires as an input for exporting images.
> We will then feed these exported images into deep learning model for training. 
> After the model gets trained, we will generate building footprints on desired/umlabelled area of  image service. 
> 
> Note:
> The workflow uses ArcGIS Pro/ArcGIS enterprise in step 1 and 
> 3 and ArcGIS Learn module available in ArcGIS API for Python in step 2.)

3) The code parameters should have proper indentation.
image


image

4) Take reference from PR template https://github.com/Esri/arcgis-python-api/blob/master/PULL_REQUEST_TEMPLATE.md and documentation guide https://github.com/Esri/arcgis-python-api/wiki/How-to-contribute-samples-and-guide-chapters to edit rest of the sample doc accordingly.

**Comment by AtmaMani** [comment]
@sandeepgadhwal the improvements are looking better, but it needs some more work. Further, this sample might be better suited in the ArcGIS Notebook server gallery. Could you send a PR there? Closing this PR meanwhile.

**Comment by rohitgeo** [comment]
@atmamani the sample needs to go in the public repo and developer website. It was built for the purpose of economy Deep learning workflow for users without ArcGIS Enterprise. It can additionally go in the Notebooks server gallery. Please be more specific in what work needs to be done in the sample and let's work on that.

**Comment by AtmaMani** [comment]
@sandeepgadhwal changes look good. AS discussed earlier, can you rename the file name?

**Comment by AtmaMani** [comment]
this should be good to merge after the rename.

**Comment by sandeepgadhwal** [comment]
@AtmaMani renamed.

**Comment by Boukary** [comment]
Hi @rohitgeo,  

I tried to use this notebook to segment no vegetation areas in high-resolution images, the trained model is good based on the results I have from show_results() function. but when I deploy the Unet model in ArcGIS Pro using **"Classify Pixels using Deep Learning"**. I got those weird results :
image
segmentation_no_vegetation_results

Thanks
Abderrahim

**Comment by rohitgeo** [comment]
Hi Abderrahim, these results indeed look strange. Would it be possible for you to share a Pro package and model exhibiting this problem so we can take a closer look? You can reach out to me via email.

**Comment by rohitgeo** [comment]
Also can you double check the cell size parameter when inferencing and changing that?

**Comment by Boukary** [comment]
Thanks @rohitgeo,

I was using default cell size, I changed it but same results
I emailed you the model packages in rsingh@esri.com

Thanks a lot for your help

**Comment by Boukary** [comment]
Hi @rohitgeo 

were you able to reproduce the issue? or is this something related to my machine and my environment ?

**Comment by rohitgeo** [comment]
@Boukary the link to your isnt working.

**Comment by Boukary** [comment]
Hi @rohitgeo,  

Sorry for the delay, I was dealing with some GPU issues in my VM, I was using one with compute capability = 3 
Now I have a better GPU with **CC = 5**, and it solved my issue

Thanks for your time
Abderrahim
image
image
image

**Pull request merged**
